
__ctr_start 0x00100000
{
	__ctr_start 0x00100000
	{
		* (:gdef:__ctr_start)
	}
}
_printf_percent 0x00100048
{
	_printf_percent 0x00100048
	{
		* (i._printf_percent)
	}
}
_printf_s 0x001000e8
{
	_printf_s 0x001000e8
	{
		* (i._printf_s)
	}
}
_printf_percent_end 0x00100100
{
	_printf_percent_end 0x00100100
	{
		* (i._printf_percent_end)
	}
}
nnMain 0x00100108
{
	nnMain 0x00100108
	{
		* (i.nnMain)
	}
}
_ZN2nn2fs28ForceDisableLatencyEmulationEv 0x0010073c
{
	_ZN2nn2fs28ForceDisableLatencyEmulationEv 0x0010073c
	{
		* (i._ZN2nn2fs28ForceDisableLatencyEmulationEv)
	}
}
_ZN2nn3svc16GetResourceLimitEPNS_6HandleES1_ 0x001008c0
{
	_ZN2nn3svc16GetResourceLimitEPNS_6HandleES1_ 0x001008c0
	{
		* (i._ZN2nn3svc16GetResourceLimitEPNS_6HandleES1_)
	}
}
_ZN2al9SystemKit16createFileLoaderEi 0x00100d50
{
	_ZN2al9SystemKit16createFileLoaderEi 0x00100d50
	{
		* (i._ZN2al9SystemKit16createFileLoaderEi)
	}
}
_ZN2al9SystemKit20createSaveDataSystemEji 0x001010f0
{
	_ZN2al9SystemKit20createSaveDataSystemEji 0x001010f0
	{
		* (i._ZN2al9SystemKit20createSaveDataSystemEji)
	}
}
_ZN2nn3svc20CreateAddressArbiterEPNS_6HandleE 0x00101b24
{
	_ZN2nn3svc20CreateAddressArbiterEPNS_6HandleE 0x00101b24
	{
		* (i._ZN2nn3svc20CreateAddressArbiterEPNS_6HandleE)
	}
}
_ZN2nn3svc12CreateThreadEPNS_6HandleEPFvjEjjii 0x001038a0
{
	_ZN2nn3svc12CreateThreadEPNS_6HandleEPFvjEjjii 0x001038a0
	{
		* (i._ZN2nn3svc12CreateThreadEPNS_6HandleEPFvjEjjii)
	}
}
_ZN2nn3svc17GetThreadPriorityEPiNS_6HandleE 0x00107404
{
	_ZN2nn3svc17GetThreadPriorityEPiNS_6HandleE 0x00107404
	{
		* (i._ZN2nn3svc17GetThreadPriorityEPiNS_6HandleE)
	}
}
_printf_str 0x0010a31c
{
	_printf_str 0x0010a31c
	{
		* (:gdef:_printf_str)
	}
}
_snputc 0x0010a470
{
	_snputc 0x0010a470
	{
		* (:gdef:_snputc)
	}
}
_ZN2nn3svc11CloseHandleENS_6HandleE 0x0010c56c
{
	_ZN2nn3svc11CloseHandleENS_6HandleE 0x0010c56c
	{
		* (i._ZN2nn3svc11CloseHandleENS_6HandleE)
	}
}
_ZN2nn3svc17CreateMemoryBlockEPNS_6HandleEjjjj 0x0010c574
{
	_ZN2nn3svc17CreateMemoryBlockEPNS_6HandleEjjjj 0x0010c574
	{
		* (i._ZN2nn3svc17CreateMemoryBlockEPNS_6HandleEjjjj)
	}
}
_ZN2nn3svc11CreateMutexEPNS_6HandleEb 0x0010c590
{
	_ZN2nn3svc11CreateMutexEPNS_6HandleEb 0x0010c590
	{
		* (i._ZN2nn3svc11CreateMutexEPNS_6HandleEb)
	}
}
_ZN2nn3svc15DuplicateHandleEPNS_6HandleES1_ 0x0010c5a8
{
	_ZN2nn3svc15DuplicateHandleEPNS_6HandleES1_ 0x0010c5a8
	{
		* (i._ZN2nn3svc15DuplicateHandleEPNS_6HandleES1_)
	}
}
strstr 0x0010c690
{
	strstr 0x0010c690
	{
		* (:gdef:strstr)
	}
}
_ZN10AppearStep11startAppearEv 0x001175a4
{
	_ZN10AppearStep11startAppearEv 0x001175a4
	{
		* (i._ZN10AppearStep11startAppearEv)
	}
}
_ZN10AppearStep14startDisappearEv 0x00117608
{
	_ZN10AppearStep14startDisappearEv 0x00117608
	{
		* (i._ZN10AppearStep14startDisappearEv)
	}
}
_ZN10AppearStepC1ERKN4sead14SafeStringBaseIcEE 0x00117710
{
	_ZN10AppearStepC1ERKN4sead14SafeStringBaseIcEE 0x00117710
	{
		* (i._ZN10AppearStepC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN10Fugumannen10receiveMsgEjPN2al9HitSensorES2_ 0x0011a38c
{
	_ZN10Fugumannen10receiveMsgEjPN2al9HitSensorES2_ 0x0011a38c
	{
		* (i._ZN10Fugumannen10receiveMsgEjPN2al9HitSensorES2_)
	}
}
_ZN10Fugumannen12attackSensorEPN2al9HitSensorES2_ 0x0011a43c
{
	_ZN10Fugumannen12attackSensorEPN2al9HitSensorES2_ 0x0011a43c
	{
		* (i._ZN10Fugumannen12attackSensorEPN2al9HitSensorES2_)
	}
}
_ZN10Fugumannen4initERKN2al13ActorInitInfoE 0x0011a498
{
	_ZN10Fugumannen4initERKN2al13ActorInitInfoE 0x0011a498
	{
		* (i._ZN10Fugumannen4initERKN2al13ActorInitInfoE)
	}
}
_ZN10FugumannenC1ERKN4sead14SafeStringBaseIcEE 0x0011a5b4
{
	_ZN10FugumannenC1ERKN4sead14SafeStringBaseIcEE 0x0011a5b4
	{
		* (i._ZN10FugumannenC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN10GameSystemC1Ev 0x0011ac34
{
	_ZN10GameSystemC1Ev 0x0011ac34
	{
		* (i._ZN10GameSystemC1Ev)
	}
}
_ZN10RailDotEnd4initERKN2al13ActorInitInfoE 0x001217e8
{
	_ZN10RailDotEnd4initERKN2al13ActorInitInfoE 0x001217e8
	{
		* (i._ZN10RailDotEnd4initERKN2al13ActorInitInfoE)
	}
}
_ZN10RailDotEndC1ERKN4sead14SafeStringBaseIcEE 0x00121850
{
	_ZN10RailDotEndC1ERKN4sead14SafeStringBaseIcEE 0x00121850
	{
		* (i._ZN10RailDotEndC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN2al6Camera2v7Ev 0x0012a6ac
{
	_ZN2al6Camera2v7Ev 0x0012a6ac
	{
		* (i._ZN2al6Camera2v7Ev)
	}
}
_ZN2al6Camera2v2Ev 0x0012a6b0
{
	_ZN2al6Camera2v2Ev 0x0012a6b0
	{
		* (i._ZN2al6Camera2v2Ev)
	}
}
_ZN2al6Camera2v4Ev 0x0012a6b4
{
	_ZN2al6Camera2v4Ev 0x0012a6b4
	{
		* (i._ZN2al6Camera2v4Ev)
	}
}
_ZN2al6Camera2v5Ev 0x0012a6b8
{
	_ZN2al6Camera2v5Ev 0x0012a6b8
	{
		* (i._ZN2al6Camera2v5Ev)
	}
}
_ZN2al6Camera2v3Ev 0x0012a6bc
{
	_ZN2al6Camera2v3Ev 0x0012a6bc
	{
		* (i._ZN2al6Camera2v3Ev)
	}
}
_ZN2al6Camera4calcEv 0x0012a6c0
{
	_ZN2al6Camera4calcEv 0x0012a6c0
	{
		* (i._ZN2al6Camera4calcEv)
	}
}
_ZN2al6Camera2v1Ev 0x0012a6c4
{
	_ZN2al6Camera2v1Ev 0x0012a6c4
	{
		* (i._ZN2al6Camera2v1Ev)
	}
}
_ZN11GhostPlayer10receiveMsgEjPN2al9HitSensorES2_ 0x0012c354
{
	_ZN11GhostPlayer10receiveMsgEjPN2al9HitSensorES2_ 0x0012c354
	{
		* (i._ZN11GhostPlayer10receiveMsgEjPN2al9HitSensorES2_)
	}
}
_ZN11GhostPlayer12attackSensorEPN2al9HitSensorES2_ 0x0012c3c8
{
	_ZN11GhostPlayer12attackSensorEPN2al9HitSensorES2_ 0x0012c3c8
	{
		* (i._ZN11GhostPlayer12attackSensorEPN2al9HitSensorES2_)
	}
}
_ZN2al12FallMapParts10receiveMsgEjPNS_9HitSensorES2_ 0x00136f64
{
	_ZN2al12FallMapParts10receiveMsgEjPNS_9HitSensorES2_ 0x00136f64
	{
		* (i._ZN2al12FallMapParts10receiveMsgEjPNS_9HitSensorES2_)
	}
}
_ZN2al12FallMapPartsC1ERKN4sead14SafeStringBaseIcEE 0x00137068
{
	_ZN2al12FallMapPartsC1ERKN4sead14SafeStringBaseIcEE 0x00137068
	{
		* (i._ZN2al12FallMapPartsC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN2al5Scene4killEv 0x0013e224
{
	_ZN2al5Scene4killEv 0x0013e224
	{
		* (i._ZN2al5Scene4killEv)
	}
}
_ZN2al5Scene7controlEv 0x0013e230
{
	_ZN2al5Scene7controlEv 0x0013e230
	{
		* (i._ZN2al5Scene7controlEv)
	}
}
_ZN13PlayerTrigger18clearSensorTriggerEv 0x0014377c
{
	_ZN13PlayerTrigger18clearSensorTriggerEv 0x0014377c
	{
		* (i._ZN13PlayerTrigger18clearSensorTriggerEv)
	}
}
_ZN13PlayerTrigger21clearCollisionTriggerEv 0x00143788
{
	_ZN13PlayerTrigger21clearCollisionTriggerEv 0x00143788
	{
		* (i._ZN13PlayerTrigger21clearCollisionTriggerEv)
	}
}
_ZN13PlayerTriggerC1Ev 0x00143794
{
	_ZN13PlayerTriggerC1Ev 0x00143794
	{
		* (i._ZN13PlayerTriggerC1Ev)
	}
}
_ZN14TrickHintPanel10receiveMsgEjPN2al9HitSensorES2_ 0x0015512c
{
	_ZN14TrickHintPanel10receiveMsgEjPN2al9HitSensorES2_ 0x0015512c
	{
		* (i._ZN14TrickHintPanel10receiveMsgEjPN2al9HitSensorES2_)
	}
}
_ZN14TrickHintPanel4initERKN2al13ActorInitInfoE 0x001551ac
{
	_ZN14TrickHintPanel4initERKN2al13ActorInitInfoE 0x001551ac
	{
		* (i._ZN14TrickHintPanel4initERKN2al13ActorInitInfoE)
	}
}
_ZN14TrickHintPanelC1ERKN4sead14SafeStringBaseIcEE 0x001551f4
{
	_ZN14TrickHintPanelC1ERKN4sead14SafeStringBaseIcEE 0x001551f4
	{
		* (i._ZN14TrickHintPanelC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN15ProductSequenceC1EPKc 0x00163b88
{
	_ZN15ProductSequenceC1EPKc 0x00163b88
	{
		* (i._ZN15ProductSequenceC1EPKc)
	}
}
_ZN15TransparentWall13makeActorDeadEv 0x001674a8
{
	_ZN15TransparentWall13makeActorDeadEv 0x001674a8
	{
		* (i._ZN15TransparentWall13makeActorDeadEv)
	}
}
_ZN15TransparentWall4initERKN2al13ActorInitInfoE 0x001674ac
{
	_ZN15TransparentWall4initERKN2al13ActorInitInfoE 0x001674ac
	{
		* (i._ZN15TransparentWall4initERKN2al13ActorInitInfoE)
	}
}
_ZN15TransparentWallC1ERKN4sead14SafeStringBaseIcEE 0x00167574
{
	_ZN15TransparentWallC1ERKN4sead14SafeStringBaseIcEE 0x00167574
	{
		* (i._ZN15TransparentWallC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN10CourseList4initEPKN2al8ResourceE 0x0016a11c
{
	_ZN10CourseList4initEPKN2al8ResourceE 0x0016a11c
	{
		* (i._ZN10CourseList4initEPKN2al8ResourceE)
	}
}
_ZN10CourseListC1Ev 0x0016a2b4
{
	_ZN10CourseListC1Ev 0x0016a2b4
	{
		* (i._ZN10CourseListC1Ev)
	}
}
_ZN16NoteObjGeneratorC1ERKN4sead14SafeStringBaseIcEE 0x00171830
{
	_ZN16NoteObjGeneratorC1ERKN4sead14SafeStringBaseIcEE 0x00171830
	{
		* (i._ZN16NoteObjGeneratorC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN16alSensorFunction20findSensorTypeByNameEPKc 0x001781ec
{
	_ZN16alSensorFunction20findSensorTypeByNameEPKc 0x001781ec
	{
		* (i._ZN16alSensorFunction20findSensorTypeByNameEPKc)
	}
}
_ZN2al17CameraParamVision4initEPKNS_9ByamlIterE 0x0017a3dc
{
	_ZN2al17CameraParamVision4initEPKNS_9ByamlIterE 0x0017a3dc
	{
		* (i._ZN2al17CameraParamVision4initEPKNS_9ByamlIterE)
	}
}
_ZN17ProductStateTitle4initEv 0x00183c9c
{
	_ZN17ProductStateTitle4initEv 0x00183c9c
	{
		* (i._ZN17ProductStateTitle4initEv)
	}
}
_ZN17ProductStateTitleC1EP15ProductSequenceP22ProductStageStartParamRKN2al14LayoutInitInfoE 0x00183e4c
{
	_ZN17ProductStateTitleC1EP15ProductSequenceP22ProductStageStartParamRKN2al14LayoutInitInfoE 0x00183e4c
	{
		* (i._ZN17ProductStateTitleC1EP15ProductSequenceP22ProductStageStartParamRKN2al14LayoutInitInfoE)
	}
}
_ZN2al18getStageSwitchNameENS_15StageSwitchTypeE 0x0018670c
{
	_ZN2al18getStageSwitchNameENS_15StageSwitchTypeE 0x0018670c
	{
		* (i._ZN2al18getStageSwitchNameENS_15StageSwitchTypeE)
	}
}
_ZN18AquariumSwimDebris4initERKN2al13ActorInitInfoE 0x00186cc8
{
	_ZN18AquariumSwimDebris4initERKN2al13ActorInitInfoE 0x00186cc8
	{
		* (i._ZN18AquariumSwimDebris4initERKN2al13ActorInitInfoE)
	}
}
_ZN18AquariumSwimDebrisC1ERKN4sead14SafeStringBaseIcEE 0x00186d44
{
	_ZN18AquariumSwimDebrisC1ERKN4sead14SafeStringBaseIcEE 0x00186d44
	{
		* (i._ZN18AquariumSwimDebrisC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN2al18CameraRotatorParam4initEPKNS_9ByamlIterE 0x0018791c
{
	_ZN2al18CameraRotatorParam4initEPKNS_9ByamlIterE 0x0018791c
	{
		* (i._ZN2al18CameraRotatorParam4initEPKNS_9ByamlIterE)
	}
}
_ZN2al18CameraRotatorParamC1Ev 0x00187970
{
	_ZN2al18CameraRotatorParamC1Ev 0x00187970
	{
		* (i._ZN2al18CameraRotatorParamC1Ev)
	}
}
_ZN2al16initLiveActorKitEPNS_12LiveActorKitE 0x00189184
{
	_ZN2al16initLiveActorKitEPNS_12LiveActorKitE 0x00189184
	{
		* (i._ZN2al16initLiveActorKitEPNS_12LiveActorKitE)
	}
}
_ZN2al18SwitchAreaDirector8movementEv 0x0018b504
{
	_ZN2al18SwitchAreaDirector8movementEv 0x0018b504
	{
		* (i._ZN2al18SwitchAreaDirector8movementEv)
	}
}
_ZN2al18SwitchAreaDirectorC2Ev 0x0018b54c
{
	_ZN2al18SwitchAreaDirectorC2Ev 0x0018b54c
	{
		* (i._ZN2al18SwitchAreaDirectorC2Ev)
	}
}
_ZN18alSubActorFunction11trySyncDeadEPN2al14SubActorKeeperE 0x0018b9e4
{
	_ZN18alSubActorFunction11trySyncDeadEPN2al14SubActorKeeperE 0x0018b9e4
	{
		* (i._ZN18alSubActorFunction11trySyncDeadEPN2al14SubActorKeeperE)
	}
}
_ZN18alSubActorFunction12trySyncAliveEPN2al14SubActorKeeperE 0x0018ba34
{
	_ZN18alSubActorFunction12trySyncAliveEPN2al14SubActorKeeperE 0x0018ba34
	{
		* (i._ZN18alSubActorFunction12trySyncAliveEPN2al14SubActorKeeperE)
	}
}
_ZN18alSubActorFunction11tryCalcAnimEPN2al14SubActorKeeperE 0x0018ba84
{
	_ZN18alSubActorFunction11tryCalcAnimEPN2al14SubActorKeeperE 0x0018ba84
	{
		* (i._ZN18alSubActorFunction11tryCalcAnimEPN2al14SubActorKeeperE)
	}
}
_ZN18alSubActorFunction18trySyncClippingEndEPN2al14SubActorKeeperE 0x0018bb4c
{
	_ZN18alSubActorFunction18trySyncClippingEndEPN2al14SubActorKeeperE 0x0018bb4c
	{
		* (i._ZN18alSubActorFunction18trySyncClippingEndEPN2al14SubActorKeeperE)
	}
}
_ZN18alSubActorFunction20trySyncClippingStartEPN2al14SubActorKeeperE 0x0018bbc4
{
	_ZN18alSubActorFunction20trySyncClippingStartEPN2al14SubActorKeeperE 0x0018bbc4
	{
		* (i._ZN18alSubActorFunction20trySyncClippingStartEPN2al14SubActorKeeperE)
	}
}
_ZN19GhostPlayerRecorder6createEi 0x0018d3a0
{
	_ZN19GhostPlayerRecorder6createEi 0x0018d3a0
	{
		* (i._ZN19GhostPlayerRecorder6createEi)
	}
}
_ZN19GhostPlayerRecorderC1Ev 0x0018d828
{
	_ZN19GhostPlayerRecorderC1Ev 0x0018d828
	{
		* (i._ZN19GhostPlayerRecorderC1Ev)
	}
}
_ZN21PlayerActionCondition5setupEv 0x0019d7b0
{
	_ZN21PlayerActionCondition5setupEv 0x0019d7b0
	{
		* (i._ZN21PlayerActionCondition5setupEv)
	}
}
_ZN2al25CameraDashAngleTunerParam4initEPKNS_9ByamlIterE 0x001b64fc
{
	_ZN2al25CameraDashAngleTunerParam4initEPKNS_9ByamlIterE 0x001b64fc
	{
		* (i._ZN2al25CameraDashAngleTunerParam4initEPKNS_9ByamlIterE)
	}
}
_ZN2al25CameraDashAngleTunerParamC1Ev 0x001b657c
{
	_ZN2al25CameraDashAngleTunerParamC1Ev 0x001b657c
	{
		* (i._ZN2al25CameraDashAngleTunerParamC1Ev)
	}
}
_ZN26PlayerActionMultiCondition5setupEv 0x001b8bd8
{
	_ZN26PlayerActionMultiCondition5setupEv 0x001b8bd8
	{
		* (i._ZN26PlayerActionMultiCondition5setupEv)
	}
}
_ZN28PlayerActionConditionAnimEnd5checkEv 0x001b9dcc
{
	_ZN28PlayerActionConditionAnimEnd5checkEv 0x001b9dcc
	{
		* (i._ZN28PlayerActionConditionAnimEnd5checkEv)
	}
}
_ZN2al10BreakModel4initERKNS_13ActorInitInfoE 0x001bb7ac
{
	_ZN2al10BreakModel4initERKNS_13ActorInitInfoE 0x001bb7ac
	{
		* (i._ZN2al10BreakModel4initERKNS_13ActorInitInfoE)
	}
}
_ZN2al10BreakModel6appearEv 0x001bb810
{
	_ZN2al10BreakModel6appearEv 0x001bb810
	{
		* (i._ZN2al10BreakModel6appearEv)
	}
}
_ZN2al11LayoutActor7controlEv 0x001be024
{
	_ZN2al11LayoutActor7controlEv 0x001be024
	{
		* (i._ZN2al11LayoutActor7controlEv)
	}
}
_ZN15alNerveFunction14setNerveActionEPN2al9IUseNerveEPKc 0x001bee30
{
	_ZN15alNerveFunction14setNerveActionEPN2al9IUseNerveEPKc 0x001bee30
	{
		* (i._ZN15alNerveFunction14setNerveActionEPN2al9IUseNerveEPKc)
	}
}
_ZN2al11NerveKeeper8setNerveEPKNS_5NerveE 0x001bee64
{
	_ZN2al11NerveKeeper8setNerveEPKNS_5NerveE 0x001bee64
	{
		* (i._ZN2al11NerveKeeper8setNerveEPKNS_5NerveE)
	}
}
_ZN2al12LiveActorKitC1Ei 0x001c0cd4
{
	_ZN2al12LiveActorKitC1Ei 0x001c0cd4
	{
		* (i._ZN2al12LiveActorKitC1Ei)
	}
}
_ZN2al12MemorySystem18createSequenceHeapEv 0x001c0e78
{
	_ZN2al12MemorySystem18createSequenceHeapEv 0x001c0e78
	{
		* (i._ZN2al12MemorySystem18createSequenceHeapEv)
	}
}
_ZN2al12MemorySystem19freeAllSequenceHeapEv 0x001c0ecc
{
	_ZN2al12MemorySystem19freeAllSequenceHeapEv 0x001c0ecc
	{
		* (i._ZN2al12MemorySystem19freeAllSequenceHeapEv)
	}
}
_ZN2al12calcHashCodeEPKc 0x001c2d40
{
	_ZN2al12calcHashCodeEPKc 0x001c2d40
	{
		* (i._ZN2al12calcHashCodeEPKc)
	}
}
_ZN2al12isSensorRideEPKNS_9HitSensorE 0x001c2ef8
{
	_ZN2al12isSensorRideEPKNS_9HitSensorE 0x001c2ef8
	{
		* (i._ZN2al12isSensorRideEPKNS_9HitSensorE)
	}
}
_ZN2al13AreaShapeCubeC2Eb 0x001c50ec
{
	_ZN2al13AreaShapeCubeC2Eb 0x001c50ec
	{
		* (i._ZN2al13AreaShapeCubeC2Eb)
	}
}
_ZN2al13KeyPoseKeeperC1Ev 0x001c5d10
{
	_ZN2al13KeyPoseKeeperC1Ev 0x001c5d10
	{
		* (i._ZN2al13KeyPoseKeeperC1Ev)
	}
}
_ZN2al13LiveActorFlagC1Ev 0x001c70fc
{
	_ZN2al13LiveActorFlagC1Ev 0x001c70fc
	{
		* (i._ZN2al13LiveActorFlagC1Ev)
	}
}
_ZN2al14LiveActorGroup13registerActorEPNS_9LiveActorE 0x001cab14
{
	_ZN2al14LiveActorGroup13registerActorEPNS_9LiveActorE 0x001cab14
	{
		* (i._ZN2al14LiveActorGroup13registerActorEPNS_9LiveActorE)
	}
}
_ZN2al14LiveActorGroup16makeActorDeadAllEv 0x001cab2c
{
	_ZN2al14LiveActorGroup16makeActorDeadAllEv 0x001cab2c
	{
		* (i._ZN2al14LiveActorGroup16makeActorDeadAllEv)
	}
}
_ZN2al14NerveStateCtrl10startStateEPKNS_5NerveE 0x001cabd8
{
	_ZN2al14NerveStateCtrl10startStateEPKNS_5NerveE 0x001cabd8
	{
		* (i._ZN2al14NerveStateCtrl10startStateEPKNS_5NerveE)
	}
}
_ZN2al14NerveStateCtrl18tryEndCurrentStateEv 0x001cac3c
{
	_ZN2al14NerveStateCtrl18tryEndCurrentStateEv 0x001cac3c
	{
		* (i._ZN2al14NerveStateCtrl18tryEndCurrentStateEv)
	}
}
_ZN2al16updateNerveStateEPNS_9IUseNerveE 0x001cac78
{
	_ZN2al16updateNerveStateEPNS_9IUseNerveE 0x001cac78
	{
		* (i._ZN2al16updateNerveStateEPNS_9IUseNerveE)
	}
}
_ZN2al14NerveStateCtrl18updateCurrentStateEv 0x001cac94
{
	_ZN2al14NerveStateCtrl18updateCurrentStateEv 0x001cac94
	{
		* (i._ZN2al14NerveStateCtrl18updateCurrentStateEv)
	}
}
_ZN2al14NerveStateCtrlC1Ei 0x001cad2c
{
	_ZN2al14NerveStateCtrlC1Ei 0x001cad2c
	{
		* (i._ZN2al14NerveStateCtrlC1Ei)
	}
}
_ZN2al11setSceneObjEPNS_9ISceneObjEi 0x001cb48c
{
	_ZN2al11setSceneObjEPNS_9ISceneObjEi 0x001cb48c
	{
		* (i._ZN2al11setSceneObjEPNS_9ISceneObjEi)
	}
}
_ZN2al14SceneObjHolder6setObjEPNS_9ISceneObjEi 0x001cb4ac
{
	_ZN2al14SceneObjHolder6setObjEPNS_9ISceneObjEi 0x001cb4ac
	{
		* (i._ZN2al14SceneObjHolder6setObjEPNS_9ISceneObjEi)
	}
}
_ZN2al14SceneObjHolder26initAfterPlacementSceneObjERKNS_13ActorInitInfoE 0x001cb4b8
{
	_ZN2al14SceneObjHolder26initAfterPlacementSceneObjERKNS_13ActorInitInfoE 0x001cb4b8
	{
		* (i._ZN2al14SceneObjHolder26initAfterPlacementSceneObjERKNS_13ActorInitInfoE)
	}
}
_ZN2al14SceneObjHolder6createEi 0x001cb508
{
	_ZN2al14SceneObjHolder6createEi 0x001cb508
	{
		* (i._ZN2al14SceneObjHolder6createEi)
	}
}
_ZN2al14isSensorSimpleEPKNS_9HitSensorE 0x001cbee4
{
	_ZN2al14isSensorSimpleEPKNS_9HitSensorE 0x001cbee4
	{
		* (i._ZN2al14isSensorSimpleEPKNS_9HitSensorE)
	}
}
_ZN2al14tryGetRailIterEPNS_9ByamlIterERKS0_ 0x001cbf3c
{
	_ZN2al14tryGetRailIterEPNS_9ByamlIterERKS0_ 0x001cbf3c
	{
		* (i._ZN2al14tryGetRailIterEPNS_9ByamlIterERKS0_)
	}
}
_ZN2al20registerExecutorUserEPNS_12IUseExecutorEPKc 0x001cc79c
{
	_ZN2al20registerExecutorUserEPNS_12IUseExecutorEPKc 0x001cc79c
	{
		* (i._ZN2al20registerExecutorUserEPNS_12IUseExecutorEPKc)
	}
}
_ZN2al15ExecuteDirector12registerUserEPNS_12IUseExecutorEPKc 0x001cc7c0
{
	_ZN2al15ExecuteDirector12registerUserEPNS_12IUseExecutorEPKc 0x001cc7c0
	{
		* (i._ZN2al15ExecuteDirector12registerUserEPNS_12IUseExecutorEPKc)
	}
}
_ZN2al23registerExecutorFunctorERKNS_11FunctorBaseEPKc 0x001cc93c
{
	_ZN2al23registerExecutorFunctorERKNS_11FunctorBaseEPKc 0x001cc93c
	{
		* (i._ZN2al23registerExecutorFunctorERKNS_11FunctorBaseEPKc)
	}
}
_ZN2al15ExecuteDirector15registerFunctorERKNS_11FunctorBaseEPKc 0x001cc960
{
	_ZN2al15ExecuteDirector15registerFunctorERKNS_11FunctorBaseEPKc 0x001cc960
	{
		* (i._ZN2al15ExecuteDirector15registerFunctorERKNS_11FunctorBaseEPKc)
	}
}
_ZN2al27registerExecutorFunctorDrawERKNS_11FunctorBaseEPKc 0x001cc9b0
{
	_ZN2al27registerExecutorFunctorDrawERKNS_11FunctorBaseEPKc 0x001cc9b0
	{
		* (i._ZN2al27registerExecutorFunctorDrawERKNS_11FunctorBaseEPKc)
	}
}
_ZN2al15ExecuteDirector19registerFunctorDrawERKNS_11FunctorBaseEPKc 0x001cc9d4
{
	_ZN2al15ExecuteDirector19registerFunctorDrawERKNS_11FunctorBaseEPKc 0x001cc9d4
	{
		* (i._ZN2al15ExecuteDirector19registerFunctorDrawERKNS_11FunctorBaseEPKc)
	}
}
_ZN2al15ExecuteDirector23createExecutorListTableEv 0x001cca1c
{
	_ZN2al15ExecuteDirector23createExecutorListTableEv 0x001cca1c
	{
		* (i._ZN2al15ExecuteDirector23createExecutorListTableEv)
	}
}
_ZN2al9LayoutKit21createExecuteDirectorEi 0x001cca5c
{
	_ZN2al9LayoutKit21createExecuteDirectorEi 0x001cca5c
	{
		* (i._ZN2al9LayoutKit21createExecuteDirectorEi)
	}
}
_ZN2al15ExecuteDirector4initEv 0x001cca94
{
	_ZN2al15ExecuteDirector4initEv 0x001cca94
	{
		* (i._ZN2al15ExecuteDirector4initEv)
	}
}
_ZN2al15ExecuteDirectorC1Ei 0x001ccd40
{
	_ZN2al15ExecuteDirectorC1Ei 0x001ccd40
	{
		* (i._ZN2al15ExecuteDirectorC1Ei)
	}
}
_ZN2al15HitSensorKeeper10invalidateEv 0x001ccdb0
{
	_ZN2al15HitSensorKeeper10invalidateEv 0x001ccdb0
	{
		* (i._ZN2al15HitSensorKeeper10invalidateEv)
	}
}
_ZN2al15HitSensorKeeper12attackSensorEv 0x001ccde8
{
	_ZN2al15HitSensorKeeper12attackSensorEv 0x001ccde8
	{
		* (i._ZN2al15HitSensorKeeper12attackSensorEv)
	}
}
_ZN2al15HitSensorKeeper8validateEv 0x001cceac
{
	_ZN2al15HitSensorKeeper8validateEv 0x001cceac
	{
		* (i._ZN2al15HitSensorKeeper8validateEv)
	}
}
_ZN2al15NerveActionCtrlC1EPN15alNerveFunction20NerveActionCollectorE 0x001cd394
{
	_ZN2al15NerveActionCtrlC1EPN15alNerveFunction20NerveActionCollectorE 0x001cd394
	{
		* (i._ZN2al15NerveActionCtrlC1EPN15alNerveFunction20NerveActionCollectorE)
	}
}
_ZN2al15getSequenceHeapEv 0x001cd698
{
	_ZN2al15getSequenceHeapEv 0x001cd698
	{
		* (i._ZN2al15getSequenceHeapEv)
	}
}
_ZN2al16KCollisionServer20initKCollisionServerEPvPKv 0x001d0970
{
	_ZN2al16KCollisionServer20initKCollisionServerEPvPKv 0x001d0970
	{
		* (i._ZN2al16KCollisionServer20initKCollisionServerEPvPKv)
	}
}
_ZN2al16KCollisionServerC1Ev 0x001d09d0
{
	_ZN2al16KCollisionServerC1Ev 0x001d09d0
	{
		* (i._ZN2al16KCollisionServerC1Ev)
	}
}
_ZN2al17HitSensorDirectorC1Ev 0x001d1f90
{
	_ZN2al17HitSensorDirectorC1Ev 0x001d1f90
	{
		* (i._ZN2al17HitSensorDirectorC1Ev)
	}
}
_ZN2al9sendMsg55EPNS_9HitSensorES1_ 0x001d2d10
{
	_ZN2al9sendMsg55EPNS_9HitSensorES1_ 0x001d2d10
	{
		* (i._ZN2al9sendMsg55EPNS_9HitSensorES1_)
	}
}
_ZN2al17isPadTriggerTouchEi 0x001d7a88
{
	_ZN2al17isPadTriggerTouchEi 0x001d7a88
	{
		* (i._ZN2al17isPadTriggerTouchEi)
	}
}
_ZN2al18isPadTriggerSelectEi 0x001db620
{
	_ZN2al18isPadTriggerSelectEi 0x001db620
	{
		* (i._ZN2al18isPadTriggerSelectEi)
	}
}
_ZN2al19ActorPoseKeeperBase10getQuatPtrEv 0x001db6d4
{
	_ZN2al19ActorPoseKeeperBase10getQuatPtrEv 0x001db6d4
	{
		* (i._ZN2al19ActorPoseKeeperBase10getQuatPtrEv)
	}
}
_ZN2al19ActorPoseKeeperBase11getFrontPtrEv 0x001db6dc
{
	_ZN2al19ActorPoseKeeperBase11getFrontPtrEv 0x001db6dc
	{
		* (i._ZN2al19ActorPoseKeeperBase11getFrontPtrEv)
	}
}
_ZN2al19ActorPoseKeeperBase12getRotatePtrEv 0x001db6e4
{
	_ZN2al19ActorPoseKeeperBase12getRotatePtrEv 0x001db6e4
	{
		* (i._ZN2al19ActorPoseKeeperBase12getRotatePtrEv)
	}
}
_ZN2al19ActorPoseKeeperTFSV11getFrontPtrEv 0x001db734
{
	_ZN2al19ActorPoseKeeperTFSV11getFrontPtrEv 0x001db734
	{
		* (i._ZN2al19ActorPoseKeeperTFSV11getFrontPtrEv)
	}
}
_ZN2al19ActorPoseKeeperTFSV11getScalePtrEv 0x001db73c
{
	_ZN2al19ActorPoseKeeperTFSV11getScalePtrEv 0x001db73c
	{
		* (i._ZN2al19ActorPoseKeeperTFSV11getScalePtrEv)
	}
}
_ZN2al19ActorPoseKeeperTFSV14getVelocityPtrEv 0x001db778
{
	_ZN2al19ActorPoseKeeperTFSV14getVelocityPtrEv 0x001db778
	{
		* (i._ZN2al19ActorPoseKeeperTFSV14getVelocityPtrEv)
	}
}
_ZN2al19ActorPoseKeeperTFSVC1Ev 0x001db7c8
{
	_ZN2al19ActorPoseKeeperTFSVC1Ev 0x001db7c8
	{
		* (i._ZN2al19ActorPoseKeeperTFSVC1Ev)
	}
}
_ZN2al19ActorPoseKeeperTQSV10getQuatPtrEv 0x001db820
{
	_ZN2al19ActorPoseKeeperTQSV10getQuatPtrEv 0x001db820
	{
		* (i._ZN2al19ActorPoseKeeperTQSV10getQuatPtrEv)
	}
}
_ZN2al19ActorPoseKeeperTQSV11getScalePtrEv 0x001db828
{
	_ZN2al19ActorPoseKeeperTQSV11getScalePtrEv 0x001db828
	{
		* (i._ZN2al19ActorPoseKeeperTQSV11getScalePtrEv)
	}
}
_ZN2al19ActorPoseKeeperTQSV14getVelocityPtrEv 0x001db860
{
	_ZN2al19ActorPoseKeeperTQSV14getVelocityPtrEv 0x001db860
	{
		* (i._ZN2al19ActorPoseKeeperTQSV14getVelocityPtrEv)
	}
}
_ZN2al19ActorPoseKeeperTQSVC1Ev 0x001db8b4
{
	_ZN2al19ActorPoseKeeperTQSVC1Ev 0x001db8b4
	{
		* (i._ZN2al19ActorPoseKeeperTQSVC1Ev)
	}
}
_ZN2al19ActorPoseKeeperTRSV11getScalePtrEv 0x001db910
{
	_ZN2al19ActorPoseKeeperTRSV11getScalePtrEv 0x001db910
	{
		* (i._ZN2al19ActorPoseKeeperTRSV11getScalePtrEv)
	}
}
_ZN2al19ActorPoseKeeperTRSV12getRotatePtrEv 0x001db918
{
	_ZN2al19ActorPoseKeeperTRSV12getRotatePtrEv 0x001db918
	{
		* (i._ZN2al19ActorPoseKeeperTRSV12getRotatePtrEv)
	}
}
_ZN2al19ActorPoseKeeperTRSV14getVelocityPtrEv 0x001dba20
{
	_ZN2al19ActorPoseKeeperTRSV14getVelocityPtrEv 0x001dba20
	{
		* (i._ZN2al19ActorPoseKeeperTRSV14getVelocityPtrEv)
	}
}
_ZN2al19StageResourceKeeperC1Ev 0x001dcd20
{
	_ZN2al19StageResourceKeeperC1Ev 0x001dcd20
	{
		* (i._ZN2al19StageResourceKeeperC1Ev)
	}
}
_ZN2al19StageSwitchAccesser21initWithPlacementInfoENS_15StageSwitchTypeERKNS_9ByamlIterES1_ 0x001dcd2c
{
	_ZN2al19StageSwitchAccesser21initWithPlacementInfoENS_15StageSwitchTypeERKNS_9ByamlIterES1_ 0x001dcd2c
	{
		* (i._ZN2al19StageSwitchAccesser21initWithPlacementInfoENS_15StageSwitchTypeERKNS_9ByamlIterES1_)
	}
}
_ZN2al19StageSwitchAccesserC1Ev 0x001dcd78
{
	_ZN2al19StageSwitchAccesserC1Ev 0x001dcd78
	{
		* (i._ZN2al19StageSwitchAccesserC1Ev)
	}
}
_ZN2al19tryCreateRailKeeperERKNS_9ByamlIterE 0x001dd494
{
	_ZN2al19tryCreateRailKeeperERKNS_9ByamlIterE 0x001dd494
	{
		* (i._ZN2al19tryCreateRailKeeperERKNS_9ByamlIterE)
	}
}
_ZN2al20ActorPoseKeeperTFGSVC1Ev 0x001dd8c0
{
	_ZN2al20ActorPoseKeeperTFGSVC1Ev 0x001dd8c0
	{
		* (i._ZN2al20ActorPoseKeeperTFGSVC1Ev)
	}
}
_ZN2al7isMsg49Ej 0x001e13a0
{
	_ZN2al7isMsg49Ej 0x001e13a0
	{
		* (i._ZN2al7isMsg49Ej)
	}
}
_ZN2al7isMsg52Ej 0x001e13b0
{
	_ZN2al7isMsg52Ej 0x001e13b0
	{
		* (i._ZN2al7isMsg52Ej)
	}
}
_ZN2al7isMsg51Ej 0x001e13c0
{
	_ZN2al7isMsg51Ej 0x001e13c0
	{
		* (i._ZN2al7isMsg51Ej)
	}
}
_ZN2al22ExecuteTableHolderDrawC1Ev 0x001e2130
{
	_ZN2al22ExecuteTableHolderDrawC1Ev 0x001e2130
	{
		* (i._ZN2al22ExecuteTableHolderDrawC1Ev)
	}
}
_ZN2al22sendMsgKickStoneAttackEPNS_9HitSensorES1_ 0x001e28f4
{
	_ZN2al22sendMsgKickStoneAttackEPNS_9HitSensorES1_ 0x001e28f4
	{
		* (i._ZN2al22sendMsgKickStoneAttackEPNS_9HitSensorES1_)
	}
}
_ZN2al14NerveStateBase4initEv 0x001e2da0
{
	_ZN2al14NerveStateBase4initEv 0x001e2da0
	{
		* (i._ZN2al14NerveStateBase4initEv)
	}
}
_ZN2al14NerveStateBase4killEv 0x001e2da4
{
	_ZN2al14NerveStateBase4killEv 0x001e2da4
	{
		* (i._ZN2al14NerveStateBase4killEv)
	}
}
_ZN2al14NerveStateBase6appearEv 0x001e2db0
{
	_ZN2al14NerveStateBase6appearEv 0x001e2db0
	{
		* (i._ZN2al14NerveStateBase6appearEv)
	}
}
_ZN2al14NerveStateBase6updateEv 0x001e2dbc
{
	_ZN2al14NerveStateBase6updateEv 0x001e2dbc
	{
		* (i._ZN2al14NerveStateBase6updateEv)
	}
}
_ZN2al14NerveStateBase7controlEv 0x001e2df0
{
	_ZN2al14NerveStateBase7controlEv 0x001e2df0
	{
		* (i._ZN2al14NerveStateBase7controlEv)
	}
}
_ZN2al9sendMsg49EPNS_9HitSensorES1_ 0x001e3490
{
	_ZN2al9sendMsg49EPNS_9HitSensorES1_ 0x001e3490
	{
		* (i._ZN2al9sendMsg49EPNS_9HitSensorES1_)
	}
}
_ZN2al23sendMsgKickKouraReflectEPNS_9HitSensorES1_ 0x001e34ac
{
	_ZN2al23sendMsgKickKouraReflectEPNS_9HitSensorES1_ 0x001e34ac
	{
		* (i._ZN2al23sendMsgKickKouraReflectEPNS_9HitSensorES1_)
	}
}
_ZN2al23sendMsgPlayerTailAttackEPNS_9HitSensorES1_ 0x001e34c8
{
	_ZN2al23sendMsgPlayerTailAttackEPNS_9HitSensorES1_ 0x001e34c8
	{
		* (i._ZN2al23sendMsgPlayerTailAttackEPNS_9HitSensorES1_)
	}
}
_ZN2al9sendMsg52EPNS_9HitSensorES1_ 0x001e34e4
{
	_ZN2al9sendMsg52EPNS_9HitSensorES1_ 0x001e34e4
	{
		* (i._ZN2al9sendMsg52EPNS_9HitSensorES1_)
	}
}
_ZN2al9sendMsg51EPNS_9HitSensorES1_ 0x001e3500
{
	_ZN2al9sendMsg51EPNS_9HitSensorES1_ 0x001e3500
	{
		* (i._ZN2al9sendMsg51EPNS_9HitSensorES1_)
	}
}
_ZN2al24ExecuteTableHolderUpdateC1Ev 0x001e3b64
{
	_ZN2al24ExecuteTableHolderUpdateC1Ev 0x001e3b64
	{
		* (i._ZN2al24ExecuteTableHolderUpdateC1Ev)
	}
}
_ZN2al7isMsg14Ej 0x001e4a60
{
	_ZN2al7isMsg14Ej 0x001e4a60
	{
		* (i._ZN2al7isMsg14Ej)
	}
}
_ZN2al26isCreatedSceneResourceHeapEv 0x001e576c
{
	_ZN2al26isCreatedSceneResourceHeapEv 0x001e576c
	{
		* (i._ZN2al26isCreatedSceneResourceHeapEv)
	}
}
_ZN2al28sendMsgPlayerBoomerangAttackEPNS_9HitSensorES1_ 0x001e6690
{
	_ZN2al28sendMsgPlayerBoomerangAttackEPNS_9HitSensorES1_ 0x001e6690
	{
		* (i._ZN2al28sendMsgPlayerBoomerangAttackEPNS_9HitSensorES1_)
	}
}
_ZN2al9sendMsg34EPNS_9HitSensorES1_ 0x001e723c
{
	_ZN2al9sendMsg34EPNS_9HitSensorES1_ 0x001e723c
	{
		* (i._ZN2al9sendMsg34EPNS_9HitSensorES1_)
	}
}
_ZN2al29sendMsgPlayerBoomerangReflectEPNS_9HitSensorES1_ 0x001e7258
{
	_ZN2al29sendMsgPlayerBoomerangReflectEPNS_9HitSensorES1_ 0x001e7258
	{
		* (i._ZN2al29sendMsgPlayerBoomerangReflectEPNS_9HitSensorES1_)
	}
}
_ZN2al4RailC1Ev 0x001e9834
{
	_ZN2al4RailC1Ev 0x001e9834
	{
		* (i._ZN2al4RailC1Ev)
	}
}
_ZN2al7AreaObj21initStageSwitchKeeperEv 0x001ea4a8
{
	_ZN2al7AreaObj21initStageSwitchKeeperEv 0x001ea4a8
	{
		* (i._ZN2al7AreaObj21initStageSwitchKeeperEv)
	}
}
_ZN2al7KeyPose4initERKNS_9ByamlIterE 0x001ea7b0
{
	_ZN2al7KeyPose4initERKNS_9ByamlIterE 0x001ea7b0
	{
		* (i._ZN2al7KeyPose4initERKNS_9ByamlIterE)
	}
}
_ZN2al7KeyPoseC1Ev 0x001ea7ec
{
	_ZN2al7KeyPoseC1Ev 0x001ea7ec
	{
		* (i._ZN2al7KeyPoseC1Ev)
	}
}
_ZN8JMapInfo6attachEPKv 0x001eb78c
{
	_ZN8JMapInfo6attachEPKv 0x001eb78c
	{
		* (i._ZN8JMapInfo6attachEPKv)
	}
}
_ZN8JMapInfoC1Ev 0x001eb7a0
{
	_ZN8JMapInfoC1Ev 0x001eb7a0
	{
		* (i._ZN8JMapInfoC1Ev)
	}
}
_ZN2al9AreaShape8setScaleERKN4sead7Vector3IfEE 0x001eb930
{
	_ZN2al9AreaShape8setScaleERKN4sead7Vector3IfEE 0x001eb930
	{
		* (i._ZN2al9AreaShape8setScaleERKN4sead7Vector3IfEE)
	}
}
_ZN2al9HitSensor10invalidateEv 0x001eb960
{
	_ZN2al9HitSensor10invalidateEv 0x001eb960
	{
		* (i._ZN2al9HitSensor10invalidateEv)
	}
}
_ZN2al9HitSensor16validateBySystemEv 0x001eb9fc
{
	_ZN2al9HitSensor16validateBySystemEv 0x001eb9fc
	{
		* (i._ZN2al9HitSensor16validateBySystemEv)
	}
}
_ZN2al9HitSensor18invalidateBySystemEv 0x001eba48
{
	_ZN2al9HitSensor18invalidateBySystemEv 0x001eba48
	{
		* (i._ZN2al9HitSensor18invalidateBySystemEv)
	}
}
_ZN2al9HitSensor8validateEv 0x001ebb24
{
	_ZN2al9HitSensor8validateEv 0x001ebb24
	{
		* (i._ZN2al9HitSensor8validateEv)
	}
}
_ZN2al9ISceneObj12initSceneObjEv 0x001ebc50
{
	_ZN2al9ISceneObj12initSceneObjEv 0x001ebc50
	{
		* (i._ZN2al9ISceneObj12initSceneObjEv)
	}
}
_ZN2al9LiveActor10receiveMsgEjPNS_9HitSensorES2_ 0x001ebc58
{
	_ZN2al9LiveActor10receiveMsgEjPNS_9HitSensorES2_ 0x001ebc58
	{
		* (i._ZN2al9LiveActor10receiveMsgEjPNS_9HitSensorES2_)
	}
}
_ZN2al9LiveActor12attackSensorEPNS_9HitSensorES2_ 0x001ebc60
{
	_ZN2al9LiveActor12attackSensorEPNS_9HitSensorES2_ 0x001ebc60
	{
		* (i._ZN2al9LiveActor12attackSensorEPNS_9HitSensorES2_)
	}
}
_ZN2al9initNerveEPNS_9LiveActorEPKNS_5NerveEi 0x001ebd94
{
	_ZN2al9initNerveEPNS_9LiveActorEPKNS_5NerveEi 0x001ebd94
	{
		* (i._ZN2al9initNerveEPNS_9LiveActorEPKNS_5NerveEi)
	}
}
_ZN2al9LiveActor15initNerveKeeperEPNS_11NerveKeeperE 0x001ebdd4
{
	_ZN2al9LiveActor15initNerveKeeperEPNS_11NerveKeeperE 0x001ebdd4
	{
		* (i._ZN2al9LiveActor15initNerveKeeperEPNS_11NerveKeeperE)
	}
}
_ZN2al9LiveActor18initAfterPlacementEv 0x001ebe64
{
	_ZN2al9LiveActor18initAfterPlacementEv 0x001ebe64
	{
		* (i._ZN2al9LiveActor18initAfterPlacementEv)
	}
}
_ZN2al9LiveActor4initERKNS_13ActorInitInfoE 0x001ebf28
{
	_ZN2al9LiveActor4initERKNS_13ActorInitInfoE 0x001ebf28
	{
		* (i._ZN2al9LiveActor4initERKNS_13ActorInitInfoE)
	}
}
_ZN2al9LiveActor7controlEv 0x001ebf2c
{
	_ZN2al9LiveActor7controlEv 0x001ebf2c
	{
		* (i._ZN2al9LiveActor7controlEv)
	}
}
_ZN2al9RailRider15moveToRailStartEv 0x001ec0f4
{
	_ZN2al9RailRider15moveToRailStartEv 0x001ec0f4
	{
		* (i._ZN2al9RailRider15moveToRailStartEv)
	}
}
_ZN2al11NerveActionC2Ev 0x00211bd8
{
	_ZN2al11NerveActionC2Ev 0x00211bd8
	{
		* (i._ZN2al11NerveActionC2Ev)
	}
}
_ZN15alNerveFunction20NerveActionCollectorC1Ev 0x00211c28
{
	_ZN15alNerveFunction20NerveActionCollectorC1Ev 0x00211c28
	{
		* (i._ZN15alNerveFunction20NerveActionCollectorC1Ev)
	}
}
_ZN2al21sendMsgKickKouraBreakEPNS_9HitSensorES1_ 0x0021777c
{
	_ZN2al21sendMsgKickKouraBreakEPNS_9HitSensorES1_ 0x0021777c
	{
		* (i._ZN2al21sendMsgKickKouraBreakEPNS_9HitSensorES1_)
	}
}
_ZN2al19sendMsgGororiAttackEPNS_9HitSensorES1_ 0x00218a48
{
	_ZN2al19sendMsgGororiAttackEPNS_9HitSensorES1_ 0x00218a48
	{
		* (i._ZN2al19sendMsgGororiAttackEPNS_9HitSensorES1_)
	}
}
_ZN2al22sendMsgGororiBigAttackEPNS_9HitSensorES1_ 0x00218a64
{
	_ZN2al22sendMsgGororiBigAttackEPNS_9HitSensorES1_ 0x00218a64
	{
		* (i._ZN2al22sendMsgGororiBigAttackEPNS_9HitSensorES1_)
	}
}
_ZN2al13isPadTriggerYEi 0x00225c3c
{
	_ZN2al13isPadTriggerYEi 0x00225c3c
	{
		* (i._ZN2al13isPadTriggerYEi)
	}
}
_ZN2al13isPadTriggerXEi 0x00225c44
{
	_ZN2al13isPadTriggerXEi 0x00225c44
	{
		* (i._ZN2al13isPadTriggerXEi)
	}
}
_ZN2al9RailRider17moveToNearestRailERKN4sead7Vector3IfEE 0x00242a44
{
	_ZN2al9RailRider17moveToNearestRailERKN4sead7Vector3IfEE 0x00242a44
	{
		* (i._ZN2al9RailRider17moveToNearestRailERKN4sead7Vector3IfEE)
	}
}
_ZN2al18initActorPoseTFGSVEPNS_9LiveActorE 0x00244cc4
{
	_ZN2al18initActorPoseTFGSVEPNS_9LiveActorE 0x00244cc4
	{
		* (i._ZN2al18initActorPoseTFGSVEPNS_9LiveActorE)
	}
}
_ZN2al9LiveActor14initPoseKeeperEPNS_19ActorPoseKeeperBaseE 0x00244cec
{
	_ZN2al9LiveActor14initPoseKeeperEPNS_19ActorPoseKeeperBaseE 0x00244cec
	{
		* (i._ZN2al9LiveActor14initPoseKeeperEPNS_19ActorPoseKeeperBaseE)
	}
}
_ZNK2al13KeyPoseKeeper17getCurrentKeyPoseEv 0x00249618
{
	_ZNK2al13KeyPoseKeeper17getCurrentKeyPoseEv 0x00249618
	{
		* (i._ZNK2al13KeyPoseKeeper17getCurrentKeyPoseEv)
	}
}
_ZN2al15HitSensorKeeper18invalidateBySystemEv 0x0024ae08
{
	_ZN2al15HitSensorKeeper18invalidateBySystemEv 0x0024ae08
	{
		* (i._ZN2al15HitSensorKeeper18invalidateBySystemEv)
	}
}
_ZNK2al13KeyPoseKeeper14getNextKeyPoseEv 0x0024b0e8
{
	_ZNK2al13KeyPoseKeeper14getNextKeyPoseEv 0x0024b0e8
	{
		* (i._ZNK2al13KeyPoseKeeper14getNextKeyPoseEv)
	}
}
_ZN2al15HitSensorKeeper16validateBySystemEv 0x0024b900
{
	_ZN2al15HitSensorKeeper16validateBySystemEv 0x0024b900
	{
		* (i._ZN2al15HitSensorKeeper16validateBySystemEv)
	}
}
_ZN21alActorSystemFunction21addToExecutorMovementEPN2al9LiveActorE 0x0024b938
{
	_ZN21alActorSystemFunction21addToExecutorMovementEPN2al9LiveActorE 0x0024b938
	{
		* (i._ZN21alActorSystemFunction21addToExecutorMovementEPN2al9LiveActorE)
	}
}
_ZNK2al9ByamlIter11isTypeArrayEv 0x0024c85c
{
	_ZNK2al9ByamlIter11isTypeArrayEv 0x0024c85c
	{
		* (i._ZNK2al9ByamlIter11isTypeArrayEv)
	}
}
_ZN2al12isPadTriggerEii 0x0024ca4c
{
	_ZN2al12isPadTriggerEii 0x0024ca4c
	{
		* (i._ZN2al12isPadTriggerEii)
	}
}
_ZN2al9AreaShapeC2Ev 0x0024e028
{
	_ZN2al9AreaShapeC2Ev 0x0024e028
	{
		* (i._ZN2al9AreaShapeC2Ev)
	}
}
_ZN2al21removeExtensionStringEPcjPKc 0x0024e424
{
	_ZN2al21removeExtensionStringEPcjPKc 0x0024e424
	{
		* (i._ZN2al21removeExtensionStringEPcjPKc)
	}
}
_ZN19alPlacementFunction17getClippingViewIdERKN2al9ByamlIterE 0x0024e638
{
	_ZN19alPlacementFunction17getClippingViewIdERKN2al9ByamlIterE 0x0024e638
	{
		* (i._ZN19alPlacementFunction17getClippingViewIdERKN2al9ByamlIterE)
	}
}
_ZNK2al19StageSwitchAccesser12FUN_0024e734Ev 0x0024e734
{
	_ZNK2al19StageSwitchAccesser12FUN_0024e734Ev 0x0024e734
	{
		* (i._ZNK2al19StageSwitchAccesser12FUN_0024e734Ev)
	}
}
_ZN2al19ActorPoseKeeperTRSVC1Ev 0x0024ed2c
{
	_ZN2al19ActorPoseKeeperTRSVC1Ev 0x0024ed2c
	{
		* (i._ZN2al19ActorPoseKeeperTRSVC1Ev)
	}
}
_ZN2al12getHitSensorEPKNS_9LiveActorEPKc 0x0024edec
{
	_ZN2al12getHitSensorEPKNS_9LiveActorEPKc 0x0024edec
	{
		* (i._ZN2al12getHitSensorEPKNS_9LiveActorEPKc)
	}
}
_ZNK2al15HitSensorKeeper9getSensorEPKc 0x0024edf4
{
	_ZNK2al15HitSensorKeeper9getSensorEPKc 0x0024edf4
	{
		* (i._ZNK2al15HitSensorKeeper9getSensorEPKc)
	}
}
_ZNK2al9ByamlIter15isTypeContainerEv 0x0024fe70
{
	_ZNK2al9ByamlIter15isTypeContainerEv 0x0024fe70
	{
		* (i._ZNK2al9ByamlIter15isTypeContainerEv)
	}
}
strrchr 0x0024fec8
{
	strrchr 0x0024fec8
	{
		* (:gdef:strrchr)
	}
}
_ZN2al21createStringIfInStackEPKc 0x002504a8
{
	_ZN2al21createStringIfInStackEPKc 0x002504a8
	{
		* (i._ZN2al21createStringIfInStackEPKc)
	}
}
_ZN2al11NerveKeeperC1EPNS_9IUseNerveEPKNS_5NerveEi 0x00250610
{
	_ZN2al11NerveKeeperC1EPNS_9IUseNerveEPKNS_5NerveEi 0x00250610
	{
		* (i._ZN2al11NerveKeeperC1EPNS_9IUseNerveEPKNS_5NerveEi)
	}
}
_ZN2al11NerveKeeper6updateEv 0x0025065c
{
	_ZN2al11NerveKeeper6updateEv 0x0025065c
	{
		* (i._ZN2al11NerveKeeper6updateEv)
	}
}
_ZNK2al19StageSwitchAccesser16isTypeKillDeadOnEv 0x00250eb4
{
	_ZNK2al19StageSwitchAccesser16isTypeKillDeadOnEv 0x00250eb4
	{
		* (i._ZNK2al19StageSwitchAccesser16isTypeKillDeadOnEv)
	}
}
_ZN2al17StageSwitchKeeper22getStageSwitchAccesserEi 0x00250ecc
{
	_ZN2al17StageSwitchKeeper22getStageSwitchAccesserEi 0x00250ecc
	{
		* (i._ZN2al17StageSwitchKeeper22getStageSwitchAccesserEi)
	}
}
_ZN2al19getCourseSelectHeapEv 0x00251c70
{
	_ZN2al19getCourseSelectHeapEv 0x00251c70
	{
		* (i._ZN2al19getCourseSelectHeapEv)
	}
}
_ZN28PlayerActionConditionAnimEndC1EP18IUsePlayerAnimatorPKci 0x00251ea0
{
	_ZN28PlayerActionConditionAnimEndC1EP18IUsePlayerAnimatorPKci 0x00251ea0
	{
		* (i._ZN28PlayerActionConditionAnimEndC1EP18IUsePlayerAnimatorPKci)
	}
}
_ZN26PlayerActionMultiCondition6appendEP21PlayerActionCondition 0x00252008
{
	_ZN26PlayerActionMultiCondition6appendEP21PlayerActionCondition 0x00252008
	{
		* (i._ZN26PlayerActionMultiCondition6appendEP21PlayerActionCondition)
	}
}
_ZN26PlayerActionMultiConditionC1Ev 0x00252054
{
	_ZN26PlayerActionMultiConditionC1Ev 0x00252054
	{
		* (i._ZN26PlayerActionMultiConditionC1Ev)
	}
}
_ZN2al15tryGetStringArgEPPKcRKNS_9ByamlIterES1_ 0x00253c5c
{
	_ZN2al15tryGetStringArgEPPKcRKNS_9ByamlIterES1_ 0x00253c5c
	{
		* (i._ZN2al15tryGetStringArgEPPKcRKNS_9ByamlIterES1_)
	}
}
_ZN2al23getNextKeyPlacementInfoEPKNS_13KeyPoseKeeperE 0x00255668
{
	_ZN2al23getNextKeyPlacementInfoEPKNS_13KeyPoseKeeperE 0x00255668
	{
		* (i._ZN2al23getNextKeyPlacementInfoEPKNS_13KeyPoseKeeperE)
	}
}
_ZN2al22startHitReactionAppearEPKNS_9LiveActorE 0x00256bb0
{
	_ZN2al22startHitReactionAppearEPKNS_9LiveActorE 0x00256bb0
	{
		* (i._ZN2al22startHitReactionAppearEPKNS_9LiveActorE)
	}
}
_ZN2al20getSceneResourceHeapEv 0x00257fe4
{
	_ZN2al20getSceneResourceHeapEv 0x00257fe4
	{
		* (i._ZN2al20getSceneResourceHeapEv)
	}
}
_ZN2al24makeStageDataArchivePathEPN4sead22BufferedSafeStringBaseIcEEPKciS5_ 0x00257ff8
{
	_ZN2al24makeStageDataArchivePathEPN4sead22BufferedSafeStringBaseIcEEPKciS5_ 0x00257ff8
	{
		* (i._ZN2al24makeStageDataArchivePathEPN4sead22BufferedSafeStringBaseIcEEPKciS5_)
	}
}
_ZN2al13isPadTriggerAEi 0x002583bc
{
	_ZN2al13isPadTriggerAEi 0x002583bc
	{
		* (i._ZN2al13isPadTriggerAEi)
	}
}
_ZN16alSensorFunction19updateHitSensorsAllEPN2al9LiveActorE 0x00258734
{
	_ZN16alSensorFunction19updateHitSensorsAllEPN2al9LiveActorE 0x00258734
	{
		* (i._ZN16alSensorFunction19updateHitSensorsAllEPN2al9LiveActorE)
	}
}
_ZN2al15HitSensorKeeper6updateEv 0x0025873c
{
	_ZN2al15HitSensorKeeper6updateEv 0x0025873c
	{
		* (i._ZN2al15HitSensorKeeper6updateEv)
	}
}
_ZN2al14LiveActorGroup7killAllEv 0x00259328
{
	_ZN2al14LiveActorGroup7killAllEv 0x00259328
	{
		* (i._ZN2al14LiveActorGroup7killAllEv)
	}
}
_ZN2al3Sky8calcAnimEv 0x0025aa18
{
	_ZN2al3Sky8calcAnimEv 0x0025aa18
	{
		* (i._ZN2al3Sky8calcAnimEv)
	}
}
_ZN2al9LiveActor8calcAnimEv 0x0025aa34
{
	_ZN2al9LiveActor8calcAnimEv 0x0025aa34
	{
		* (i._ZN2al9LiveActor8calcAnimEv)
	}
}
_ZN10CourseList6Course17isCourseTypeStageENS0_10CourseTypeE 0x0025bd18
{
	_ZN10CourseList6Course17isCourseTypeStageENS0_10CourseTypeE 0x0025bd18
	{
		* (i._ZN10CourseList6Course17isCourseTypeStageENS0_10CourseTypeE)
	}
}
_ZN2al27sendMsgPlayerBoomerangBreakEPNS_9HitSensorES1_ 0x0025e534
{
	_ZN2al27sendMsgPlayerBoomerangBreakEPNS_9HitSensorES1_ 0x0025e534
	{
		* (i._ZN2al27sendMsgPlayerBoomerangBreakEPNS_9HitSensorES1_)
	}
}
_ZN2al25isPadTriggerLeftStickDownEi 0x0025ece0
{
	_ZN2al25isPadTriggerLeftStickDownEi 0x0025ece0
	{
		* (i._ZN2al25isPadTriggerLeftStickDownEi)
	}
}
_ZN2al23isPadTriggerLeftStickUpEi 0x0025ece8
{
	_ZN2al23isPadTriggerLeftStickUpEi 0x0025ece8
	{
		* (i._ZN2al23isPadTriggerLeftStickUpEi)
	}
}
_ZN2al6Camera4loadEPKNS_9ByamlIterE 0x00260a84
{
	_ZN2al6Camera4loadEPKNS_9ByamlIterE 0x00260a84
	{
		* (i._ZN2al6Camera4loadEPKNS_9ByamlIterE)
	}
}
_ZN2al21isMsgKickKouraReflectEj 0x002620b4
{
	_ZN2al21isMsgKickKouraReflectEj 0x002620b4
	{
		* (i._ZN2al21isMsgKickKouraReflectEj)
	}
}
_ZN2al16isCollidedGroundEPKNS_9LiveActorE 0x00262ba4
{
	_ZN2al16isCollidedGroundEPKNS_9LiveActorE 0x00262ba4
	{
		* (i._ZN2al16isCollidedGroundEPKNS_9LiveActorE)
	}
}
_ZN2al27sendMsgPlayerFireBallAttackEPNS_9HitSensorES1_ 0x00262de4
{
	_ZN2al27sendMsgPlayerFireBallAttackEPNS_9HitSensorES1_ 0x00262de4
	{
		* (i._ZN2al27sendMsgPlayerFireBallAttackEPNS_9HitSensorES1_)
	}
}
_ZN2al17isPadTriggerRightEi 0x00263848
{
	_ZN2al17isPadTriggerRightEi 0x00263848
	{
		* (i._ZN2al17isPadTriggerRightEi)
	}
}
_ZN2al26isPadTriggerLeftStickRightEi 0x00263850
{
	_ZN2al26isPadTriggerLeftStickRightEi 0x00263850
	{
		* (i._ZN2al26isPadTriggerLeftStickRightEi)
	}
}
_ZN2al16isPadTriggerLeftEi 0x00263858
{
	_ZN2al16isPadTriggerLeftEi 0x00263858
	{
		* (i._ZN2al16isPadTriggerLeftEi)
	}
}
_ZN2al25isPadTriggerLeftStickLeftEi 0x00263860
{
	_ZN2al25isPadTriggerLeftStickLeftEi 0x00263860
	{
		* (i._ZN2al25isPadTriggerLeftStickLeftEi)
	}
}
_ZN2al13isPadTriggerBEi 0x002638b0
{
	_ZN2al13isPadTriggerBEi 0x002638b0
	{
		* (i._ZN2al13isPadTriggerBEi)
	}
}
_ZN2al7isAliveEPKNS_9LiveActorE 0x00264150
{
	_ZN2al7isAliveEPKNS_9LiveActorE 0x00264150
	{
		* (i._ZN2al7isAliveEPKNS_9LiveActorE)
	}
}
_ZN2rp13getCourseListEv 0x002645ac
{
	_ZN2rp13getCourseListEv 0x002645ac
	{
		* (i._ZN2rp13getCourseListEv)
	}
}
_ZN2al8copyPoseEPNS_9LiveActorEPKS0_ 0x00266248
{
	_ZN2al8copyPoseEPNS_9LiveActorEPKS0_ 0x00266248
	{
		* (i._ZN2al8copyPoseEPNS_9LiveActorEPKS0_)
	}
}
_ZN2al10WipeSimpleC1EPKcS2_RKNS_14LayoutInitInfoES2_ 0x00266bac
{
	_ZN2al10WipeSimpleC1EPKcS2_RKNS_14LayoutInitInfoES2_ 0x00266bac
	{
		* (i._ZN2al10WipeSimpleC1EPKcS2_RKNS_14LayoutInitInfoES2_)
	}
}
_ZN2al17initActorPoseTRSVEPNS_9LiveActorE 0x00266f34
{
	_ZN2al17initActorPoseTRSVEPNS_9LiveActorE 0x00266f34
	{
		* (i._ZN2al17initActorPoseTRSVEPNS_9LiveActorE)
	}
}
_ZN2al12isObjectNameERKNS_9ByamlIterEPKc 0x00267050
{
	_ZN2al12isObjectNameERKNS_9ByamlIterEPKc 0x00267050
	{
		* (i._ZN2al12isObjectNameERKNS_9ByamlIterEPKc)
	}
}
_ZN2al19getLinksInfoByIndexEPNS_9ByamlIterERKNS_13ActorInitInfoEi 0x00267088
{
	_ZN2al19getLinksInfoByIndexEPNS_9ByamlIterERKNS_13ActorInitInfoEi 0x00267088
	{
		* (i._ZN2al19getLinksInfoByIndexEPNS_9ByamlIterERKNS_13ActorInitInfoEi)
	}
}
_ZN2al17getSceneObjHolderEv 0x00267234
{
	_ZN2al17getSceneObjHolderEv 0x00267234
	{
		* (i._ZN2al17getSceneObjHolderEv)
	}
}
_ZN2al25startHitReactionDisappearEPKNS_9LiveActorE 0x00267354
{
	_ZN2al25startHitReactionDisappearEPKNS_9LiveActorE 0x00267354
	{
		* (i._ZN2al25startHitReactionDisappearEPKNS_9LiveActorE)
	}
}
_ZN2al19startHitReactionHitEPKNS_9LiveActorE 0x00267394
{
	_ZN2al19startHitReactionHitEPKNS_9LiveActorE 0x00267394
	{
		* (i._ZN2al19startHitReactionHitEPKNS_9LiveActorE)
	}
}
_ZN2al14NerveStateBaseC1EPKc 0x002684e0
{
	_ZN2al14NerveStateBaseC1EPKc 0x002684e0
	{
		* (i._ZN2al14NerveStateBaseC1EPKc)
	}
}
_ZN2al22tryStartMclAnimIfExistEPNS_9LiveActorEPKc 0x00268804
{
	_ZN2al22tryStartMclAnimIfExistEPNS_9LiveActorEPKc 0x00268804
	{
		* (i._ZN2al22tryStartMclAnimIfExistEPNS_9LiveActorEPKc)
	}
}
_ZN2al15getNextKeyTransEPKNS_13KeyPoseKeeperE 0x0026935c
{
	_ZN2al15getNextKeyTransEPKNS_13KeyPoseKeeperE 0x0026935c
	{
		* (i._ZN2al15getNextKeyTransEPKNS_13KeyPoseKeeperE)
	}
}
_ZN2al7lerpVecEPN4sead7Vector3IfEERKS2_S5_f 0x00269790
{
	_ZN2al7lerpVecEPN4sead7Vector3IfEERKS2_S5_f 0x00269790
	{
		* (i._ZN2al7lerpVecEPN4sead7Vector3IfEERKS2_S5_f)
	}
}
_ZN2al13ActorInitInfo14initViewIdHostEPKNS_9ByamlIterERKS0_ 0x0026aca0
{
	_ZN2al13ActorInitInfo14initViewIdHostEPKNS_9ByamlIterERKS0_ 0x0026aca0
	{
		* (i._ZN2al13ActorInitInfo14initViewIdHostEPKNS_9ByamlIterERKS0_)
	}
}
_ZN2rp14getCoinRotateYEv 0x0026c70c
{
	_ZN2rp14getCoinRotateYEv 0x0026c70c
	{
		* (i._ZN2rp14getCoinRotateYEv)
	}
}
_ZN19alLiveActorFunction14calcAnimDirectEPN2al9LiveActorE 0x0026d0e4
{
	_ZN19alLiveActorFunction14calcAnimDirectEPN2al9LiveActorE 0x0026d0e4
	{
		* (i._ZN19alLiveActorFunction14calcAnimDirectEPN2al9LiveActorE)
	}
}
_ZN2al21startHitReactionStartEPKNS_9LiveActorE 0x0026d610
{
	_ZN2al21startHitReactionStartEPKNS_9LiveActorE 0x0026d610
	{
		* (i._ZN2al21startHitReactionStartEPKNS_9LiveActorE)
	}
}
_ZN2al16validateClippingEPNS_9LiveActorE 0x0026d668
{
	_ZN2al16validateClippingEPNS_9LiveActorE 0x0026d668
	{
		* (i._ZN2al16validateClippingEPNS_9LiveActorE)
	}
}
_ZN2al10isNearZeroEff 0x0026d698
{
	_ZN2al10isNearZeroEff 0x0026d698
	{
		* (i._ZN2al10isNearZeroEff)
	}
}
_ZN2al9getRotateEPKNS_9LiveActorE 0x0026e734
{
	_ZN2al9getRotateEPKNS_9LiveActorE 0x0026e734
	{
		* (i._ZN2al9getRotateEPKNS_9LiveActorE)
	}
}
_ZN2al12getRotatePtrEPNS_9LiveActorE 0x0026e744
{
	_ZN2al12getRotatePtrEPNS_9LiveActorE 0x0026e744
	{
		* (i._ZN2al12getRotatePtrEPNS_9LiveActorE)
	}
}
_ZN2al8setScaleEPNS_9LiveActorERKN4sead7Vector3IfEE 0x0026e778
{
	_ZN2al8setScaleEPNS_9LiveActorERKN4sead7Vector3IfEE 0x0026e778
	{
		* (i._ZN2al8setScaleEPNS_9LiveActorERKN4sead7Vector3IfEE)
	}
}
_ZN13PlayerTrigger3setENS_17ECollisionTriggerE 0x0026e7ac
{
	_ZN13PlayerTrigger3setENS_17ECollisionTriggerE 0x0026e7ac
	{
		* (i._ZN13PlayerTrigger3setENS_17ECollisionTriggerE)
	}
}
_ZN2al17sendMsgPlayerKickEPNS_9HitSensorES1_ 0x0026e964
{
	_ZN2al17sendMsgPlayerKickEPNS_9HitSensorES1_ 0x0026e964
	{
		* (i._ZN2al17sendMsgPlayerKickEPNS_9HitSensorES1_)
	}
}
_ZN2al8sendMsg9EPNS_9HitSensorES1_ 0x0026e9b8
{
	_ZN2al8sendMsg9EPNS_9HitSensorES1_ 0x0026e9b8
	{
		* (i._ZN2al8sendMsg9EPNS_9HitSensorES1_)
	}
}
_ZNK13PlayerTrigger4isOnENS_17ECollisionTriggerE 0x0026ea40
{
	_ZNK13PlayerTrigger4isOnENS_17ECollisionTriggerE 0x0026ea40
	{
		* (i._ZNK13PlayerTrigger4isOnENS_17ECollisionTriggerE)
	}
}
_ZNK13PlayerTrigger4isOnENS_14ESensorTriggerE 0x0026ea60
{
	_ZNK13PlayerTrigger4isOnENS_14ESensorTriggerE 0x0026ea60
	{
		* (i._ZNK13PlayerTrigger4isOnENS_14ESensorTriggerE)
	}
}
_ZN2al29sendMsgPlayerInvincibleAttackEPNS_9HitSensorES1_ 0x0026ea90
{
	_ZN2al29sendMsgPlayerInvincibleAttackEPNS_9HitSensorES1_ 0x0026ea90
	{
		* (i._ZN2al29sendMsgPlayerInvincibleAttackEPNS_9HitSensorES1_)
	}
}
_ZN13PlayerTrigger3setENS_14ESensorTriggerE 0x0026ebe8
{
	_ZN13PlayerTrigger3setENS_14ESensorTriggerE 0x0026ebe8
	{
		* (i._ZN13PlayerTrigger3setENS_14ESensorTriggerE)
	}
}
_ZN2al9sendMsg58EPNS_9HitSensorES1_ 0x0026ec24
{
	_ZN2al9sendMsg58EPNS_9HitSensorES1_ 0x0026ec24
	{
		* (i._ZN2al9sendMsg58EPNS_9HitSensorES1_)
	}
}
_ZN2al13updatePoseMtxEPNS_9LiveActorEPKN4sead8Matrix34IfEE 0x0027011c
{
	_ZN2al13updatePoseMtxEPNS_9LiveActorEPKN4sead8Matrix34IfEE 0x0027011c
	{
		* (i._ZN2al13updatePoseMtxEPNS_9LiveActorEPKN4sead8Matrix34IfEE)
	}
}
_ZN2al16isPadTriggerDownEi 0x00270368
{
	_ZN2al16isPadTriggerDownEi 0x00270368
	{
		* (i._ZN2al16isPadTriggerDownEi)
	}
}
_ZN2al14isPadTriggerUpEi 0x00270370
{
	_ZN2al14isPadTriggerUpEi 0x00270370
	{
		* (i._ZN2al14isPadTriggerUpEi)
	}
}
_ZN2al16isEqualSubStringEPKcS1_ 0x0027044c
{
	_ZN2al16isEqualSubStringEPKcS1_ 0x0027044c
	{
		* (i._ZN2al16isEqualSubStringEPKcS1_)
	}
}
_ZN2al14isSensorMapObjEPKNS_9HitSensorE 0x00270628
{
	_ZN2al14isSensorMapObjEPKNS_9HitSensorE 0x00270628
	{
		* (i._ZN2al14isSensorMapObjEPKNS_9HitSensorE)
	}
}
_ZN2al17initActorPoseTFSVEPNS_9LiveActorE 0x00270b74
{
	_ZN2al17initActorPoseTFSVEPNS_9LiveActorE 0x00270b74
	{
		* (i._ZN2al17initActorPoseTFSVEPNS_9LiveActorE)
	}
}
_ZN2al11isExistRailEPKNS_9LiveActorE 0x00270f94
{
	_ZN2al11isExistRailEPKNS_9LiveActorE 0x00270f94
	{
		* (i._ZN2al11isExistRailEPKNS_9LiveActorE)
	}
}
_ZN2al17CameraParamVisionC1Ev 0x002711e0
{
	_ZN2al17CameraParamVisionC1Ev 0x002711e0
	{
		* (i._ZN2al17CameraParamVisionC1Ev)
	}
}
_ZN2al11getBaseNameEPKc 0x00272634
{
	_ZN2al11getBaseNameEPKc 0x00272634
	{
		* (i._ZN2al11getBaseNameEPKc)
	}
}
_ZN2al20isMsgGororiBigAttackEj 0x00272da0
{
	_ZN2al20isMsgGororiBigAttackEj 0x00272da0
	{
		* (i._ZN2al20isMsgGororiBigAttackEj)
	}
}
_ZN2al17isMsgGororiAttackEj 0x00272db0
{
	_ZN2al17isMsgGororiAttackEj 0x00272db0
	{
		* (i._ZN2al17isMsgGororiAttackEj)
	}
}
_ZN2al14getVelocityPtrEPNS_9LiveActorE 0x00272dc0
{
	_ZN2al14getVelocityPtrEPNS_9LiveActorE 0x00272dc0
	{
		* (i._ZN2al14getVelocityPtrEPNS_9LiveActorE)
	}
}
_ZN2al11getVelocityEPKNS_9LiveActorE 0x00272dd8
{
	_ZN2al11getVelocityEPKNS_9LiveActorE 0x00272dd8
	{
		* (i._ZN2al11getVelocityEPKNS_9LiveActorE)
	}
}
_ZN2al21isMsgPlayerFloorTouchEj 0x00273318
{
	_ZN2al21isMsgPlayerFloorTouchEj 0x00273318
	{
		* (i._ZN2al21isMsgPlayerFloorTouchEj)
	}
}
_ZN2al7setQuatEPNS_9LiveActorERKN4sead4QuatIfEE 0x00274318
{
	_ZN2al7setQuatEPNS_9LiveActorERKN4sead4QuatIfEE 0x00274318
	{
		* (i._ZN2al7setQuatEPNS_9LiveActorERKN4sead4QuatIfEE)
	}
}
_ZN2al5SceneC2EPKc 0x00274498
{
	_ZN2al5SceneC2EPKc 0x00274498
	{
		* (i._ZN2al5SceneC2EPKc)
	}
}
_ZN2al5Scene6appearEv 0x0027497c
{
	_ZN2al5Scene6appearEv 0x0027497c
	{
		* (i._ZN2al5Scene6appearEv)
	}
}
_ZN2al5Scene7endInitERKNS_13ActorInitInfoE 0x00274a7c
{
	_ZN2al5Scene7endInitERKNS_13ActorInitInfoE 0x00274a7c
	{
		* (i._ZN2al5Scene7endInitERKNS_13ActorInitInfoE)
	}
}
_ZNK2al19StageResourceKeeper16getResourceSoundEv 0x00274ee4
{
	_ZNK2al19StageResourceKeeper16getResourceSoundEv 0x00274ee4
	{
		* (i._ZNK2al19StageResourceKeeper16getResourceSoundEv)
	}
}
_ZNK2al19StageResourceKeeper14getResourceMapEv 0x00275048
{
	_ZNK2al19StageResourceKeeper14getResourceMapEv 0x00275048
	{
		* (i._ZNK2al19StageResourceKeeper14getResourceMapEv)
	}
}
_ZNK2al19StageResourceKeeper17getResourceDesignEv 0x00275514
{
	_ZNK2al19StageResourceKeeper17getResourceDesignEv 0x00275514
	{
		* (i._ZNK2al19StageResourceKeeper17getResourceDesignEv)
	}
}
_ZN2rp17createCoinRotaterEv 0x00276588
{
	_ZN2rp17createCoinRotaterEv 0x00276588
	{
		* (i._ZN2rp17createCoinRotaterEv)
	}
}
_ZN2al14createSceneObjEi 0x00276590
{
	_ZN2al14createSceneObjEi 0x00276590
	{
		* (i._ZN2al14createSceneObjEi)
	}
}
_ZN2al5Scene16initActorFactoryEv 0x00276810
{
	_ZN2al5Scene16initActorFactoryEv 0x00276810
	{
		* (i._ZN2al5Scene16initActorFactoryEv)
	}
}
_ZN19PlayerActorInitInfoC1Ev 0x00276884
{
	_ZN19PlayerActorInitInfoC1Ev 0x00276884
	{
		* (i._ZN19PlayerActorInitInfoC1Ev)
	}
}
_ZN2al8isPlacedERKNS_13ActorInitInfoE 0x00276a98
{
	_ZN2al8isPlacedERKNS_13ActorInitInfoE 0x00276a98
	{
		* (i._ZN2al8isPlacedERKNS_13ActorInitInfoE)
	}
}
_ZNK2al9ByamlIter7isValidEv 0x00276aa0
{
	_ZNK2al9ByamlIter7isValidEv 0x00276aa0
	{
		* (i._ZNK2al9ByamlIter7isValidEv)
	}
}
_ZN2al11tryGetTransEPN4sead7Vector3IfEERKNS_9ByamlIterE 0x00276b54
{
	_ZN2al11tryGetTransEPN4sead7Vector3IfEERKNS_9ByamlIterE 0x00276b54
	{
		* (i._ZN2al11tryGetTransEPN4sead7Vector3IfEERKNS_9ByamlIterE)
	}
}
_ZN2al16tryGetObjectNameEPPKcRKNS_9ByamlIterE 0x00276bf0
{
	_ZN2al16tryGetObjectNameEPPKcRKNS_9ByamlIterE 0x00276bf0
	{
		* (i._ZN2al16tryGetObjectNameEPPKcRKNS_9ByamlIterE)
	}
}
_ZN2al17initActorInitInfoEPNS_13ActorInitInfoEPKNS_9ByamlIterERKS0_ 0x00276c08
{
	_ZN2al17initActorInitInfoEPNS_13ActorInitInfoEPKNS_9ByamlIterERKS0_ 0x00276c08
	{
		* (i._ZN2al17initActorInitInfoEPNS_13ActorInitInfoEPKNS_9ByamlIterERKS0_)
	}
}
_ZN2al13ActorInitInfoC1Ev 0x00276c3c
{
	_ZN2al13ActorInitInfoC1Ev 0x00276c3c
	{
		* (i._ZN2al13ActorInitInfoC1Ev)
	}
}
_ZN2al19tryGetPlacementInfoEPNS_9ByamlIterEPKNS_8ResourceEPKc 0x00276c60
{
	_ZN2al19tryGetPlacementInfoEPNS_9ByamlIterEPKNS_8ResourceEPKc 0x00276c60
	{
		* (i._ZN2al19tryGetPlacementInfoEPNS_9ByamlIterEPKNS_8ResourceEPKc)
	}
}
_ZN2al15getLiveActorKitEv 0x00277250
{
	_ZN2al15getLiveActorKitEv 0x00277250
	{
		* (i._ZN2al15getLiveActorKitEv)
	}
}
_ZN2al11getSceneObjEi 0x002775c0
{
	_ZN2al11getSceneObjEi 0x002775c0
	{
		* (i._ZN2al11getSceneObjEi)
	}
}
_ZN2al19isMsgKickKouraBreakEj 0x00277c88
{
	_ZN2al19isMsgKickKouraBreakEj 0x00277c88
	{
		* (i._ZN2al19isMsgKickKouraBreakEj)
	}
}
_ZN2al20isMsgKickStoneAttackEj 0x00277d2c
{
	_ZN2al20isMsgKickStoneAttackEj 0x00277d2c
	{
		* (i._ZN2al20isMsgKickStoneAttackEj)
	}
}
_ZN2al15isMsgPlayerKickEj 0x00277d64
{
	_ZN2al15isMsgPlayerKickEj 0x00277d64
	{
		* (i._ZN2al15isMsgPlayerKickEj)
	}
}
_ZN2al32initCreateActorWithPlacementInfoEPNS_9LiveActorERKNS_13ActorInitInfoE 0x00277d94
{
	_ZN2al32initCreateActorWithPlacementInfoEPNS_9LiveActorERKNS_13ActorInitInfoE 0x00277d94
	{
		* (i._ZN2al32initCreateActorWithPlacementInfoEPNS_9LiveActorERKNS_13ActorInitInfoE)
	}
}
_ZN2al19startHitReactionEndEPKNS_9LiveActorE 0x0027845c
{
	_ZN2al19startHitReactionEndEPKNS_9LiveActorE 0x0027845c
	{
		* (i._ZN2al19startHitReactionEndEPKNS_9LiveActorE)
	}
}
_ZN2al12calcFrontDirEPN4sead7Vector3IfEEPKNS_9LiveActorE 0x00278660
{
	_ZN2al12calcFrontDirEPN4sead7Vector3IfEEPKNS_9LiveActorE 0x00278660
	{
		* (i._ZN2al12calcFrontDirEPN4sead7Vector3IfEEPKNS_9LiveActorE)
	}
}
_ZN2al25isMsgPlayerBoomerangBreakEj 0x00278720
{
	_ZN2al25isMsgPlayerBoomerangBreakEj 0x00278720
	{
		* (i._ZN2al25isMsgPlayerBoomerangBreakEj)
	}
}
_ZNK2al9ByamlIter16tryGetFloatByKeyEPfPKc 0x00278c30
{
	_ZNK2al9ByamlIter16tryGetFloatByKeyEPfPKc 0x00278c30
	{
		* (i._ZNK2al9ByamlIter16tryGetFloatByKeyEPfPKc)
	}
}
_ZN2al13isGreaterStepEPKNS_9IUseNerveEi 0x002799ec
{
	_ZN2al13isGreaterStepEPKNS_9IUseNerveEi 0x002799ec
	{
		* (i._ZN2al13isGreaterStepEPKNS_9IUseNerveEi)
	}
}
_ZN2al16tryGetObjectNameEPPKcRKNS_13ActorInitInfoE 0x00279bb4
{
	_ZN2al16tryGetObjectNameEPPKcRKNS_13ActorInitInfoE 0x00279bb4
	{
		* (i._ZN2al16tryGetObjectNameEPPKcRKNS_13ActorInitInfoE)
	}
}
_ZN2al6isStepEPNS_9IUseNerveEi 0x00279d14
{
	_ZN2al6isStepEPNS_9IUseNerveEi 0x00279d14
	{
		* (i._ZN2al6isStepEPNS_9IUseNerveEi)
	}
}
_ZN2al21startHitReactionDeathEPKNS_9LiveActorE 0x00279e3c
{
	_ZN2al21startHitReactionDeathEPKNS_9LiveActorE 0x00279e3c
	{
		* (i._ZN2al21startHitReactionDeathEPKNS_9LiveActorE)
	}
}
_ZN2al24startHitReactionOnGroundEPKNS_9LiveActorE 0x00279e4c
{
	_ZN2al24startHitReactionOnGroundEPKNS_9LiveActorE 0x00279e4c
	{
		* (i._ZN2al24startHitReactionOnGroundEPKNS_9LiveActorE)
	}
}
_ZN2al15setVelocityZeroEPNS_9LiveActorE 0x0027a000
{
	_ZN2al15setVelocityZeroEPNS_9LiveActorE 0x0027a000
	{
		* (i._ZN2al15setVelocityZeroEPNS_9LiveActorE)
	}
}
_ZN2al14onDrawClippingEPNS_9LiveActorE 0x0027a15c
{
	_ZN2al14onDrawClippingEPNS_9LiveActorE 0x0027a15c
	{
		* (i._ZN2al14onDrawClippingEPNS_9LiveActorE)
	}
}
_ZN2al19isSensorEnemyAttackEPKNS_9HitSensorE 0x0027a4d8
{
	_ZN2al19isSensorEnemyAttackEPKNS_9HitSensorE 0x0027a4d8
	{
		* (i._ZN2al19isSensorEnemyAttackEPKNS_9HitSensorE)
	}
}
_ZN2al13isSensorEnemyEPKNS_9HitSensorE 0x0027a508
{
	_ZN2al13isSensorEnemyEPKNS_9HitSensorE 0x0027a508
	{
		* (i._ZN2al13isSensorEnemyEPKNS_9HitSensorE)
	}
}
_ZN2rp12getPlayerPosEv 0x0027a5cc
{
	_ZN2rp12getPlayerPosEv 0x0027a5cc
	{
		* (i._ZN2rp12getPlayerPosEv)
	}
}
_ZN2al26isMsgPlayerBoomerangAttackEj 0x0027a6c4
{
	_ZN2al26isMsgPlayerBoomerangAttackEj 0x0027a6c4
	{
		* (i._ZN2al26isMsgPlayerBoomerangAttackEj)
	}
}
_ZN4sead12PtrArrayImpl9setBufferEiPv 0x0027a81c
{
	_ZN4sead12PtrArrayImpl9setBufferEiPv 0x0027a81c
	{
		* (i._ZN4sead12PtrArrayImpl9setBufferEiPv)
	}
}
_ZN2al23getLinksActorObjectNameERKNS_13ActorInitInfoEi 0x0027aaec
{
	_ZN2al23getLinksActorObjectNameERKNS_13ActorInitInfoEi 0x0027aaec
	{
		* (i._ZN2al23getLinksActorObjectNameERKNS_13ActorInitInfoEi)
	}
}
_ZN2al16calcLinkChildNumERKNS_13ActorInitInfoE 0x0027ab64
{
	_ZN2al16calcLinkChildNumERKNS_13ActorInitInfoE 0x0027ab64
	{
		* (i._ZN2al16calcLinkChildNumERKNS_13ActorInitInfoE)
	}
}
_ZN2al9onCollideEPNS_9LiveActorE 0x0027af08
{
	_ZN2al9onCollideEPNS_9LiveActorE 0x0027af08
	{
		* (i._ZN2al9onCollideEPNS_9LiveActorE)
	}
}
_ZN2al15getSensorRadiusEPKNS_9LiveActorEPKc 0x0027b054
{
	_ZN2al15getSensorRadiusEPKNS_9LiveActorEPKc 0x0027b054
	{
		* (i._ZN2al15getSensorRadiusEPKNS_9LiveActorEPKc)
	}
}
_ZN2al14isSensorPlayerEPKNS_9HitSensorE 0x0027b100
{
	_ZN2al14isSensorPlayerEPKNS_9HitSensorE 0x0027b100
	{
		* (i._ZN2al14isSensorPlayerEPKNS_9HitSensorE)
	}
}
_ZN2al13NerveExecutorC1EPKc 0x0027b194
{
	_ZN2al13NerveExecutorC1EPKc 0x0027b194
	{
		* (i._ZN2al13NerveExecutorC1EPKc)
	}
}
_ZN2al13NerveExecutor11updateNerveEv 0x0027b278
{
	_ZN2al13NerveExecutor11updateNerveEv 0x0027b278
	{
		* (i._ZN2al13NerveExecutor11updateNerveEv)
	}
}
_ZN2al9LayoutKitC1EPNS_10FontHolderE 0x0027b330
{
	_ZN2al9LayoutKitC1EPNS_10FontHolderE 0x0027b330
	{
		* (i._ZN2al9LayoutKitC1EPNS_10FontHolderE)
	}
}
_ZN2al13NerveExecutor9initNerveEPKNS_5NerveEi 0x0027b364
{
	_ZN2al13NerveExecutor9initNerveEPKNS_5NerveEi 0x0027b364
	{
		* (i._ZN2al13NerveExecutor9initNerveEPKNS_5NerveEi)
	}
}
_ZN2al10offCollideEPNS_9LiveActorE 0x0027b510
{
	_ZN2al10offCollideEPNS_9LiveActorE 0x0027b510
	{
		* (i._ZN2al10offCollideEPNS_9LiveActorE)
	}
}
_ZN2al18setSyncRailToStartEPNS_9LiveActorE 0x0027b60c
{
	_ZN2al18setSyncRailToStartEPNS_9LiveActorE 0x0027b60c
	{
		* (i._ZN2al18setSyncRailToStartEPNS_9LiveActorE)
	}
}
_ZN2al9LiveActor14initRailKeeperERKNS_13ActorInitInfoE 0x0027b638
{
	_ZN2al9LiveActor14initRailKeeperERKNS_13ActorInitInfoE 0x0027b638
	{
		* (i._ZN2al9LiveActor14initRailKeeperERKNS_13ActorInitInfoE)
	}
}
_ZN2al11isExistRailERKNS_13ActorInitInfoE 0x0027b650
{
	_ZN2al11isExistRailERKNS_13ActorInitInfoE 0x0027b650
	{
		* (i._ZN2al11isExistRailERKNS_13ActorInitInfoE)
	}
}
_ZN2al9initActorEPNS_9LiveActorERKNS_13ActorInitInfoE 0x0027b690
{
	_ZN2al9initActorEPNS_9LiveActorERKNS_13ActorInitInfoE 0x0027b690
	{
		* (i._ZN2al9initActorEPNS_9LiveActorERKNS_13ActorInitInfoE)
	}
}
_ZN2al6isMsg9Ej 0x0027b758
{
	_ZN2al6isMsg9Ej 0x0027b758
	{
		* (i._ZN2al6isMsg9Ej)
	}
}
_ZN2al10getRailDirEPKNS_9LiveActorE 0x0027c140
{
	_ZN2al10getRailDirEPKNS_9LiveActorE 0x0027c140
	{
		* (i._ZN2al10getRailDirEPKNS_9LiveActorE)
	}
}
_ZN2al10isLoopRailEPKNS_9LiveActorE 0x0027c150
{
	_ZN2al10isLoopRailEPKNS_9LiveActorE 0x0027c150
	{
		* (i._ZN2al10isLoopRailEPKNS_9LiveActorE)
	}
}
_ZN2nn4math5ARMv610VEC3SubAsmEPNS0_4VEC3EPKS2_S5_ 0x0027cb64
{
	_ZN2nn4math5ARMv610VEC3SubAsmEPNS0_4VEC3EPKS2_S5_ 0x0027cb64
	{
		* (i._ZN2nn4math5ARMv610VEC3SubAsmEPNS0_4VEC3EPKS2_S5_)
	}
}
_ZN2nn4math5ARMv610VEC3MulAsmEPNS0_4VEC3EPKS2_f 0x0027cc64
{
	_ZN2nn4math5ARMv610VEC3MulAsmEPNS0_4VEC3EPKS2_f 0x0027cc64
	{
		* (i._ZN2nn4math5ARMv610VEC3MulAsmEPNS0_4VEC3EPKS2_f)
	}
}
_ZN2al9calcUpDirEPN4sead7Vector3IfEEPKNS_9LiveActorE 0x0027d0a0
{
	_ZN2al9calcUpDirEPN4sead7Vector3IfEEPKNS_9LiveActorE 0x0027d0a0
	{
		* (i._ZN2al9calcUpDirEPN4sead7Vector3IfEEPKNS_9LiveActorE)
	}
}
_ZN2al11calcSideDirEPN4sead7Vector3IfEEPKNS_9LiveActorE 0x0027d0e0
{
	_ZN2al11calcSideDirEPN4sead7Vector3IfEEPKNS_9LiveActorE 0x0027d0e0
	{
		* (i._ZN2al11calcSideDirEPN4sead7Vector3IfEEPKNS_9LiveActorE)
	}
}
_ZN2al18sendMsgEnemyAttackEPNS_9HitSensorES1_ 0x0027d56c
{
	_ZN2al18sendMsgEnemyAttackEPNS_9HitSensorES1_ 0x0027d56c
	{
		* (i._ZN2al18sendMsgEnemyAttackEPNS_9HitSensorES1_)
	}
}
_ZN2al10getGravityEPKNS_9LiveActorE 0x0027d588
{
	_ZN2al10getGravityEPKNS_9LiveActorE 0x0027d588
	{
		* (i._ZN2al10getGravityEPKNS_9LiveActorE)
	}
}
_ZN2al25startHitReactionPressDownEPKNS_9LiveActorE 0x0027d660
{
	_ZN2al25startHitReactionPressDownEPKNS_9LiveActorE 0x0027d660
	{
		* (i._ZN2al25startHitReactionPressDownEPKNS_9LiveActorE)
	}
}
_ZN2al25isMsgPlayerFireBallAttackEj 0x0027db98
{
	_ZN2al25isMsgPlayerFireBallAttackEj 0x0027db98
	{
		* (i._ZN2al25isMsgPlayerFireBallAttackEj)
	}
}
_ZN2al21isMsgPlayerTailAttackEj 0x0027dba8
{
	_ZN2al21isMsgPlayerTailAttackEj 0x0027dba8
	{
		* (i._ZN2al21isMsgPlayerTailAttackEj)
	}
}
_ZN2al27isMsgPlayerBoomerangReflectEj 0x0027dbb8
{
	_ZN2al27isMsgPlayerBoomerangReflectEj 0x0027dbb8
	{
		* (i._ZN2al27isMsgPlayerBoomerangReflectEj)
	}
}
_ZN2al22isMsgPlayerStatueTouchEj 0x0027dc18
{
	_ZN2al22isMsgPlayerStatueTouchEj 0x0027dc18
	{
		* (i._ZN2al22isMsgPlayerStatueTouchEj)
	}
}
_ZN2al12isSensorNameEPNS_9HitSensorEPKc 0x0027dc38
{
	_ZN2al12isSensorNameEPNS_9HitSensorEPKc 0x0027dc38
	{
		* (i._ZN2al12isSensorNameEPNS_9HitSensorEPKc)
	}
}
_ZN2al27isMsgPlayerInvincibleAttackEj 0x0027dc40
{
	_ZN2al27isMsgPlayerInvincibleAttackEj 0x0027dc40
	{
		* (i._ZN2al27isMsgPlayerInvincibleAttackEj)
	}
}
_ZN2al26isMsgPlayerInvincibleTouchEj 0x0027dc50
{
	_ZN2al26isMsgPlayerInvincibleTouchEj 0x0027dc50
	{
		* (i._ZN2al26isMsgPlayerInvincibleTouchEj)
	}
}
_ZN11PlayerActor11getPropertyEv 0x0027def0
{
	_ZN11PlayerActor11getPropertyEv 0x0027def0
	{
		* (i._ZN11PlayerActor11getPropertyEv)
	}
}
_ZN2al7AreaObjC1EPKc 0x0027e01c
{
	_ZN2al7AreaObjC1EPKc 0x0027e01c
	{
		* (i._ZN2al7AreaObjC1EPKc)
	}
}
_ZNK2al9ByamlIter14tryGetIntByKeyEPiPKc 0x0027e068
{
	_ZNK2al9ByamlIter14tryGetIntByKeyEPiPKc 0x0027e068
	{
		* (i._ZNK2al9ByamlIter14tryGetIntByKeyEPiPKc)
	}
}
_ZN2al11LayoutActor9initNerveEPKNS_5NerveEi 0x0027e610
{
	_ZN2al11LayoutActor9initNerveEPKNS_5NerveEi 0x0027e610
	{
		* (i._ZN2al11LayoutActor9initNerveEPKNS_5NerveEi)
	}
}
_ZN2al11LayoutActorC1EPKc 0x0027e648
{
	_ZN2al11LayoutActorC1EPKc 0x0027e648
	{
		* (i._ZN2al11LayoutActorC1EPKc)
	}
}
_ZN2al10WipeSimple6appearEv 0x0027e828
{
	_ZN2al10WipeSimple6appearEv 0x0027e828
	{
		* (i._ZN2al10WipeSimple6appearEv)
	}
}
_ZN2al11LayoutActor6appearEv 0x0027e82c
{
	_ZN2al11LayoutActor6appearEv 0x0027e82c
	{
		* (i._ZN2al11LayoutActor6appearEv)
	}
}
_ZN2al11LayoutActor4killEv 0x0027e85c
{
	_ZN2al11LayoutActor4killEv 0x0027e85c
	{
		* (i._ZN2al11LayoutActor4killEv)
	}
}
_ZN2al8getScaleEPKNS_9LiveActorE 0x0027e9dc
{
	_ZN2al8getScaleEPKNS_9LiveActorE 0x0027e9dc
	{
		* (i._ZN2al8getScaleEPKNS_9LiveActorE)
	}
}
_ZN2al9LiveActor4killEv 0x0027ebf0
{
	_ZN2al9LiveActor4killEv 0x0027ebf0
	{
		* (i._ZN2al9LiveActor4killEv)
	}
}
_ZN2al21startHitReactionBreakEPKNS_9LiveActorE 0x0027ec94
{
	_ZN2al21startHitReactionBreakEPKNS_9LiveActorE 0x0027ec94
	{
		* (i._ZN2al21startHitReactionBreakEPKNS_9LiveActorE)
	}
}
_ZN2al7getQuatEPKNS_9LiveActorE 0x0027ee24
{
	_ZN2al7getQuatEPKNS_9LiveActorE 0x0027ee24
	{
		* (i._ZN2al7getQuatEPKNS_9LiveActorE)
	}
}
_ZN2al30initCreateActorNoPlacementInfoEPNS_9LiveActorERKNS_13ActorInitInfoE 0x0027ee64
{
	_ZN2al30initCreateActorNoPlacementInfoEPNS_9LiveActorERKNS_13ActorInitInfoE 0x0027ee64
	{
		* (i._ZN2al30initCreateActorNoPlacementInfoEPNS_9LiveActorERKNS_13ActorInitInfoE)
	}
}
_ZN2al12isObjectNameERKNS_13ActorInitInfoEPKc 0x0027ef70
{
	_ZN2al12isObjectNameERKNS_13ActorInitInfoEPKc 0x0027ef70
	{
		* (i._ZN2al12isObjectNameERKNS_13ActorInitInfoEPKc)
	}
}
_ZN2al10BreakModelC1EPNS_9LiveActorEPKcS4_PKN4sead8Matrix34IfEES4_ 0x0027f0bc
{
	_ZN2al10BreakModelC1EPNS_9LiveActorEPKcS4_PKN4sead8Matrix34IfEES4_ 0x0027f0bc
	{
		* (i._ZN2al10BreakModelC1EPNS_9LiveActorEPKcS4_PKN4sead8Matrix34IfEES4_)
	}
}
_ZN2al24isMsgPlayerRollingAttackEj 0x0027f1b8
{
	_ZN2al24isMsgPlayerRollingAttackEj 0x0027f1b8
	{
		* (i._ZN2al24isMsgPlayerRollingAttackEj)
	}
}
_ZN2al15isMsgUpperPunchEj 0x0027f330
{
	_ZN2al15isMsgUpperPunchEj 0x0027f330
	{
		* (i._ZN2al15isMsgUpperPunchEj)
	}
}
_ZN2al18isGreaterEqualStepEPKNS_9IUseNerveEi 0x0027f340
{
	_ZN2al18isGreaterEqualStepEPKNS_9IUseNerveEi 0x0027f340
	{
		* (i._ZN2al18isGreaterEqualStepEPKNS_9IUseNerveEi)
	}
}
_ZN2al8setTransEPNS_9LiveActorERKN4sead7Vector3IfEE 0x0027f394
{
	_ZN2al8setTransEPNS_9LiveActorERKN4sead7Vector3IfEE 0x0027f394
	{
		* (i._ZN2al8setTransEPNS_9LiveActorERKN4sead7Vector3IfEE)
	}
}
_ZN2al10getQuatPtrEPNS_9LiveActorE 0x0027f3b4
{
	_ZN2al10getQuatPtrEPNS_9LiveActorE 0x0027f3b4
	{
		* (i._ZN2al10getQuatPtrEPNS_9LiveActorE)
	}
}
_ZN2al11getTransPtrEPNS_9LiveActorE 0x0027f3c4
{
	_ZN2al11getTransPtrEPNS_9LiveActorE 0x0027f3c4
	{
		* (i._ZN2al11getTransPtrEPNS_9LiveActorE)
	}
}
_ZN2al11isFirstStepEPKNS_9IUseNerveE 0x0027f514
{
	_ZN2al11isFirstStepEPKNS_9IUseNerveE 0x0027f514
	{
		* (i._ZN2al11isFirstStepEPKNS_9IUseNerveE)
	}
}
_ZN2al16startNerveActionEPNS_9LiveActorEPKc 0x0027fbe0
{
	_ZN2al16startNerveActionEPNS_9LiveActorEPKc 0x0027fbe0
	{
		* (i._ZN2al16startNerveActionEPNS_9LiveActorEPKc)
	}
}
_ZN2al9LiveActorC1EPKc 0x0027fe9c
{
	_ZN2al9LiveActorC1EPKc 0x0027fe9c
	{
		* (i._ZN2al9LiveActorC1EPKc)
	}
}
_ZN2al9LiveActor6appearEv 0x0027ff70
{
	_ZN2al9LiveActor6appearEv 0x0027ff70
	{
		* (i._ZN2al9LiveActor6appearEv)
	}
}
_ZN2al19startHitReactionGetEPKNS_9LiveActorE 0x00280270
{
	_ZN2al19startHitReactionGetEPKNS_9LiveActorE 0x00280270
	{
		* (i._ZN2al19startHitReactionGetEPKNS_9LiveActorE)
	}
}
_ZN2al8getTransEPKNS_9LiveActorE 0x0028028c
{
	_ZN2al8getTransEPKNS_9LiveActorE 0x0028028c
	{
		* (i._ZN2al8getTransEPKNS_9LiveActorE)
	}
}
_ZN2al11MapObjActorC1ERKN4sead14SafeStringBaseIcEE 0x00280428
{
	_ZN2al11MapObjActorC1ERKN4sead14SafeStringBaseIcEE 0x00280428
	{
		* (i._ZN2al11MapObjActorC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN2al17initActorPoseTQSVEPNS_9LiveActorE 0x00280590
{
	_ZN2al17initActorPoseTQSVEPNS_9LiveActorE 0x00280590
	{
		* (i._ZN2al17initActorPoseTQSVEPNS_9LiveActorE)
	}
}
_ZN2al8setNerveEPNS_9IUseNerveEPKNS_5NerveE 0x00280610
{
	_ZN2al8setNerveEPNS_9IUseNerveEPKNS_5NerveE 0x00280610
	{
		* (i._ZN2al8setNerveEPNS_9IUseNerveEPKNS_5NerveE)
	}
}
_ZN2al18invalidateClippingEPNS_9LiveActorE 0x0028065c
{
	_ZN2al18invalidateClippingEPNS_9LiveActorE 0x0028065c
	{
		* (i._ZN2al18invalidateClippingEPNS_9LiveActorE)
	}
}
_ZN2al7isNerveEPKNS_9IUseNerveEPKNS_5NerveE 0x002806a8
{
	_ZN2al7isNerveEPKNS_9IUseNerveEPKNS_5NerveE 0x002806a8
	{
		* (i._ZN2al7isNerveEPKNS_9IUseNerveEPKNS_5NerveE)
	}
}
_printf_cs_common 0x0028940c
{
	_printf_cs_common 0x0028940c
	{
		* (:gdef:_printf_cs_common)
	}
}
_sputc 0x00289e98
{
	_sputc 0x00289e98
	{
		* (:gdef:_sputc)
	}
}
_printf_input_char 0x00289ea8
{
	_printf_input_char 0x00289ea8
	{
		* (:gdef:_printf_input_char)
	}
}
_printf_char_common 0x00289ebc
{
	_printf_char_common 0x00289ebc
	{
		* (:gdef:_printf_char_common)
	}
}
strcmp 0x0028aa60
{
	strcmp 0x0028aa60
	{
		* (:gdef:strcmp)
	}
}
_ZNK2al20ByamlStringTableIter15findStringIndexEPKc 0x0028b518
{
	_ZNK2al20ByamlStringTableIter15findStringIndexEPKc 0x0028b518
	{
		* (i._ZNK2al20ByamlStringTableIter15findStringIndexEPKc)
	}
}
_ZN2nn3svc11GetThreadIdEPjNS_6HandleE 0x0028b644
{
	_ZN2nn3svc11GetThreadIdEPjNS_6HandleE 0x0028b644
	{
		* (i._ZN2nn3svc11GetThreadIdEPjNS_6HandleE)
	}
}
_ZN2nn3svc12GetProcessIdEPjNS_6HandleE 0x0028bbc4
{
	_ZN2nn3svc12GetProcessIdEPjNS_6HandleE 0x0028bbc4
	{
		* (i._ZN2nn3svc12GetProcessIdEPjNS_6HandleE)
	}
}
_ZN2nn3svc11SleepThreadEy 0x0028bc4c
{
	_ZN2nn3svc11SleepThreadEy 0x0028bc4c
	{
		* (i._ZN2nn3svc11SleepThreadEy)
	}
}
_ZN2nn3svc16ArbitrateAddressENS_6HandleEjNS_2os15ArbitrationTypeEix 0x0028bc84
{
	_ZN2nn3svc16ArbitrateAddressENS_6HandleEjNS_2os15ArbitrationTypeEix 0x0028bc84
	{
		* (i._ZN2nn3svc16ArbitrateAddressENS_6HandleEjNS_2os15ArbitrationTypeEix)
	}
}
_ZN2al11loadArchiveERKN4sead14SafeStringBaseIcEE 0x0028c2a4
{
	_ZN2al11loadArchiveERKN4sead14SafeStringBaseIcEE 0x0028c2a4
	{
		* (i._ZN2al11loadArchiveERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN2al9ByamlIterC1ERKS0_ 0x0028c2f8
{
	_ZN2al9ByamlIterC1ERKS0_ 0x0028c2f8
	{
		* (i._ZN2al9ByamlIterC1ERKS0_)
	}
}
_ZN2nn3svc13ConnectToPortEPNS_6HandleEPKc 0x0028dc40
{
	_ZN2nn3svc13ConnectToPortEPNS_6HandleEPKc 0x0028dc40
	{
		* (i._ZN2nn3svc13ConnectToPortEPNS_6HandleEPKc)
	}
}
_ZN2al14getApplicationEv 0x0028e688
{
	_ZN2al14getApplicationEv 0x0028e688
	{
		* (i._ZN2al14getApplicationEv)
	}
}
_ZN4sead8ListNode12insertFront_EPS0_ 0x0028e948
{
	_ZN4sead8ListNode12insertFront_EPS0_ 0x0028e948
	{
		* (i._ZN4sead8ListNode12insertFront_EPS0_)
	}
}
__aeabi_vec_ctor_nocookie_nodtor 0x0028eabc
{
	__aeabi_vec_ctor_nocookie_nodtor 0x0028eabc
	{
		* (i.__aeabi_vec_ctor_nocookie_nodtor)
	}
}
_ZN2nn3svc20WaitSynchronizationNEPiPKNS_6HandleEibx 0x0028eba8
{
	_ZN2nn3svc20WaitSynchronizationNEPiPKNS_6HandleEibx 0x0028eba8
	{
		* (i._ZN2nn3svc20WaitSynchronizationNEPiPKNS_6HandleEibx)
	}
}
_ZN2nn3svc5BreakENS_3dbg11BreakReasonE 0x0028ec90
{
	_ZN2nn3svc5BreakENS_3dbg11BreakReasonE 0x0028ec90
	{
		* (i._ZN2nn3svc5BreakENS_3dbg11BreakReasonE)
	}
}
_ZN2al9ByamlIterC1EPKh 0x002905f0
{
	_ZN2al9ByamlIterC1EPKh 0x002905f0
	{
		* (i._ZN2al9ByamlIterC1EPKh)
	}
}
_ZN2al24makeLocalizedArchivePathEPN4sead22BufferedSafeStringBaseIcEERKNS0_14SafeStringBaseIcEE 0x00290eb0
{
	_ZN2al24makeLocalizedArchivePathEPN4sead22BufferedSafeStringBaseIcEERKNS0_14SafeStringBaseIcEE 0x00290eb0
	{
		* (i._ZN2al24makeLocalizedArchivePathEPN4sead22BufferedSafeStringBaseIcEERKNS0_14SafeStringBaseIcEE)
	}
}
_ZNK2al9ByamlIter15tryGetBoolByKeyEPbPKc 0x00290f60
{
	_ZNK2al9ByamlIter15tryGetBoolByKeyEPbPKc 0x00290f60
	{
		* (i._ZNK2al9ByamlIter15tryGetBoolByKeyEPbPKc)
	}
}
_ZN2al9ByamlIterC1Ev 0x002910e8
{
	_ZN2al9ByamlIterC1Ev 0x002910e8
	{
		* (i._ZN2al9ByamlIterC1Ev)
	}
}
_ZNK2al9ByamlIter7getSizeEv 0x002910f8
{
	_ZNK2al9ByamlIter7getSizeEv 0x002910f8
	{
		* (i._ZNK2al9ByamlIter7getSizeEv)
	}
}
_ZN2nn3svc11CreateEventEPNS_6HandleENS_2os9ResetTypeE 0x00291970
{
	_ZN2nn3svc11CreateEventEPNS_6HandleENS_2os9ResetTypeE 0x00291970
	{
		* (i._ZN2nn3svc11CreateEventEPNS_6HandleENS_2os9ResetTypeE)
	}
}
strlen 0x00292158
{
	strlen 0x00292158
	{
		* (:gdef:strlen)
	}
}
_ZN2al13isEqualStringEPKcS1_ 0x00292308
{
	_ZN2al13isEqualStringEPKcS1_ 0x00292308
	{
		* (i._ZN2al13isEqualStringEPKcS1_)
	}
}
_ZN18alProjectInterface12getSystemKitEv 0x00292d10
{
	_ZN18alProjectInterface12getSystemKitEv 0x00292d10
	{
		* (i._ZN18alProjectInterface12getSystemKitEv)
	}
}
_ZN2nn3svc13ControlMemoryEPjjjjjj 0x00293054
{
	_ZN2nn3svc13ControlMemoryEPjjjjjj 0x00293054
	{
		* (i._ZN2nn3svc13ControlMemoryEPjjjjjj)
	}
}
_ZN2al16getStationedHeapEv 0x0029329c
{
	_ZN2al16getStationedHeapEv 0x0029329c
	{
		* (i._ZN2al16getStationedHeapEv)
	}
}
_ZN2nn3svc11ExitProcessEv 0x00293614
{
	_ZN2nn3svc11ExitProcessEv 0x00293614
	{
		* (i._ZN2nn3svc11ExitProcessEv)
	}
}
_ZN2al3Sky4initERKNS_13ActorInitInfoE 0x002d4ff4
{
	_ZN2al3Sky4initERKNS_13ActorInitInfoE 0x002d4ff4
	{
		* (i._ZN2al3Sky4initERKNS_13ActorInitInfoE)
	}
}
_ZN2al3SkyC1EPKc 0x002d503c
{
	_ZN2al3SkyC1EPKc 0x002d503c
	{
		* (i._ZN2al3SkyC1EPKc)
	}
}
_ZN4sead7HeapMgrC1Ev 0x002f0424
{
	_ZN4sead7HeapMgrC1Ev 0x002f0424
	{
		* (i._ZN4sead7HeapMgrC1Ev)
	}
}
_ZN6Togezo4initERKN2al13ActorInitInfoE 0x0030b60c
{
	_ZN6Togezo4initERKN2al13ActorInitInfoE 0x0030b60c
	{
		* (i._ZN6Togezo4initERKN2al13ActorInitInfoE)
	}
}
_ZN6TogezoC1ERKN4sead14SafeStringBaseIcEE 0x0030b860
{
	_ZN6TogezoC1ERKN4sead14SafeStringBaseIcEE 0x0030b860
	{
		* (i._ZN6TogezoC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN7NoteObj18initAfterPlacementEv 0x00312660
{
	_ZN7NoteObj18initAfterPlacementEv 0x00312660
	{
		* (i._ZN7NoteObj18initAfterPlacementEv)
	}
}
_ZN7RailDot4initERKN2al13ActorInitInfoE 0x00313464
{
	_ZN7RailDot4initERKN2al13ActorInitInfoE 0x00313464
	{
		* (i._ZN7RailDot4initERKN2al13ActorInitInfoE)
	}
}
_ZN7RailDotC1ERKN4sead14SafeStringBaseIcEE 0x003134c8
{
	_ZN7RailDotC1ERKN4sead14SafeStringBaseIcEE 0x003134c8
	{
		* (i._ZN7RailDotC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN8FireBall10receiveMsgEjPN2al9HitSensorES2_ 0x00314dcc
{
	_ZN8FireBall10receiveMsgEjPN2al9HitSensorES2_ 0x00314dcc
	{
		* (i._ZN8FireBall10receiveMsgEjPN2al9HitSensorES2_)
	}
}
_ZN8FireBall12attackSensorEPN2al9HitSensorES2_ 0x00314e40
{
	_ZN8FireBall12attackSensorEPN2al9HitSensorES2_ 0x00314e40
	{
		* (i._ZN8FireBall12attackSensorEPN2al9HitSensorES2_)
	}
}
_ZN8FireBall4initERKN2al13ActorInitInfoE 0x00314ee4
{
	_ZN8FireBall4initERKN2al13ActorInitInfoE 0x00314ee4
	{
		* (i._ZN8FireBall4initERKN2al13ActorInitInfoE)
	}
}
_ZN8FireBallC1ERKN4sead14SafeStringBaseIcEE 0x00314fe4
{
	_ZN8FireBallC1ERKN4sead14SafeStringBaseIcEE 0x00314fe4
	{
		* (i._ZN8FireBallC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN2al8Sequence4initEv 0x00318a2c
{
	_ZN2al8Sequence4initEv 0x00318a2c
	{
		* (i._ZN2al8Sequence4initEv)
	}
}
_ZN2al8Sequence4unk3Ev 0x00318a30
{
	_ZN2al8Sequence4unk3Ev 0x00318a30
	{
		* (i._ZN2al8Sequence4unk3Ev)
	}
}
_ZN2al8Sequence4unk1Ev 0x00318a4c
{
	_ZN2al8Sequence4unk1Ev 0x00318a4c
	{
		* (i._ZN2al8Sequence4unk1Ev)
	}
}
_ZN2al8Sequence4unk2Ev 0x00318a68
{
	_ZN2al8Sequence4unk2Ev 0x00318a68
	{
		* (i._ZN2al8Sequence4unk2Ev)
	}
}
_ZN2al9EffectObj17makeActorAppearedEv 0x0031b378
{
	_ZN2al9EffectObj17makeActorAppearedEv 0x0031b378
	{
		* (i._ZN2al9EffectObj17makeActorAppearedEv)
	}
}
_ZN2al9EffectObj4initERKNS_13ActorInitInfoE 0x0031b3ac
{
	_ZN2al9EffectObj4initERKNS_13ActorInitInfoE 0x0031b3ac
	{
		* (i._ZN2al9EffectObj4initERKNS_13ActorInitInfoE)
	}
}
_ZN2al17EffectObjFunction18initActorEffectObjEPNS_9EffectObjERKNS_13ActorInitInfoEPKc 0x0031b45c
{
	_ZN2al17EffectObjFunction18initActorEffectObjEPNS_9EffectObjERKNS_13ActorInitInfoEPKc 0x0031b45c
	{
		* (i._ZN2al17EffectObjFunction18initActorEffectObjEPNS_9EffectObjERKNS_13ActorInitInfoEPKc)
	}
}
_ZN2al9EffectObj4killEv 0x0031b4f8
{
	_ZN2al9EffectObj4killEv 0x0031b4f8
	{
		* (i._ZN2al9EffectObj4killEv)
	}
}
_ZN9FlowerPot4initERKN2al13ActorInitInfoE 0x0031b6ec
{
	_ZN9FlowerPot4initERKN2al13ActorInitInfoE 0x0031b6ec
	{
		* (i._ZN9FlowerPot4initERKN2al13ActorInitInfoE)
	}
}
_ZN9FlowerPotC1ERKN4sead14SafeStringBaseIcEE 0x0031b754
{
	_ZN9FlowerPotC1ERKN4sead14SafeStringBaseIcEE 0x0031b754
	{
		* (i._ZN9FlowerPotC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZN9PeachRope4initERKN2al13ActorInitInfoE 0x00321a60
{
	_ZN9PeachRope4initERKN2al13ActorInitInfoE 0x00321a60
	{
		* (i._ZN9PeachRope4initERKN2al13ActorInitInfoE)
	}
}
_ZN9PeachRope4killEv 0x00321ab4
{
	_ZN9PeachRope4killEv 0x00321ab4
	{
		* (i._ZN9PeachRope4killEv)
	}
}
_ZN9PeachRopeC1ERKN4sead14SafeStringBaseIcEE 0x00321acc
{
	_ZN9PeachRopeC1ERKN4sead14SafeStringBaseIcEE 0x00321acc
	{
		* (i._ZN9PeachRopeC1ERKN4sead14SafeStringBaseIcEE)
	}
}
_ZNK14PlayerAnimator12getAnimFrameEv 0x0032c73c
{
	_ZNK14PlayerAnimator12getAnimFrameEv 0x0032c73c
	{
		* (i._ZNK14PlayerAnimator12getAnimFrameEv)
	}
}
_ZNK19PlayerAnimFrameCtrl15getCurrentFrameEv 0x0032c744
{
	_ZNK19PlayerAnimFrameCtrl15getCurrentFrameEv 0x0032c744
	{
		* (i._ZNK19PlayerAnimFrameCtrl15getCurrentFrameEv)
	}
}
_ZN24KoopaLastStageStartParam16getStageDataNameEv 0x0032f2a0
{
	_ZN24KoopaLastStageStartParam16getStageDataNameEv 0x0032f2a0
	{
		* (i._ZN24KoopaLastStageStartParam16getStageDataNameEv)
	}
}
_ZNK2al10FunctorV0FclEv 0x0032f444
{
	_ZNK2al10FunctorV0FclEv 0x0032f444
	{
		* (i._ZNK2al10FunctorV0FclEv)
	}
}
_ZNK2al10RailKeeper11isExistRailEv 0x0032f618
{
	_ZNK2al10RailKeeper11isExistRailEv 0x0032f618
	{
		* (i._ZNK2al10RailKeeper11isExistRailEv)
	}
}
_ZNK2al11LayoutActor14getNerveKeeperEv 0x0032fa78
{
	_ZNK2al11LayoutActor14getNerveKeeperEv 0x0032fa78
	{
		* (i._ZNK2al11LayoutActor14getNerveKeeperEv)
	}
}
_ZNK2al11LayoutActor15getEffectKeeperEv 0x0032fa80
{
	_ZNK2al11LayoutActor15getEffectKeeperEv 0x0032fa80
	{
		* (i._ZNK2al11LayoutActor15getEffectKeeperEv)
	}
}
_ZNK2al11NerveKeeper15getCurrentNerveEv 0x0032fd54
{
	_ZNK2al11NerveKeeper15getCurrentNerveEv 0x0032fd54
	{
		* (i._ZNK2al11NerveKeeper15getCurrentNerveEv)
	}
}
_ZNK2al13ByamlHashIter8findPairEi 0x00331350
{
	_ZNK2al13ByamlHashIter8findPairEi 0x00331350
	{
		* (i._ZNK2al13ByamlHashIter8findPairEi)
	}
}
_ZNK2al13NerveExecutor14getNerveKeeperEv 0x00331520
{
	_ZNK2al13NerveExecutor14getNerveKeeperEv 0x00331520
	{
		* (i._ZNK2al13NerveExecutor14getNerveKeeperEv)
	}
}
_ZN2al15isExistSceneObjEi 0x00332840
{
	_ZN2al15isExistSceneObjEi 0x00332840
	{
		* (i._ZN2al15isExistSceneObjEi)
	}
}
_ZNK2al14SceneObjHolder7isExistEi 0x00332858
{
	_ZNK2al14SceneObjHolder7isExistEi 0x00332858
	{
		* (i._ZNK2al14SceneObjHolder7isExistEi)
	}
}
_ZNK2al14SceneObjHolder6getObjEi 0x00332884
{
	_ZNK2al14SceneObjHolder6getObjEi 0x00332884
	{
		* (i._ZNK2al14SceneObjHolder6getObjEi)
	}
}
_ZNK2al15NerveActionCtrl9findNerveEPKc 0x00332a7c
{
	_ZNK2al15NerveActionCtrl9findNerveEPKc 0x00332a7c
	{
		* (i._ZNK2al15NerveActionCtrl9findNerveEPKc)
	}
}
_ZNK2al19ActorPoseKeeperBase7getQuatEv 0x00334ef8
{
	_ZNK2al19ActorPoseKeeperBase7getQuatEv 0x00334ef8
	{
		* (i._ZNK2al19ActorPoseKeeperBase7getQuatEv)
	}
}
_ZNK2al19ActorPoseKeeperBase8getFrontEv 0x00334f04
{
	_ZNK2al19ActorPoseKeeperBase8getFrontEv 0x00334f04
	{
		* (i._ZNK2al19ActorPoseKeeperBase8getFrontEv)
	}
}
_ZNK2al19ActorPoseKeeperBase9getRotateEv 0x00334f10
{
	_ZNK2al19ActorPoseKeeperBase9getRotateEv 0x00334f10
	{
		* (i._ZNK2al19ActorPoseKeeperBase9getRotateEv)
	}
}
_ZNK2al19ActorPoseKeeperTFSV11getVelocityEv 0x00334f78
{
	_ZNK2al19ActorPoseKeeperTFSV11getVelocityEv 0x00334f78
	{
		* (i._ZNK2al19ActorPoseKeeperTFSV11getVelocityEv)
	}
}
_ZNK2al19ActorPoseKeeperTFSV8getFrontEv 0x00334f80
{
	_ZNK2al19ActorPoseKeeperTFSV8getFrontEv 0x00334f80
	{
		* (i._ZNK2al19ActorPoseKeeperTFSV8getFrontEv)
	}
}
_ZNK2al19ActorPoseKeeperTFSV8getScaleEv 0x00334f88
{
	_ZNK2al19ActorPoseKeeperTFSV8getScaleEv 0x00334f88
	{
		* (i._ZNK2al19ActorPoseKeeperTFSV8getScaleEv)
	}
}
_ZNK2al19ActorPoseKeeperTQSV11getVelocityEv 0x00335064
{
	_ZNK2al19ActorPoseKeeperTQSV11getVelocityEv 0x00335064
	{
		* (i._ZNK2al19ActorPoseKeeperTQSV11getVelocityEv)
	}
}
_ZNK2al19ActorPoseKeeperTQSV7getQuatEv 0x0033506c
{
	_ZNK2al19ActorPoseKeeperTQSV7getQuatEv 0x0033506c
	{
		* (i._ZNK2al19ActorPoseKeeperTQSV7getQuatEv)
	}
}
_ZNK2al19ActorPoseKeeperTQSV8getScaleEv 0x00335074
{
	_ZNK2al19ActorPoseKeeperTQSV8getScaleEv 0x00335074
	{
		* (i._ZNK2al19ActorPoseKeeperTQSV8getScaleEv)
	}
}
_ZNK2al19ActorPoseKeeperTRSV11getVelocityEv 0x003350e0
{
	_ZNK2al19ActorPoseKeeperTRSV11getVelocityEv 0x003350e0
	{
		* (i._ZNK2al19ActorPoseKeeperTRSV11getVelocityEv)
	}
}
_ZNK2al19ActorPoseKeeperTRSV8getScaleEv 0x003350e8
{
	_ZNK2al19ActorPoseKeeperTRSV8getScaleEv 0x003350e8
	{
		* (i._ZNK2al19ActorPoseKeeperTRSV8getScaleEv)
	}
}
_ZNK2al19ActorPoseKeeperTRSV9getRotateEv 0x003350f0
{
	_ZNK2al19ActorPoseKeeperTRSV9getRotateEv 0x003350f0
	{
		* (i._ZNK2al19ActorPoseKeeperTRSV9getRotateEv)
	}
}
_ZNK2al20ActorPoseKeeperTFGSV10getGravityEv 0x003352a0
{
	_ZNK2al20ActorPoseKeeperTFGSV10getGravityEv 0x003352a0
	{
		* (i._ZNK2al20ActorPoseKeeperTFGSV10getGravityEv)
	}
}
_ZNK2al5Nerve12executeOnEndEPNS_11NerveKeeperE 0x00336f6c
{
	_ZNK2al5Nerve12executeOnEndEPNS_11NerveKeeperE 0x00336f6c
	{
		* (i._ZNK2al5Nerve12executeOnEndEPNS_11NerveKeeperE)
	}
}
_ZNK2al7AreaObj10isInVolumeERKN4sead7Vector3IfEE 0x00337030
{
	_ZNK2al7AreaObj10isInVolumeERKN4sead7Vector3IfEE 0x00337030
	{
		* (i._ZNK2al7AreaObj10isInVolumeERKN4sead7Vector3IfEE)
	}
}
_ZNK2al7AreaObj20getStageSwitchKeeperEv 0x00337054
{
	_ZNK2al7AreaObj20getStageSwitchKeeperEv 0x00337054
	{
		* (i._ZNK2al7AreaObj20getStageSwitchKeeperEv)
	}
}
_ZNK2al9LiveActor14getNerveKeeperEv 0x003375f4
{
	_ZNK2al9LiveActor14getNerveKeeperEv 0x003375f4
	{
		* (i._ZNK2al9LiveActor14getNerveKeeperEv)
	}
}
_ZNK2al9LiveActor15getEffectKeeperEv 0x00337604
{
	_ZNK2al9LiveActor15getEffectKeeperEv 0x00337604
	{
		* (i._ZNK2al9LiveActor15getEffectKeeperEv)
	}
}
_ZN2al17isRailReachedGoalEPKNS_9LiveActorE 0x0033760c
{
	_ZN2al17isRailReachedGoalEPKNS_9LiveActorE 0x0033760c
	{
		* (i._ZN2al17isRailReachedGoalEPKNS_9LiveActorE)
	}
}
_ZNK2al9RailRider13isReachedGoalEv 0x00337618
{
	_ZNK2al9RailRider13isReachedGoalEv 0x00337618
	{
		* (i._ZNK2al9RailRider13isReachedGoalEv)
	}
}
_ZNK9NrvTogezo17TogezoNrvBlowDown7executeEPN2al11NerveKeeperE 0x00349af0
{
	_ZNK9NrvTogezo17TogezoNrvBlowDown7executeEPN2al11NerveKeeperE 0x00349af0
	{
		* (i._ZNK9NrvTogezo17TogezoNrvBlowDown7executeEPN2al11NerveKeeperE)
	}
}
_ZNK9NrvTogezo15TogezoNrvSearch7executeEPN2al11NerveKeeperE 0x00349b2c
{
	_ZNK9NrvTogezo15TogezoNrvSearch7executeEPN2al11NerveKeeperE 0x00349b2c
	{
		* (i._ZNK9NrvTogezo15TogezoNrvSearch7executeEPN2al11NerveKeeperE)
	}
}
_ZNK9NrvTogezo14TogezoNrvChase7executeEPN2al11NerveKeeperE 0x00349be8
{
	_ZNK9NrvTogezo14TogezoNrvChase7executeEPN2al11NerveKeeperE 0x00349be8
	{
		* (i._ZNK9NrvTogezo14TogezoNrvChase7executeEPN2al11NerveKeeperE)
	}
}
_ZNK9NrvTogezo15TogezoNrvWander7executeEPN2al11NerveKeeperE 0x00349c28
{
	_ZNK9NrvTogezo15TogezoNrvWander7executeEPN2al11NerveKeeperE 0x00349c28
	{
		* (i._ZNK9NrvTogezo15TogezoNrvWander7executeEPN2al11NerveKeeperE)
	}
}
_ZNK9NrvTogezo13TogezoNrvTurn7executeEPN2al11NerveKeeperE 0x00349c80
{
	_ZNK9NrvTogezo13TogezoNrvTurn7executeEPN2al11NerveKeeperE 0x00349c80
	{
		* (i._ZNK9NrvTogezo13TogezoNrvTurn7executeEPN2al11NerveKeeperE)
	}
}
_ZNK10NrvRailDot14RailDotNrvWait7executeEPN2al11NerveKeeperE 0x0034c4e8
{
	_ZNK10NrvRailDot14RailDotNrvWait7executeEPN2al11NerveKeeperE 0x0034c4e8
	{
		* (i._ZNK10NrvRailDot14RailDotNrvWait7executeEPN2al11NerveKeeperE)
	}
}
_ZNK13NrvAppearStep17AppearStepNrvWait7executeEPN2al11NerveKeeperE 0x00350810
{
	_ZNK13NrvAppearStep17AppearStepNrvWait7executeEPN2al11NerveKeeperE 0x00350810
	{
		* (i._ZNK13NrvAppearStep17AppearStepNrvWait7executeEPN2al11NerveKeeperE)
	}
}
_ZNK13NrvAppearStep16AppearStepNrvEnd7executeEPN2al11NerveKeeperE 0x00350838
{
	_ZNK13NrvAppearStep16AppearStepNrvEnd7executeEPN2al11NerveKeeperE 0x00350838
	{
		* (i._ZNK13NrvAppearStep16AppearStepNrvEnd7executeEPN2al11NerveKeeperE)
	}
}
_ZNK13NrvAppearStep19AppearStepNrvAppear7executeEPN2al11NerveKeeperE 0x00350870
{
	_ZNK13NrvAppearStep19AppearStepNrvAppear7executeEPN2al11NerveKeeperE 0x00350870
	{
		* (i._ZNK13NrvAppearStep19AppearStepNrvAppear7executeEPN2al11NerveKeeperE)
	}
}
_ZNK13NrvAppearStep22AppearStepNrvDisappear7executeEPN2al11NerveKeeperE 0x003508c4
{
	_ZNK13NrvAppearStep22AppearStepNrvDisappear7executeEPN2al11NerveKeeperE 0x003508c4
	{
		* (i._ZNK13NrvAppearStep22AppearStepNrvDisappear7executeEPN2al11NerveKeeperE)
	}
}
_ZNK13NrvFugumannen18FugumannenNrvMove27executeEPN2al11NerveKeeperE 0x003510b0
{
	_ZNK13NrvFugumannen18FugumannenNrvMove27executeEPN2al11NerveKeeperE 0x003510b0
	{
		* (i._ZNK13NrvFugumannen18FugumannenNrvMove27executeEPN2al11NerveKeeperE)
	}
}
_ZNK13NrvFugumannen21FugumannenNrvBlowDown7executeEPN2al11NerveKeeperE 0x0035113c
{
	_ZNK13NrvFugumannen21FugumannenNrvBlowDown7executeEPN2al11NerveKeeperE 0x0035113c
	{
		* (i._ZNK13NrvFugumannen21FugumannenNrvBlowDown7executeEPN2al11NerveKeeperE)
	}
}
_ZNK13NrvFugumannen17FugumannenNrvMove7executeEPN2al11NerveKeeperE 0x00351178
{
	_ZNK13NrvFugumannen17FugumannenNrvMove7executeEPN2al11NerveKeeperE 0x00351178
	{
		* (i._ZNK13NrvFugumannen17FugumannenNrvMove7executeEPN2al11NerveKeeperE)
	}
}
_ZNK13NrvRailDotEnd17RailDotEndNrvWait7executeEPN2al11NerveKeeperE 0x0035308c
{
	_ZNK13NrvRailDotEnd17RailDotEndNrvWait7executeEPN2al11NerveKeeperE 0x0035308c
	{
		* (i._ZNK13NrvRailDotEnd17RailDotEndNrvWait7executeEPN2al11NerveKeeperE)
	}
}
_ZNK2al15NrvFallMapParts18FallMapPartsNrvEnd7executeEPNS_11NerveKeeperE 0x00357990
{
	_ZNK2al15NrvFallMapParts18FallMapPartsNrvEnd7executeEPNS_11NerveKeeperE 0x00357990
	{
		* (i._ZNK2al15NrvFallMapParts18FallMapPartsNrvEnd7executeEPNS_11NerveKeeperE)
	}
}
_ZNK2al15NrvFallMapParts19FallMapPartsNrvFall7executeEPNS_11NerveKeeperE 0x00357a24
{
	_ZNK2al15NrvFallMapParts19FallMapPartsNrvFall7executeEPNS_11NerveKeeperE 0x00357a24
	{
		* (i._ZNK2al15NrvFallMapParts19FallMapPartsNrvFall7executeEPNS_11NerveKeeperE)
	}
}
_ZNK2al15NrvFallMapParts19FallMapPartsNrvWait7executeEPNS_11NerveKeeperE 0x00357ad8
{
	_ZNK2al15NrvFallMapParts19FallMapPartsNrvWait7executeEPNS_11NerveKeeperE 0x00357ad8
	{
		* (i._ZNK2al15NrvFallMapParts19FallMapPartsNrvWait7executeEPNS_11NerveKeeperE)
	}
}
_ZNK2al15NrvFallMapParts21FallMapPartsNrvAppear7executeEPNS_11NerveKeeperE 0x00357b10
{
	_ZNK2al15NrvFallMapParts21FallMapPartsNrvAppear7executeEPNS_11NerveKeeperE 0x00357b10
	{
		* (i._ZNK2al15NrvFallMapParts21FallMapPartsNrvAppear7executeEPNS_11NerveKeeperE)
	}
}
_ZNK2al13NrvBreakModel17BreakModelNrvWait7executeEPNS_11NerveKeeperE 0x0035a064
{
	_ZNK2al13NrvBreakModel17BreakModelNrvWait7executeEPNS_11NerveKeeperE 0x0035a064
	{
		* (i._ZNK2al13NrvBreakModel17BreakModelNrvWait7executeEPNS_11NerveKeeperE)
	}
}
_ZNK2al13NrvBreakModel18BreakModelNrvBreak7executeEPNS_11NerveKeeperE 0x0035a068
{
	_ZNK2al13NrvBreakModel18BreakModelNrvBreak7executeEPNS_11NerveKeeperE 0x0035a068
	{
		* (i._ZNK2al13NrvBreakModel18BreakModelNrvBreak7executeEPNS_11NerveKeeperE)
	}
}
_ZNK2al13NrvWipeSimple18WipeSimpleNrvClose7executeEPNS_11NerveKeeperE 0x0035a11c
{
	_ZNK2al13NrvWipeSimple18WipeSimpleNrvClose7executeEPNS_11NerveKeeperE 0x0035a11c
	{
		* (i._ZNK2al13NrvWipeSimple18WipeSimpleNrvClose7executeEPNS_11NerveKeeperE)
	}
}
_ZNK2al13NrvWipeSimple17WipeSimpleNrvWait7executeEPNS_11NerveKeeperE 0x0035a15c
{
	_ZNK2al13NrvWipeSimple17WipeSimpleNrvWait7executeEPNS_11NerveKeeperE 0x0035a15c
	{
		* (i._ZNK2al13NrvWipeSimple17WipeSimpleNrvWait7executeEPNS_11NerveKeeperE)
	}
}
_ZNK17NrvTrickHintPanel21TrickHintPanelNrvWait7executeEPN2al11NerveKeeperE 0x0035dd7c
{
	_ZNK17NrvTrickHintPanel21TrickHintPanelNrvWait7executeEPN2al11NerveKeeperE 0x0035dd7c
	{
		* (i._ZNK17NrvTrickHintPanel21TrickHintPanelNrvWait7executeEPN2al11NerveKeeperE)
	}
}
_ZNK17NrvTrickHintPanel19TrickHintPanelNrvOn7executeEPN2al11NerveKeeperE 0x0035dd80
{
	_ZNK17NrvTrickHintPanel19TrickHintPanelNrvOn7executeEPN2al11NerveKeeperE 0x0035dd80
	{
		* (i._ZNK17NrvTrickHintPanel19TrickHintPanelNrvOn7executeEPN2al11NerveKeeperE)
	}
}
_ZNK17NrvTrickHintPanel21TrickHintPanelNrvnrv37executeEPN2al11NerveKeeperE 0x0035dde0
{
	_ZNK17NrvTrickHintPanel21TrickHintPanelNrvnrv37executeEPN2al11NerveKeeperE 0x0035dde0
	{
		* (i._ZNK17NrvTrickHintPanel21TrickHintPanelNrvnrv37executeEPN2al11NerveKeeperE)
	}
}
_ZNK17NrvTrickHintPanel20TrickHintPanelNrvOff7executeEPN2al11NerveKeeperE 0x0035de20
{
	_ZNK17NrvTrickHintPanel20TrickHintPanelNrvOff7executeEPN2al11NerveKeeperE 0x0035de20
	{
		* (i._ZNK17NrvTrickHintPanel20TrickHintPanelNrvOff7executeEPN2al11NerveKeeperE)
	}
}
_ZNK18NrvProductSequence23ProductSequenceNrvTitle7executeEPN2al11NerveKeeperE 0x003602d8
{
	_ZNK18NrvProductSequence23ProductSequenceNrvTitle7executeEPN2al11NerveKeeperE 0x003602d8
	{
		* (i._ZNK18NrvProductSequence23ProductSequenceNrvTitle7executeEPN2al11NerveKeeperE)
	}
}
_ZNK18NrvProductSequence24ProductSequenceNrvEnding7executeEPN2al11NerveKeeperE 0x00360330
{
	_ZNK18NrvProductSequence24ProductSequenceNrvEnding7executeEPN2al11NerveKeeperE 0x00360330
	{
		* (i._ZNK18NrvProductSequence24ProductSequenceNrvEnding7executeEPN2al11NerveKeeperE)
	}
}
_ZNK18NrvProductSequence25ProductSequenceNrvOpening7executeEPN2al11NerveKeeperE 0x00360380
{
	_ZNK18NrvProductSequence25ProductSequenceNrvOpening7executeEPN2al11NerveKeeperE 0x00360380
	{
		* (i._ZNK18NrvProductSequence25ProductSequenceNrvOpening7executeEPN2al11NerveKeeperE)
	}
}
_ZNK18NrvProductSequence30ProductSequenceNrvKinopioHouse7executeEPN2al11NerveKeeperE 0x003604e4
{
	_ZNK18NrvProductSequence30ProductSequenceNrvKinopioHouse7executeEPN2al11NerveKeeperE 0x003604e4
	{
		* (i._ZNK18NrvProductSequence30ProductSequenceNrvKinopioHouse7executeEPN2al11NerveKeeperE)
	}
}
_ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvMove7getNameEv 0x0036416c
{
	_ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvMove7getNameEv 0x0036416c
	{
		* (i._ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvMove7getNameEv)
	}
}
_ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvWait7getNameEv 0x0036417c
{
	_ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvWait7getNameEv 0x0036417c
	{
		* (i._ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvWait7getNameEv)
	}
}
_ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvWait7executeEPN2al11NerveKeeperE 0x0036418c
{
	_ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvWait7executeEPN2al11NerveKeeperE 0x0036418c
	{
		* (i._ZNK19NrvNoteObjGenerator23NoteObjGeneratorNrvWait7executeEPN2al11NerveKeeperE)
	}
}
_ZNK19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccess7getNameEv 0x003641f4
{
	_ZNK19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccess7getNameEv 0x003641f4
	{
		* (i._ZNK19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccess7getNameEv)
	}
}
_ZNK19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccess7executeEPN2al11NerveKeeperE 0x00364204
{
	_ZNK19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccess7executeEPN2al11NerveKeeperE 0x00364204
	{
		* (i._ZNK19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccess7executeEPN2al11NerveKeeperE)
	}
}
_ZNK19NrvNoteObjGenerator28NoteObjGeneratorNrvDisappear7getNameEv 0x00364238
{
	_ZNK19NrvNoteObjGenerator28NoteObjGeneratorNrvDisappear7getNameEv 0x00364238
	{
		* (i._ZNK19NrvNoteObjGenerator28NoteObjGeneratorNrvDisappear7getNameEv)
	}
}
_ZNK21NrvAquariumSwimDebris27AquariumSwimDebrisNrvAppear7executeEPN2al11NerveKeeperE 0x00367ec8
{
	_ZNK21NrvAquariumSwimDebris27AquariumSwimDebrisNrvAppear7executeEPN2al11NerveKeeperE 0x00367ec8
	{
		* (i._ZNK21NrvAquariumSwimDebris27AquariumSwimDebrisNrvAppear7executeEPN2al11NerveKeeperE)
	}
}
_ZNK2al19NrvRailMoveMovement23RailMoveMovementNrvMove7executeEPNS_11NerveKeeperE 0x00369744
{
	_ZNK2al19NrvRailMoveMovement23RailMoveMovementNrvMove7executeEPNS_11NerveKeeperE 0x00369744
	{
		* (i._ZNK2al19NrvRailMoveMovement23RailMoveMovementNrvMove7executeEPNS_11NerveKeeperE)
	}
}
_ZNK2al8Sequence12isDisposableEv 0x00375754
{
	_ZNK2al8Sequence12isDisposableEv 0x00375754
	{
		* (i._ZNK2al8Sequence12isDisposableEv)
	}
}
_ZN2al8Sequence4unk5Ev 0x00375a4c
{
	_ZN2al8Sequence4unk5Ev 0x00375a4c
	{
		* (i._ZN2al8Sequence4unk5Ev)
	}
}
_ZN2al8Sequence4unk4Ev 0x00375a64
{
	_ZN2al8Sequence4unk4Ev 0x00375a64
	{
		* (i._ZN2al8Sequence4unk4Ev)
	}
}
_ZNK2al9EffectObj10getBaseMtxEv 0x00375b38
{
	_ZNK2al9EffectObj10getBaseMtxEv 0x00375b38
	{
		* (i._ZNK2al9EffectObj10getBaseMtxEv)
	}
}
_ZThn12_N2al9LiveActor21initStageSwitchKeeperEv 0x00375e4c
{
	_ZThn12_N2al9LiveActor21initStageSwitchKeeperEv 0x00375e4c
	{
		* (i._ZThn12_N2al9LiveActor21initStageSwitchKeeperEv)
	}
}
_ZThn12_NK2al9LiveActor20getStageSwitchKeeperEv 0x00375f28
{
	_ZThn12_NK2al9LiveActor20getStageSwitchKeeperEv 0x00375f28
	{
		* (i._ZThn12_NK2al9LiveActor20getStageSwitchKeeperEv)
	}
}
_ZThn4_NK2al11LayoutActor14getAudioKeeperEv 0x003765a0
{
	_ZThn4_NK2al11LayoutActor14getAudioKeeperEv 0x003765a0
	{
		* (i._ZThn4_NK2al11LayoutActor14getAudioKeeperEv)
	}
}
_ZThn8_NK2al11LayoutActor15getEffectKeeperEv 0x00376a3c
{
	_ZThn8_NK2al11LayoutActor15getEffectKeeperEv 0x00376a3c
	{
		* (i._ZThn8_NK2al11LayoutActor15getEffectKeeperEv)
	}
}
_ZThn8_NK2al9LiveActor14getAudioKeeperEv 0x00376a44
{
	_ZThn8_NK2al9LiveActor14getAudioKeeperEv 0x00376a44
	{
		* (i._ZThn8_NK2al9LiveActor14getAudioKeeperEv)
	}
}
_ZThn96_N11CoinRotater26initAfterPlacementSceneObjERKN2al13ActorInitInfoE 0x00376bc4
{
	_ZThn96_N11CoinRotater26initAfterPlacementSceneObjERKN2al13ActorInitInfoE 0x00376bc4
	{
		* (i._ZThn96_N11CoinRotater26initAfterPlacementSceneObjERKN2al13ActorInitInfoE)
	}
}
__sti___11_RailDot_cpp 0x0038093c
{
	__sti___11_RailDot_cpp 0x0038093c
	{
		* (i.__sti___11_RailDot_cpp)
	}
}
__sti___12_FireBall_cpp 0x00380d6c
{
	__sti___12_FireBall_cpp 0x00380d6c
	{
		* (i.__sti___12_FireBall_cpp)
	}
}
__sti___13_FlowerPot_cpp 0x00381514
{
	__sti___13_FlowerPot_cpp 0x00381514
	{
		* (i.__sti___13_FlowerPot_cpp)
	}
}
__sti___14_AppearStep_cpp 0x0038211c
{
	__sti___14_AppearStep_cpp 0x0038211c
	{
		* (i.__sti___14_AppearStep_cpp)
	}
}
__sti___14_Fugumannen_cpp 0x00382410
{
	__sti___14_Fugumannen_cpp 0x00382410
	{
		* (i.__sti___14_Fugumannen_cpp)
	}
}
__sti___14_RailDotEnd_cpp 0x00382a94
{
	__sti___14_RailDotEnd_cpp 0x00382a94
	{
		* (i.__sti___14_RailDotEnd_cpp)
	}
}
__sti___16_FallMapParts_cpp 0x00384f8c
{
	__sti___16_FallMapParts_cpp 0x00384f8c
	{
		* (i.__sti___16_FallMapParts_cpp)
	}
}
__sti___14_BreakModel_cpp 0x003857e4
{
	__sti___14_BreakModel_cpp 0x003857e4
	{
		* (i.__sti___14_BreakModel_cpp)
	}
}
__sti___14_WipeSimple_cpp 0x00385844
{
	__sti___14_WipeSimple_cpp 0x00385844
	{
		* (i.__sti___14_WipeSimple_cpp)
	}
}
__sti___18_TrickHintPanel_cpp 0x00386bdc
{
	__sti___18_TrickHintPanel_cpp 0x00386bdc
	{
		* (i.__sti___18_TrickHintPanel_cpp)
	}
}
__sti___19_ActorPoseKeeper_cpp 0x0038a12c
{
	__sti___19_ActorPoseKeeper_cpp 0x0038a12c
	{
		* (i.__sti___19_ActorPoseKeeper_cpp)
	}
}
__sti___22_AquariumSwimDebris_cpp 0x0038a440
{
	__sti___22_AquariumSwimDebris_cpp 0x0038a440
	{
		* (i.__sti___22_AquariumSwimDebris_cpp)
	}
}
_ZN2al19createActorFunctionINS_12FallMapPartsEEEPNS_9LiveActorEPKc 0x0039674c
{
	_ZN2al19createActorFunctionINS_12FallMapPartsEEEPNS_9LiveActorEPKc 0x0039674c
	{
		* (t._ZN2al19createActorFunctionINS_12FallMapPartsEEEPNS_9LiveActorEPKc)
	}
}
_ZN2al19createActorFunctionI16NoteObjGeneratorEEPNS_9LiveActorEPKc 0x003975c4
{
	_ZN2al19createActorFunctionI16NoteObjGeneratorEEPNS_9LiveActorEPKc 0x003975c4
	{
		* (t._ZN2al19createActorFunctionI16NoteObjGeneratorEEPNS_9LiveActorEPKc)
	}
}
_ZN2al19createActorFunctionINS_3SkyEEEPNS_9LiveActorEPKc 0x00397e64
{
	_ZN2al19createActorFunctionINS_3SkyEEEPNS_9LiveActorEPKc 0x00397e64
	{
		* (t._ZN2al19createActorFunctionINS_3SkyEEEPNS_9LiveActorEPKc)
	}
}
_ZN2al19createActorFunctionI6TogezoEEPNS_9LiveActorEPKc 0x0039842c
{
	_ZN2al19createActorFunctionI6TogezoEEPNS_9LiveActorEPKc 0x0039842c
	{
		* (t._ZN2al19createActorFunctionI6TogezoEEPNS_9LiveActorEPKc)
	}
}
_ZN2al19createActorFunctionI7NoteObjEEPNS_9LiveActorEPKc 0x0039865c
{
	_ZN2al19createActorFunctionI7NoteObjEEPNS_9LiveActorEPKc 0x0039865c
	{
		* (t._ZN2al19createActorFunctionI7NoteObjEEPNS_9LiveActorEPKc)
	}
}
_ZN2al19createActorFunctionINS_9EffectObjEEEPNS_9LiveActorEPKc 0x00398a74
{
	_ZN2al19createActorFunctionINS_9EffectObjEEEPNS_9LiveActorEPKc 0x00398a74
	{
		* (t._ZN2al19createActorFunctionINS_9EffectObjEEEPNS_9LiveActorEPKc)
	}
}
_ZN2al21createAreaObjFunctionINS_7AreaObjEEEPS1_PKc 0x00398f44
{
	_ZN2al21createAreaObjFunctionINS_7AreaObjEEEPS1_PKc 0x00398f44
	{
		* (t._ZN2al21createAreaObjFunctionINS_7AreaObjEEEPS1_PKc)
	}
}
_ZNK2al10FunctorV0MIP10AppearStepMS1_FvvEEclEv 0x0039b33c
{
	_ZNK2al10FunctorV0MIP10AppearStepMS1_FvvEEclEv 0x0039b33c
	{
		* (t._ZNK2al10FunctorV0MIP10AppearStepMS1_FvvEEclEv)
	}
}
__cpp_initialize__aeabi_ 0x003a0da4
{
	__cpp_initialize__aeabi_ 0x003a0da4
	{
		* (:gdef:__cpp_initialize__aeabi_)
	}
}



.constdata__ZTV9PeachRope 0x00305254
{
	.constdata__ZTV9PeachRope 0x00305254
	{
		* (.constdata__ZTV9PeachRope)
	}
}
i.sUpdateExecuteOrder 0x003a8fa4
{
	i.sUpdateExecuteOrder 0x003a8fa4
	{
		* (i.sUpdateExecuteOrder)
	}
}
i.sDraw0ExecuteOrder 0x003a9344
{
	i.sDraw0ExecuteOrder 0x003a9344
	{
		* (i.sDraw0ExecuteOrder)
	}
}
i.sDraw2ExecuteOrder 0x003a9384
{
	i.sDraw2ExecuteOrder 0x003a9384
	{
		* (i.sDraw2ExecuteOrder)
	}
}
i.sDraw3ExecuteOrder 0x003a93a4
{
	i.sDraw3ExecuteOrder 0x003a93a4
	{
		* (i.sDraw3ExecuteOrder)
	}
}
i.sDraw4ExecuteOrder 0x003a95a4
{
	i.sDraw4ExecuteOrder 0x003a95a4
	{
		* (i.sDraw4ExecuteOrder)
	}
}
i.sDraw1ExecuteOrder 0x003a95b4
{
	i.sDraw1ExecuteOrder 0x003a95b4
	{
		* (i.sDraw1ExecuteOrder)
	}
}
i.sDraw5ExecuteOrder 0x003a95c4
{
	i.sDraw5ExecuteOrder 0x003a95c4
	{
		* (i.sDraw5ExecuteOrder)
	}
}
i.sDraw6ExecuteOrder 0x003a9614
{
	i.sDraw6ExecuteOrder 0x003a9614
	{
		* (i.sDraw6ExecuteOrder)
	}
}
i.sDraw7ExecuteOrder 0x003a96b4
{
	i.sDraw7ExecuteOrder 0x003a96b4
	{
		* (i.sDraw7ExecuteOrder)
	}
}
i.sDraw9ExecuteOrder 0x003a96d4
{
	i.sDraw9ExecuteOrder 0x003a96d4
	{
		* (i.sDraw9ExecuteOrder)
	}
}
i.sDraw8ExecuteOrder 0x003a9764
{
	i.sDraw8ExecuteOrder 0x003a9764
	{
		* (i.sDraw8ExecuteOrder)
	}
}
.constdata__ZTVN2al13NrvWipeSimple18WipeSimpleNrvCloseE 0x003aebdc
{
	.constdata__ZTVN2al13NrvWipeSimple18WipeSimpleNrvCloseE 0x003aebdc
	{
		* (.constdata__ZTVN2al13NrvWipeSimple18WipeSimpleNrvCloseE)
	}
}
.constdata__ZTVN2al13NrvWipeSimple17WipeSimpleNrvWaitE 0x003aebec
{
	.constdata__ZTVN2al13NrvWipeSimple17WipeSimpleNrvWaitE 0x003aebec
	{
		* (.constdata__ZTVN2al13NrvWipeSimple17WipeSimpleNrvWaitE)
	}
}
.constdata__ZTVN2al13NrvWipeSimple17WipeSimpleNrvOpenE 0x003aebfc
{
	.constdata__ZTVN2al13NrvWipeSimple17WipeSimpleNrvOpenE 0x003aebfc
	{
		* (.constdata__ZTVN2al13NrvWipeSimple17WipeSimpleNrvOpenE)
	}
}
.constdata__ZTVN14NrvGhostPlayer19GhostPlayerNrvBeginE 0x003b1214
{
	.constdata__ZTVN14NrvGhostPlayer19GhostPlayerNrvBeginE 0x003b1214
	{
		* (.constdata__ZTVN14NrvGhostPlayer19GhostPlayerNrvBeginE)
	}
}
.constdata__ZTVN14NrvGhostPlayer18GhostPlayerNrvNrv5E 0x003b1244
{
	.constdata__ZTVN14NrvGhostPlayer18GhostPlayerNrvNrv5E 0x003b1244
	{
		* (.constdata__ZTVN14NrvGhostPlayer18GhostPlayerNrvNrv5E)
	}
}
.constdata__ZTVN2al13NrvBreakModel17BreakModelNrvWaitE 0x003b2abc
{
	.constdata__ZTVN2al13NrvBreakModel17BreakModelNrvWaitE 0x003b2abc
	{
		* (.constdata__ZTVN2al13NrvBreakModel17BreakModelNrvWaitE)
	}
}
.constdata__ZTVN2al13NrvBreakModel18BreakModelNrvBreakE 0x003b2acc
{
	.constdata__ZTVN2al13NrvBreakModel18BreakModelNrvBreakE 0x003b2acc
	{
		* (.constdata__ZTVN2al13NrvBreakModel18BreakModelNrvBreakE)
	}
}
i.sAreaObjFactoryEntries 0x003b896c
{
	i.sAreaObjFactoryEntries 0x003b896c
	{
		* (i.sAreaObjFactoryEntries)
	}
}
i.sActorFactoryEntries 0x003b99f0
{
	i.sActorFactoryEntries 0x003b99f0
	{
		* (i.sActorFactoryEntries)
	}
}
.constdata__ZTVN13NrvFugumannen17FugumannenNrvMoveE 0x003bad40
{
	.constdata__ZTVN13NrvFugumannen17FugumannenNrvMoveE 0x003bad40
	{
		* (.constdata__ZTVN13NrvFugumannen17FugumannenNrvMoveE)
	}
}
.constdata__ZTVN13NrvFugumannen18FugumannenNrvMove2E 0x003bad50
{
	.constdata__ZTVN13NrvFugumannen18FugumannenNrvMove2E 0x003bad50
	{
		* (.constdata__ZTVN13NrvFugumannen18FugumannenNrvMove2E)
	}
}
.constdata__ZTVN13NrvFugumannen21FugumannenNrvBlowDownE 0x003bad60
{
	.constdata__ZTVN13NrvFugumannen21FugumannenNrvBlowDownE 0x003bad60
	{
		* (.constdata__ZTVN13NrvFugumannen21FugumannenNrvBlowDownE)
	}
}
.constdata__ZTVN9NrvTogezo15TogezoNrvWanderE 0x003bc970
{
	.constdata__ZTVN9NrvTogezo15TogezoNrvWanderE 0x003bc970
	{
		* (.constdata__ZTVN9NrvTogezo15TogezoNrvWanderE)
	}
}
.constdata__ZTVN9NrvTogezo13TogezoNrvTurnE 0x003bc980
{
	.constdata__ZTVN9NrvTogezo13TogezoNrvTurnE 0x003bc980
	{
		* (.constdata__ZTVN9NrvTogezo13TogezoNrvTurnE)
	}
}
.constdata__ZTVN9NrvTogezo15TogezoNrvSearchE 0x003bc990
{
	.constdata__ZTVN9NrvTogezo15TogezoNrvSearchE 0x003bc990
	{
		* (.constdata__ZTVN9NrvTogezo15TogezoNrvSearchE)
	}
}
.constdata__ZTVN9NrvTogezo14TogezoNrvChaseE 0x003bc9a0
{
	.constdata__ZTVN9NrvTogezo14TogezoNrvChaseE 0x003bc9a0
	{
		* (.constdata__ZTVN9NrvTogezo14TogezoNrvChaseE)
	}
}
.constdata__ZTVN9NrvTogezo15TogezoNrvAttackE 0x003bc9b0
{
	.constdata__ZTVN9NrvTogezo15TogezoNrvAttackE 0x003bc9b0
	{
		* (.constdata__ZTVN9NrvTogezo15TogezoNrvAttackE)
	}
}
.constdata__ZTVN9NrvTogezo17TogezoNrvBlowDownE 0x003bc9c0
{
	.constdata__ZTVN9NrvTogezo17TogezoNrvBlowDownE 0x003bc9c0
	{
		* (.constdata__ZTVN9NrvTogezo17TogezoNrvBlowDownE)
	}
}
.constdata__ZTVN13NrvAppearStep19AppearStepNrvAppearE 0x003bcdbc
{
	.constdata__ZTVN13NrvAppearStep19AppearStepNrvAppearE 0x003bcdbc
	{
		* (.constdata__ZTVN13NrvAppearStep19AppearStepNrvAppearE)
	}
}
.constdata__ZTVN13NrvAppearStep17AppearStepNrvWaitE 0x003bcdcc
{
	.constdata__ZTVN13NrvAppearStep17AppearStepNrvWaitE 0x003bcdcc
	{
		* (.constdata__ZTVN13NrvAppearStep17AppearStepNrvWaitE)
	}
}
.constdata__ZTVN13NrvAppearStep22AppearStepNrvDisappearE 0x003bcddc
{
	.constdata__ZTVN13NrvAppearStep22AppearStepNrvDisappearE 0x003bcddc
	{
		* (.constdata__ZTVN13NrvAppearStep22AppearStepNrvDisappearE)
	}
}
.constdata__ZTVN13NrvAppearStep16AppearStepNrvEndE 0x003bcdec
{
	.constdata__ZTVN13NrvAppearStep16AppearStepNrvEndE 0x003bcdec
	{
		* (.constdata__ZTVN13NrvAppearStep16AppearStepNrvEndE)
	}
}
.constdata__ZTVN21NrvAquariumSwimDebris27AquariumSwimDebrisNrvAppearE 0x003bce04
{
	.constdata__ZTVN21NrvAquariumSwimDebris27AquariumSwimDebrisNrvAppearE 0x003bce04
	{
		* (.constdata__ZTVN21NrvAquariumSwimDebris27AquariumSwimDebrisNrvAppearE)
	}
}
.constdata__ZTVN2al15NrvFallMapParts21FallMapPartsNrvAppearE 0x003bda10
{
	.constdata__ZTVN2al15NrvFallMapParts21FallMapPartsNrvAppearE 0x003bda10
	{
		* (.constdata__ZTVN2al15NrvFallMapParts21FallMapPartsNrvAppearE)
	}
}
.constdata__ZTVN2al15NrvFallMapParts19FallMapPartsNrvWaitE 0x003bda20
{
	.constdata__ZTVN2al15NrvFallMapParts19FallMapPartsNrvWaitE 0x003bda20
	{
		* (.constdata__ZTVN2al15NrvFallMapParts19FallMapPartsNrvWaitE)
	}
}
.constdata__ZTVN2al15NrvFallMapParts23FallMapPartsNrvFallSignE 0x003bda30
{
	.constdata__ZTVN2al15NrvFallMapParts23FallMapPartsNrvFallSignE 0x003bda30
	{
		* (.constdata__ZTVN2al15NrvFallMapParts23FallMapPartsNrvFallSignE)
	}
}
.constdata__ZTVN2al15NrvFallMapParts19FallMapPartsNrvFallE 0x003bda40
{
	.constdata__ZTVN2al15NrvFallMapParts19FallMapPartsNrvFallE 0x003bda40
	{
		* (.constdata__ZTVN2al15NrvFallMapParts19FallMapPartsNrvFallE)
	}
}
.constdata__ZTVN2al15NrvFallMapParts18FallMapPartsNrvEndE 0x003bda50
{
	.constdata__ZTVN2al15NrvFallMapParts18FallMapPartsNrvEndE 0x003bda50
	{
		* (.constdata__ZTVN2al15NrvFallMapParts18FallMapPartsNrvEndE)
	}
}
.constdata__ZTVN19NrvNoteObjGenerator23NoteObjGeneratorNrvWaitE 0x003beb3c
{
	.constdata__ZTVN19NrvNoteObjGenerator23NoteObjGeneratorNrvWaitE 0x003beb3c
	{
		* (.constdata__ZTVN19NrvNoteObjGenerator23NoteObjGeneratorNrvWaitE)
	}
}
.constdata__ZTVN19NrvNoteObjGenerator23NoteObjGeneratorNrvMoveE 0x003beb50
{
	.constdata__ZTVN19NrvNoteObjGenerator23NoteObjGeneratorNrvMoveE 0x003beb50
	{
		* (.constdata__ZTVN19NrvNoteObjGenerator23NoteObjGeneratorNrvMoveE)
	}
}
.constdata__ZTVN19NrvNoteObjGenerator28NoteObjGeneratorNrvDisappearE 0x003beb64
{
	.constdata__ZTVN19NrvNoteObjGenerator28NoteObjGeneratorNrvDisappearE 0x003beb64
	{
		* (.constdata__ZTVN19NrvNoteObjGenerator28NoteObjGeneratorNrvDisappearE)
	}
}
.constdata__ZTVN19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccessE 0x003beb78
{
	.constdata__ZTVN19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccessE 0x003beb78
	{
		* (.constdata__ZTVN19NrvNoteObjGenerator26NoteObjGeneratorNrvSuccessE)
	}
}
.constdata__ZTVN17NrvTrickHintPanel21TrickHintPanelNrvWaitE 0x003bf900
{
	.constdata__ZTVN17NrvTrickHintPanel21TrickHintPanelNrvWaitE 0x003bf900
	{
		* (.constdata__ZTVN17NrvTrickHintPanel21TrickHintPanelNrvWaitE)
	}
}
.constdata__ZTVN17NrvTrickHintPanel19TrickHintPanelNrvOnE 0x003bf910
{
	.constdata__ZTVN17NrvTrickHintPanel19TrickHintPanelNrvOnE 0x003bf910
	{
		* (.constdata__ZTVN17NrvTrickHintPanel19TrickHintPanelNrvOnE)
	}
}
.constdata__ZTVN17NrvTrickHintPanel21TrickHintPanelNrvnrv3E 0x003bf920
{
	.constdata__ZTVN17NrvTrickHintPanel21TrickHintPanelNrvnrv3E 0x003bf920
	{
		* (.constdata__ZTVN17NrvTrickHintPanel21TrickHintPanelNrvnrv3E)
	}
}
.constdata__ZTVN17NrvTrickHintPanel20TrickHintPanelNrvOffE 0x003bf930
{
	.constdata__ZTVN17NrvTrickHintPanel20TrickHintPanelNrvOffE 0x003bf930
	{
		* (.constdata__ZTVN17NrvTrickHintPanel20TrickHintPanelNrvOffE)
	}
}
.constdata__ZTVN2al19NrvRailMoveMovement23RailMoveMovementNrvMoveE 0x003c0190
{
	.constdata__ZTVN2al19NrvRailMoveMovement23RailMoveMovementNrvMoveE 0x003c0190
	{
		* (.constdata__ZTVN2al19NrvRailMoveMovement23RailMoveMovementNrvMoveE)
	}
}
.constdata__ZTVN11NrvFireBall15FireBallNrvShotE 0x003c082c
{
	.constdata__ZTVN11NrvFireBall15FireBallNrvShotE 0x003c082c
	{
		* (.constdata__ZTVN11NrvFireBall15FireBallNrvShotE)
	}
}
.constdata__ZTVN12NrvFlowerPot16FlowerPotNrvWaitE 0x003c10d4
{
	.constdata__ZTVN12NrvFlowerPot16FlowerPotNrvWaitE 0x003c10d4
	{
		* (.constdata__ZTVN12NrvFlowerPot16FlowerPotNrvWaitE)
	}
}
.constdata__ZTVN10NrvRailDot14RailDotNrvWaitE 0x003c11a0
{
	.constdata__ZTVN10NrvRailDot14RailDotNrvWaitE 0x003c11a0
	{
		* (.constdata__ZTVN10NrvRailDot14RailDotNrvWaitE)
	}
}
.constdata__ZTVN13NrvRailDotEnd17RailDotEndNrvWaitE 0x003c11b0
{
	.constdata__ZTVN13NrvRailDotEnd17RailDotEndNrvWaitE 0x003c11b0
	{
		* (.constdata__ZTVN13NrvRailDotEnd17RailDotEndNrvWaitE)
	}
}
.constdata__ZTV10AppearStep 0x003c4178
{
	.constdata__ZTV10AppearStep 0x003c4178
	{
		* (.constdata__ZTV10AppearStep)
	}
}
.constdata__ZTV10Fugumannen 0x003c4708
{
	.constdata__ZTV10Fugumannen 0x003c4708
	{
		* (.constdata__ZTV10Fugumannen)
	}
}
.constdata__ZTV10GameSystem 0x003c47a0
{
	.constdata__ZTV10GameSystem 0x003c47a0
	{
		* (.constdata__ZTV10GameSystem)
	}
}
.constdata__ZTV10RailDotEnd 0x003c5060
{
	.constdata__ZTV10RailDotEnd 0x003c5060
	{
		* (.constdata__ZTV10RailDotEnd)
	}
}
.constdata__ZTVN2al6CameraE 0x003c5988
{
	.constdata__ZTVN2al6CameraE 0x003c5988
	{
		* (.constdata__ZTVN2al6CameraE)
	}
}
.constdata__ZTV11CoinRotater 0x003c5c2c
{
	.constdata__ZTV11CoinRotater 0x003c5c2c
	{
		* (.constdata__ZTV11CoinRotater)
	}
}
.constdata__ZTV11GhostPlayer 0x003c6038
{
	.constdata__ZTV11GhostPlayer 0x003c6038
	{
		* (.constdata__ZTV11GhostPlayer)
	}
}
.constdata__ZTVN2al11MapObjActorE 0x003c76f4
{
	.constdata__ZTVN2al11MapObjActorE 0x003c76f4
	{
		* (.constdata__ZTVN2al11MapObjActorE)
	}
}
.constdata__ZTV14PlayerAnimator 0x003c91a0
{
	.constdata__ZTV14PlayerAnimator 0x003c91a0
	{
		* (.constdata__ZTV14PlayerAnimator)
	}
}
.constdata__ZTV14TrickHintPanel 0x003c980c
{
	.constdata__ZTV14TrickHintPanel 0x003c980c
	{
		* (.constdata__ZTV14TrickHintPanel)
	}
}
.constdata__ZTV15TransparentWall 0x003cb64c
{
	.constdata__ZTV15TransparentWall 0x003cb64c
	{
		* (.constdata__ZTV15TransparentWall)
	}
}
.constdata__ZTV16NoteObjGenerator 0x003cc1f4
{
	.constdata__ZTV16NoteObjGenerator 0x003cc1f4
	{
		* (.constdata__ZTV16NoteObjGenerator)
	}
}
.constdata__ZTV17ProductStateTitle 0x003cda4c
{
	.constdata__ZTV17ProductStateTitle 0x003cda4c
	{
		* (.constdata__ZTV17ProductStateTitle)
	}
}
.constdata__ZTV18AquariumSwimDebris 0x003cde8c
{
	.constdata__ZTV18AquariumSwimDebris 0x003cde8c
	{
		* (.constdata__ZTV18AquariumSwimDebris)
	}
}
.constdata__ZTVN2al18SwitchAreaDirectorE 0x003ce368
{
	.constdata__ZTVN2al18SwitchAreaDirectorE 0x003ce368
	{
		* (.constdata__ZTVN2al18SwitchAreaDirectorE)
	}
}
.constdata__ZTV19GhostPlayerRecorder 0x003ce758
{
	.constdata__ZTV19GhostPlayerRecorder 0x003ce758
	{
		* (.constdata__ZTV19GhostPlayerRecorder)
	}
}
.constdata__ZTV26PlayerActionMultiCondition 0x003d10d4
{
	.constdata__ZTV26PlayerActionMultiCondition 0x003d10d4
	{
		* (.constdata__ZTV26PlayerActionMultiCondition)
	}
}
.constdata__ZTV28PlayerActionConditionAnimEnd 0x003d12c8
{
	.constdata__ZTV28PlayerActionConditionAnimEnd 0x003d12c8
	{
		* (.constdata__ZTV28PlayerActionConditionAnimEnd)
	}
}
.constdata__ZTVN2al3SkyE 0x003d1ddc
{
	.constdata__ZTVN2al3SkyE 0x003d1ddc
	{
		* (.constdata__ZTVN2al3SkyE)
	}
}
.constdata__ZTV6Togezo 0x003d3010
{
	.constdata__ZTV6Togezo 0x003d3010
	{
		* (.constdata__ZTV6Togezo)
	}
}
.constdata__ZTV7NoteObj 0x003d37c8
{
	.constdata__ZTV7NoteObj 0x003d37c8
	{
		* (.constdata__ZTV7NoteObj)
	}
}
.constdata__ZTV7RailDot 0x003d3998
{
	.constdata__ZTV7RailDot 0x003d3998
	{
		* (.constdata__ZTV7RailDot)
	}
}
.constdata__ZTV8FireBall 0x003d3dd8
{
	.constdata__ZTV8FireBall 0x003d3dd8
	{
		* (.constdata__ZTV8FireBall)
	}
}
.constdata__ZTVN2al9EffectObjE 0x003d49a4
{
	.constdata__ZTVN2al9EffectObjE 0x003d49a4
	{
		* (.constdata__ZTVN2al9EffectObjE)
	}
}
.constdata__ZTV9FlowerPot 0x003d4ad4
{
	.constdata__ZTV9FlowerPot 0x003d4ad4
	{
		* (.constdata__ZTV9FlowerPot)
	}
}
.constdata__ZTVN2al10BreakModelE 0x003d598c
{
	.constdata__ZTVN2al10BreakModelE 0x003d598c
	{
		* (.constdata__ZTVN2al10BreakModelE)
	}
}
.constdata__ZTVN2al10FunctorV0FE 0x003d5a24
{
	.constdata__ZTVN2al10FunctorV0FE 0x003d5a24
	{
		* (.constdata__ZTVN2al10FunctorV0FE)
	}
}
.constdata__ZTVN2al10FunctorV0MIP10AppearStepMS1_FvvEEE 0x003d5a34
{
	.constdata__ZTVN2al10FunctorV0MIP10AppearStepMS1_FvvEEE 0x003d5a34
	{
		* (.constdata__ZTVN2al10FunctorV0MIP10AppearStepMS1_FvvEEE)
	}
}
.constdata__ZTVN2al10WipeSimpleE 0x003d5f4c
{
	.constdata__ZTVN2al10WipeSimpleE 0x003d5f4c
	{
		* (.constdata__ZTVN2al10WipeSimpleE)
	}
}
.constdata__ZTVN2al13AreaShapeCubeE 0x003d62b8
{
	.constdata__ZTVN2al13AreaShapeCubeE 0x003d62b8
	{
		* (.constdata__ZTVN2al13AreaShapeCubeE)
	}
}
.constdata__ZTVN2al16RailMoveMovementE 0x003d68c4
{
	.constdata__ZTVN2al16RailMoveMovementE 0x003d68c4
	{
		* (.constdata__ZTVN2al16RailMoveMovementE)
	}
}
.constdata__ZTVN2al17HitSensorDirectorE 0x003d6918
{
	.constdata__ZTVN2al17HitSensorDirectorE 0x003d6918
	{
		* (.constdata__ZTVN2al17HitSensorDirectorE)
	}
}
.constdata__ZTVN2al19ActorPoseKeeperTFSVE 0x003d6df4
{
	.constdata__ZTVN2al19ActorPoseKeeperTFSVE 0x003d6df4
	{
		* (.constdata__ZTVN2al19ActorPoseKeeperTFSVE)
	}
}
.constdata__ZTVN2al19ActorPoseKeeperTQSVE 0x003d6e40
{
	.constdata__ZTVN2al19ActorPoseKeeperTQSVE 0x003d6e40
	{
		* (.constdata__ZTVN2al19ActorPoseKeeperTQSVE)
	}
}
.constdata__ZTVN2al19ActorPoseKeeperTRSVE 0x003d6e8c
{
	.constdata__ZTVN2al19ActorPoseKeeperTRSVE 0x003d6e8c
	{
		* (.constdata__ZTVN2al19ActorPoseKeeperTRSVE)
	}
}
.constdata__ZTVN2al20ActorPoseKeeperTFGSVE 0x003d6f78
{
	.constdata__ZTVN2al20ActorPoseKeeperTFGSVE 0x003d6f78
	{
		* (.constdata__ZTVN2al20ActorPoseKeeperTFGSVE)
	}
}
.constdata__ZTVN2al9AreaShapeE 0x003d7960
{
	.constdata__ZTVN2al9AreaShapeE 0x003d7960
	{
		* (.constdata__ZTVN2al9AreaShapeE)
	}
}
.constdata__ZTVN2al9LiveActorE 0x003d7974
{
	.constdata__ZTVN2al9LiveActorE 0x003d7974
	{
		* (.constdata__ZTVN2al9LiveActorE)
	}
}
.constdata__ZTVN4sead14SafeStringBaseIcEE 0x003d9c34
{
	.constdata__ZTVN4sead14SafeStringBaseIcEE 0x003d9c34
	{
		* (.constdata__ZTVN4sead14SafeStringBaseIcEE)
	}
}
:gdef:_ZN11Application9sInstanceE 0x003e23c4
{
	:gdef:_ZN11Application9sInstanceE 0x003e23c4
	{
		* (:gdef:_ZN11Application9sInstanceE)
	}
}
i.NerveActionCollector::sCurrentCollector 0x003ef620
{
	i.NerveActionCollector::sCurrentCollector 0x003ef620
	{
		* (i.NerveActionCollector::sCurrentCollector)
	}
}
i.sNameToTypeLookupTable 0x003f02b8
{
	i.sNameToTypeLookupTable 0x003f02b8
	{
		* (i.sNameToTypeLookupTable)
	}
}
i.WipeSimpleNrvClose 0x003f0350
{
	i.WipeSimpleNrvClose 0x003f0350
	{
		* (i.WipeSimpleNrvClose)
	}
}
i.WipeSimpleNrvWait 0x003f0354
{
	i.WipeSimpleNrvWait 0x003f0354
	{
		* (i.WipeSimpleNrvWait)
	}
}
i.WipeSimpleNrvOpen 0x003f0358
{
	i.WipeSimpleNrvOpen 0x003f0358
	{
		* (i.WipeSimpleNrvOpen)
	}
}
i.GhostPlayerNrvBegin 0x003f0eec
{
	i.GhostPlayerNrvBegin 0x003f0eec
	{
		* (i.GhostPlayerNrvBegin)
	}
}
i.GhostPlayerNrvNrv5 0x003f0ef8
{
	i.GhostPlayerNrvNrv5 0x003f0ef8
	{
		* (i.GhostPlayerNrvNrv5)
	}
}
i.BreakModelNrvWait 0x003f1338
{
	i.BreakModelNrvWait 0x003f1338
	{
		* (i.BreakModelNrvWait)
	}
}
i.BreakModelNrvBreak 0x003f133c
{
	i.BreakModelNrvBreak 0x003f133c
	{
		* (i.BreakModelNrvBreak)
	}
}
i.FugumannenNrvMove 0x003f1fc0
{
	i.FugumannenNrvMove 0x003f1fc0
	{
		* (i.FugumannenNrvMove)
	}
}
i.FugumannenNrvMove2 0x003f1fc4
{
	i.FugumannenNrvMove2 0x003f1fc4
	{
		* (i.FugumannenNrvMove2)
	}
}
i.FugumannenNrvBlowDown 0x003f1fc8
{
	i.FugumannenNrvBlowDown 0x003f1fc8
	{
		* (i.FugumannenNrvBlowDown)
	}
}
i.TogezoNrvWander 0x003f2464
{
	i.TogezoNrvWander 0x003f2464
	{
		* (i.TogezoNrvWander)
	}
}
i.TogezoNrvTurn 0x003f2468
{
	i.TogezoNrvTurn 0x003f2468
	{
		* (i.TogezoNrvTurn)
	}
}
i.TogezoNrvSearch 0x003f246c
{
	i.TogezoNrvSearch 0x003f246c
	{
		* (i.TogezoNrvSearch)
	}
}
i.TogezoNrvChase 0x003f2470
{
	i.TogezoNrvChase 0x003f2470
	{
		* (i.TogezoNrvChase)
	}
}
i.TogezoNrvAttack 0x003f2474
{
	i.TogezoNrvAttack 0x003f2474
	{
		* (i.TogezoNrvAttack)
	}
}
i.TogezoNrvBlowDown 0x003f2478
{
	i.TogezoNrvBlowDown 0x003f2478
	{
		* (i.TogezoNrvBlowDown)
	}
}
i.AppearStepNrvAppear 0x003f2514
{
	i.AppearStepNrvAppear 0x003f2514
	{
		* (i.AppearStepNrvAppear)
	}
}
i.AppearStepNrvWait 0x003f2518
{
	i.AppearStepNrvWait 0x003f2518
	{
		* (i.AppearStepNrvWait)
	}
}
i.AppearStepNrvDisappear 0x003f251c
{
	i.AppearStepNrvDisappear 0x003f251c
	{
		* (i.AppearStepNrvDisappear)
	}
}
i.AppearStepNrvEnd 0x003f2520
{
	i.AppearStepNrvEnd 0x003f2520
	{
		* (i.AppearStepNrvEnd)
	}
}
i.AquariumSwimDebrisNrvAppear 0x003f2524
{
	i.AquariumSwimDebrisNrvAppear 0x003f2524
	{
		* (i.AquariumSwimDebrisNrvAppear)
	}
}
i.FallMapPartsNrvAppear 0x003f2738
{
	i.FallMapPartsNrvAppear 0x003f2738
	{
		* (i.FallMapPartsNrvAppear)
	}
}
i.FallMapPartsNrvWait 0x003f273c
{
	i.FallMapPartsNrvWait 0x003f273c
	{
		* (i.FallMapPartsNrvWait)
	}
}
i.FallMapPartsNrvFallSign 0x003f2740
{
	i.FallMapPartsNrvFallSign 0x003f2740
	{
		* (i.FallMapPartsNrvFallSign)
	}
}
i.FallMapPartsNrvFall 0x003f2744
{
	i.FallMapPartsNrvFall 0x003f2744
	{
		* (i.FallMapPartsNrvFall)
	}
}
i.FallMapPartsNrvEnd 0x003f2748
{
	i.FallMapPartsNrvEnd 0x003f2748
	{
		* (i.FallMapPartsNrvEnd)
	}
}
i.NoteObjGeneratorNrvWait 0x003f2a3c
{
	i.NoteObjGeneratorNrvWait 0x003f2a3c
	{
		* (i.NoteObjGeneratorNrvWait)
	}
}
i.NoteObjGeneratorNrvMove 0x003f2a44
{
	i.NoteObjGeneratorNrvMove 0x003f2a44
	{
		* (i.NoteObjGeneratorNrvMove)
	}
}
i.NoteObjGeneratorNrvDisappear 0x003f2a4c
{
	i.NoteObjGeneratorNrvDisappear 0x003f2a4c
	{
		* (i.NoteObjGeneratorNrvDisappear)
	}
}
i.NoteObjGeneratorNrvSuccess 0x003f2a54
{
	i.NoteObjGeneratorNrvSuccess 0x003f2a54
	{
		* (i.NoteObjGeneratorNrvSuccess)
	}
}
i.TrickHintPanelNrvWait 0x003f2ca4
{
	i.TrickHintPanelNrvWait 0x003f2ca4
	{
		* (i.TrickHintPanelNrvWait)
	}
}
i.TrickHintPanelNrvOn 0x003f2ca8
{
	i.TrickHintPanelNrvOn 0x003f2ca8
	{
		* (i.TrickHintPanelNrvOn)
	}
}
i.TrickHintPanelNrvnrv3 0x003f2cac
{
	i.TrickHintPanelNrvnrv3 0x003f2cac
	{
		* (i.TrickHintPanelNrvnrv3)
	}
}
i.TrickHintPanelNrvOff 0x003f2cb0
{
	i.TrickHintPanelNrvOff 0x003f2cb0
	{
		* (i.TrickHintPanelNrvOff)
	}
}
i.RailMoveMovementNrvMove 0x003f2e1c
{
	i.RailMoveMovementNrvMove 0x003f2e1c
	{
		* (i.RailMoveMovementNrvMove)
	}
}
i.FireBallNrvShot 0x003f2fd8
{
	i.FireBallNrvShot 0x003f2fd8
	{
		* (i.FireBallNrvShot)
	}
}
i.FlowerPotNrvWait 0x003f3164
{
	i.FlowerPotNrvWait 0x003f3164
	{
		* (i.FlowerPotNrvWait)
	}
}
i.RailDotNrvWait 0x003f3190
{
	i.RailDotNrvWait 0x003f3190
	{
		* (i.RailDotNrvWait)
	}
}
i.RailDotEndNrvWait 0x003f3194
{
	i.RailDotEndNrvWait 0x003f3194
	{
		* (i.RailDotEndNrvWait)
	}
}
i.al::ActorPoseKeeperBase::sDefaultGravity 0x00424f2c
{
	i.al::ActorPoseKeeperBase::sDefaultGravity 0x00424f2c
	{
		* (i.al::ActorPoseKeeperBase::sDefaultGravity)
	}
}
i.sTogezoWalkerStateParam 0x0042fb10
{
	i.sTogezoWalkerStateParam 0x0042fb10
	{
		* (i.sTogezoWalkerStateParam)
	}
}
i.sTogezoWalkerStateWanderParam 0x0042fb30
{
	i.sTogezoWalkerStateWanderParam 0x0042fb30
	{
		* (i.sTogezoWalkerStateWanderParam)
	}
}
i.sTogezoWalkerStateChaseParam 0x0042fb9c
{
	i.sTogezoWalkerStateChaseParam 0x0042fb9c
	{
		* (i.sTogezoWalkerStateChaseParam)
	}
}
.bss__ZN4sead4QuatIfE4unitE 0x00430500
{
	.bss__ZN4sead4QuatIfE4unitE 0x00430500
	{
		* (.bss__ZN4sead4QuatIfE4unitE)
	}
}
.bss__ZN4sead7Vector3IfE2exE 0x004305c8
{
	.bss__ZN4sead7Vector3IfE2exE 0x004305c8
	{
		* (.bss__ZN4sead7Vector3IfE2exE)
	}
}
.bss__ZN4sead7Vector3IfE2eyE 0x004305d4
{
	.bss__ZN4sead7Vector3IfE2eyE 0x004305d4
	{
		* (.bss__ZN4sead7Vector3IfE2eyE)
	}
}
.bss__ZN4sead7Vector3IfE2ezE 0x004305e0
{
	.bss__ZN4sead7Vector3IfE2ezE 0x004305e0
	{
		* (.bss__ZN4sead7Vector3IfE2ezE)
	}
}
.bss__ZN4sead7Vector3IfE4zeroE 0x004305f8
{
	.bss__ZN4sead7Vector3IfE4zeroE 0x004305f8
	{
		* (.bss__ZN4sead7Vector3IfE4zeroE)
	}
}


RO_SECTION 0x003a2000
{
    RO +0
    {
        * (+CONST)
    }
    STATIC_INIT  +0 
    {
        * (.static_init)
    }
    ET +0
    {
        * (.ARM.exidx)
        * (.ARM.extab)
    }
}

RW_SECTION 0x003e1000
{
    RW +0
    {
        * (+RW-DATA)
    }
    ZI +0
    {
        * (+ZI)
    }
}

MODULE_INFO     (0x00100000 + (0x04000000 - 0x00100000))
{
    .module_id  (0x00100000 + (0x04000000 - 0x00100000))
    {
        * (.module_id)
    }
}

GARBAGE_SECTION 0x00432000
{
    REST_SECTION 0x00432000
    {
        * (+CODE)
    }
}