LMS_Impl.c
LMS_AllocFuncPtr LMSi_sAllocFuncPtr
Referenced by LMS_SetMemFuncs, LMSi_Malloc.
LMS_FreeFuncPtr LMSi_sFreeFuncPtr
Referenced by LMS_SetMemFuncs, LMSi_Free.
void * LMSi_Malloc(u32 size)
References LMSi_sAllocFuncPtr.
Referenced by LMS_InitMessage.
void LMSi_Free(void *ptr)
References LMSi_sFreeFuncPtr.
Referenced by LMS_CloseMessage.
void LMS_SetMemFuncs(LMS_AllocFuncPtr alloc_ptr, LMS_FreeFuncPtr free_ptr)
References LMSi_sAllocFuncPtr, LMSi_sFreeFuncPtr.
s32 LMSi_SearchBlockByName(LMS_Binary *binary, const char *blockName)
References LMS_Binary::blocks, LMSi_MemCmp, LMS_Binary::numBlocks, LMS_BinaryBlock::type.
Referenced by LMS_InitMessage.