LMS_Impl.h
LMS_MessageEncoding
typedef void *(* LMS_AllocFuncPtr) (u32 size))(u32 size)
typedef void(* LMS_FreeFuncPtr) (void *ptr))(void *ptr)
typedef struct LMS_BinaryBlock LMS_BinaryBlock
typedef enum LMS_MessageEncoding LMS_MessageEncoding
typedef struct LMS_Binary LMS_Binary
_Bool LMSi_MemCmp(const void *, const void *, u32 size)
Referenced by LMSi_SearchBlockByName.
void * LMSi_Malloc(u32 size)
References LMSi_sAllocFuncPtr.
Referenced by LMS_InitMessage.
void LMSi_Free(void *ptr)
References LMSi_sFreeFuncPtr.
Referenced by LMS_CloseMessage.
void LMS_SetMemFuncs(LMS_AllocFuncPtr alloc_ptr, LMS_FreeFuncPtr free_ptr)
References LMSi_sAllocFuncPtr, LMSi_sFreeFuncPtr.
void LMSi_AnalyzeMessageBinary(LMS_Binary *binary, const char *magic)
Referenced by LMS_InitMessage.
s32 LMSi_SearchBlockByName(LMS_Binary *binary, const char *blockName)
References LMS_Binary::blocks, LMSi_MemCmp, LMS_Binary::numBlocks, LMS_BinaryBlock::type.
Referenced by LMS_InitMessage.