sead::Matrix34CalcCommon
typedef Policies<T>::Mtx34Base sead::Matrix34CalcCommon< T >::Base
typedef Policies<T>::Mtx33Base sead::Matrix34CalcCommon< T >::Mtx33
typedef Policies<T>::Mtx44Base sead::Matrix34CalcCommon< T >::Mtx44
typedef Policies<T>::QuatBase sead::Matrix34CalcCommon< T >::Quat
typedef Policies<T>::Vec3Base sead::Matrix34CalcCommon< T >::Vec3
typedef Policies<T>::Vec4Base sead::Matrix34CalcCommon< T >::Vec4
void sead::Matrix34CalcCommon< T >::makeIdentity(Base &o)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::makeIdentity.
void sead::Matrix34CalcCommon< T >::makeZero(Base &o)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::makeZero.
void sead::Matrix34CalcCommon< T >::copy(Base &o, const Base &n)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::Matrix34, sead::Matrix34< T >::Matrix34, sead::Matrix34< T >::operator=.
void sead::Matrix34CalcCommon< T >::copy(Base &o, const Mtx33 &n, const Vec3 &t)
References sead::BaseMtx33< T >::m, sead::BaseMtx34< T >::m.
void sead::Matrix34CalcCommon< T >::copy(Base &o, const Mtx44 &n)
References sead::BaseMtx34< T >::m, sead::BaseMtx44< T >::m.
void sead::Matrix34CalcCommon< T >::inverse(Base &o, const Base &n)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::setInverse.
void sead::Matrix34CalcCommon< T >::inverse33(Base &o, const Base &n)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::setInverse33.
void sead::Matrix34CalcCommon< T >::inverseTranspose(Base &o, const Base &n)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::setInverseTranspose.
void sead::Matrix34CalcCommon< T >::multiply(Base &o, const Base &a, const Base &b)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::setMul, sead::Matrix34< T >::setMul.
void sead::Matrix34CalcCommon< T >::multiply(Base &o, const Mtx33 &a, const Base &b)
References sead::BaseMtx33< T >::m, sead::BaseMtx34< T >::m.
void sead::Matrix34CalcCommon< T >::multiply(Base &o, const Base &a, const Mtx33 &b)
References sead::BaseMtx33< T >::m, sead::BaseMtx34< T >::m.
void sead::Matrix34CalcCommon< T >::transpose(Base &o)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::transpose.
void sead::Matrix34CalcCommon< T >::transposeTo(Base &o, const Base &n)
References sead::BaseMtx34< T >::m, SEAD_ASSERT.
Referenced by sead::Matrix34< T >::setTranspose.
void sead::Matrix34CalcCommon< T >::makeQ(Base &o, const Quat &q)
References sead::BaseMtx34< T >::m, sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Matrix34< T >::fromQuat.
void sead::Matrix34CalcCommon< T >::makeQT(Base &o, const Quat &q, const Vec3 &t)
References sead::BaseMtx34< T >::m, sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Matrix34< T >::makeQT.
void sead::Matrix34CalcCommon< T >::makeR(Base &o, const Vec3 &r)
References sead::MathCalcCommon< T >::cos, sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sin.
Referenced by sead::Matrix34< T >::makeR.
void sead::Matrix34CalcCommon< T >::makeRIdx(Base &o, u32 xr, u32 yr, u32 zr)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix34< T >::makeRIdx.
void sead::Matrix34CalcCommon< T >::makeRT(Base &o, const Vec3 &r, const Vec3 &t)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::makeRT.
void sead::Matrix34CalcCommon< T >::makeRTIdx(Base &o, const Vector3< u32 > &r, const Vec3 &t)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix34< T >::makeRTIdx.
void sead::Matrix34CalcCommon< T >::makeRzxyIdx(Base &o, u32 xr, u32 yr, u32 zr)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix34< T >::makeRzxyIdx.
void sead::Matrix34CalcCommon< T >::makeRzxyTIdx(Base &o, const Vector3< u32 > &r, const Vec3 &t)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix34< T >::makeRzxyTIdx.
void sead::Matrix34CalcCommon< T >::makeS(Base &o, const Vec3 &s)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::makeS, sead::Matrix34< T >::makeS.
void sead::Matrix34CalcCommon< T >::makeSR(Base &o, const Vec3 &s, const Vec3 &r)
References sead::MathCalcCommon< T >::cos, sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sin.
Referenced by sead::Matrix34< T >::makeSR.
void sead::Matrix34CalcCommon< T >::makeSRIdx(Base &o, const Vec3 &s, const Vector3< u32 > &r)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix34< T >::makeSRIdx.
void sead::Matrix34CalcCommon< T >::makeSRT(Base &o, const Vec3 &s, const Vec3 &r, const Vec3 &t)
References sead::MathCalcCommon< T >::cos, sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sin.
Referenced by sead::Matrix34< T >::makeSRT.
void sead::Matrix34CalcCommon< T >::makeSRTIdx(Base &o, const Vec3 &s, const Vector3< u32 > &r, const Vec3 &t)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix34< T >::makeSRTIdx.
void sead::Matrix34CalcCommon< T >::makeSRzxyIdx(Base &o, const Vec3 &s, const Vector3< u32 > &r)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix34< T >::makeSRzxyIdx.
void sead::Matrix34CalcCommon< T >::makeSRzxyTIdx(Base &o, const Vec3 &s, const Vector3< u32 > &r, const Vec3 &t)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix34< T >::makeSRzxyTIdx.
void sead::Matrix34CalcCommon< T >::makeST(Base &o, const Vec3 &s, const Vec3 &t)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::makeST.
void sead::Matrix34CalcCommon< T >::makeT(Base &o, const Vec3 &t)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::makeT, sead::Matrix34< T >::makeT.
void sead::Matrix34CalcCommon< T >::toQuat(Quat &q, const Base &n)
References sead::BaseMtx34< T >::m, sead::MathCalcCommon< T >::sqrt, sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Matrix34< T >::toQuat.
void sead::Matrix34CalcCommon< T >::getBase(Vec3 &v, const Base &n, s32 axis)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::getBase.
void sead::Matrix34CalcCommon< T >::getRow(Vec4 &v, const Base &n, s32 row)
References sead::BaseMtx34< T >::m, sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
Referenced by sead::Matrix34< T >::getRow.
void sead::Matrix34CalcCommon< T >::getTranslation(Vec3 &v, const Base &n)
Referenced by sead::Matrix34< T >::getTranslation.
void sead::Matrix34CalcCommon< T >::getRotation(Vec3 &v, const Base &n)
References sead::MathCalcCommon< T >::abs, sead::BaseMtx34< T >::m, sead::numbers::pi_v.
Referenced by sead::Matrix34< T >::getRotation.
void sead::Matrix34CalcCommon< T >::scaleAllElements(Base &n, T s)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::scaleAllElements.
void sead::Matrix34CalcCommon< T >::scaleBases(Base &n, T sx, T sy, T sz)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::scaleBases.
void sead::Matrix34CalcCommon< T >::setBase(Base &n, s32 axis, const Vec3 &v)
References sead::BaseMtx34< T >::m.
Referenced by sead::Matrix34< T >::setBase.
void sead::Matrix34CalcCommon< T >::setRow(Base &n, const Vec4 &v, s32 row)
References sead::BaseMtx34< T >::m, sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
Referenced by sead::Matrix34< T >::setRow.
void sead::Matrix34CalcCommon< T >::setTranslation(Base &n, const Vec3 &v)
Referenced by sead::Matrix34< T >::setTranslation, sead::Matrix34< T >::setTranslation.