sead::OffsetList
typedef int(* sead::OffsetList< T >::CompareCallback) (const T *, const T *))(const T *, const T *)
s32 sead::OffsetList< T >::mOffset
Referenced by sead::OffsetList< T >::begin, sead::OffsetList< T >::begin, sead::OffsetList< T >::end, sead::OffsetList< T >::find, sead::OffsetList< T >::initOffset, sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::objToListNode, sead::OffsetList< T >::objToListNode, sead::OffsetList< T >::pushBack, sead::OffsetList< T >::pushFront, sead::OffsetList< T >::robustBegin, sead::OffsetList< T >::robustBegin, sead::OffsetList< T >::robustEnd, sead::OffsetList< T >::sort, sead::OffsetList< T >::uniq.
sead::OffsetList< T >::OffsetList()
void sead::OffsetList< T >::initOffset(s32 offset)
References sead::OffsetList< T >::mOffset.
void sead::OffsetList< T >::clear()
References sead::ListImpl::clear.
void sead::OffsetList< T >::pushBack(T *item)
References sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset, sead::OffsetList< T >::objToListNode, sead::ListImpl::pushBack, SEAD_ASSERT.
void sead::OffsetList< T >::pushFront(T *item)
References sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset, sead::OffsetList< T >::objToListNode, sead::ListImpl::pushFront, SEAD_ASSERT.
T * sead::OffsetList< T >::popBack()
References sead::OffsetList< T >::listNodeToObjWithNullCheck, sead::ListImpl::popBack.
T * sead::OffsetList< T >::popFront()
References sead::OffsetList< T >::listNodeToObjWithNullCheck, sead::ListImpl::popFront.
void sead::OffsetList< T >::insertBefore(const T *obj, T *obj_to_insert)
References sead::ListImpl::insertBefore, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::objToListNode.
void sead::OffsetList< T >::insertAfter(const T *obj, T *obj_to_insert)
References sead::ListImpl::insertAfter, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::objToListNode.
void sead::OffsetList< T >::erase(T *item)
References sead::ListImpl::erase, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::objToListNode.
T * sead::OffsetList< T >::front() const
References sead::ListImpl::front, sead::OffsetList< T >::listNodeToObjWithNullCheck.
T * sead::OffsetList< T >::back() const
References sead::ListImpl::back, sead::OffsetList< T >::listNodeToObjWithNullCheck.
T * sead::OffsetList< T >::prev(const T *obj) const
References sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mergeSort, sead::ListImpl::mStartEnd, sead::OffsetList< T >::objToListNode, sead::ListNode::prev.
T * sead::OffsetList< T >::next(const T *obj) const
References sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mergeSort, sead::ListImpl::mStartEnd, sead::ListNode::next, sead::OffsetList< T >::objToListNode.
Referenced by sead::OffsetList< T >::iterator::operator++.
T * sead::OffsetList< T >::nth(s32 n) const
References sead::OffsetList< T >::listNodeToObjWithNullCheck, sead::OffsetList< T >::mergeSort, sead::ListImpl::nth.
s32 sead::OffsetList< T >::indexOf(const T *obj) const
References sead::ListImpl::indexOf, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::objToListNode.
bool sead::OffsetList< T >::isNodeLinked(const T *obj) const
References sead::ListNode::isLinked, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::objToListNode.
void sead::OffsetList< T >::swap(T *obj1, T *obj2)
References sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::objToListNode, sead::ListImpl::swap.
void sead::OffsetList< T >::moveAfter(T *basis, T *obj)
References sead::OffsetList< T >::mergeSort, sead::ListImpl::moveAfter, sead::OffsetList< T >::objToListNode.
void sead::OffsetList< T >::moveBefore(T *basis, T *obj)
References sead::OffsetList< T >::mergeSort, sead::ListImpl::moveBefore, sead::OffsetList< T >::objToListNode.
void sead::OffsetList< T >::sort()
References sead::OffsetList< T >::compareT, sead::OffsetList< T >::sort.
Referenced by sead::OffsetList< T >::sort.
void sead::OffsetList< T >::sort(CompareCallback cmp)
References sead::OffsetList< T >::mergeSort, sead::ListImpl::mergeSort, sead::OffsetList< T >::mOffset.
void sead::OffsetList< T >::mergeSort()
References sead::OffsetList< T >::compareT, sead::OffsetList< T >::mergeSort.
Referenced by sead::OffsetList< T >::begin, sead::OffsetList< T >::compareT, sead::OffsetList< T >::erase, sead::OffsetList< T >::find, sead::OffsetList< T >::find, sead::OffsetList< T >::indexOf, sead::OffsetList< T >::insertAfter, sead::OffsetList< T >::insertBefore, sead::OffsetList< T >::isNodeLinked, sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::listNodeToObjWithNullCheck, sead::OffsetList< T >::listNodeToObjWithNullCheck, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::moveAfter, sead::OffsetList< T >::moveBefore, sead::OffsetList< T >::next, sead::OffsetList< T >::nth, sead::OffsetList< T >::objToListNode, sead::OffsetList< T >::objToListNode, sead::OffsetList< T >::iterator::operator!=, sead::OffsetList< T >::robustIterator::operator!=, sead::OffsetList< T >::iterator::operator++, sead::OffsetList< T >::robustIterator::operator++, sead::OffsetList< T >::iterator::operator==, sead::OffsetList< T >::robustIterator::operator==, sead::OffsetList< T >::prev, sead::OffsetList< T >::pushBack, sead::OffsetList< T >::pushFront, sead::OffsetList< T >::robustBegin, sead::OffsetList< T >::sort, sead::OffsetList< T >::swap, sead::OffsetList< T >::uniq.
void sead::OffsetList< T >::mergeSort(CompareCallback cmp)
References sead::OffsetList< T >::mergeSort, sead::ListImpl::mergeSort, sead::OffsetList< T >::mOffset.
T * sead::OffsetList< T >::find(const T *obj) const
References sead::OffsetList< T >::compareT, sead::OffsetList< T >::find, sead::OffsetList< T >::mergeSort.
Referenced by sead::OffsetList< T >::find.
T * sead::OffsetList< T >::find(const T *obj, CompareCallback cmp) const
References sead::ListImpl::find, sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset.
void sead::OffsetList< T >::uniq()
References sead::OffsetList< T >::compareT, sead::OffsetList< T >::uniq.
Referenced by sead::OffsetList< T >::uniq.
void sead::OffsetList< T >::uniq(CompareCallback cmp)
References sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset, sead::ListImpl::uniq.
iterator sead::OffsetList< T >::begin() const
References sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mOffset, sead::ListImpl::mStartEnd, sead::ListNode::next.
iterator sead::OffsetList< T >::end() const
References sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mOffset, sead::ListImpl::mStartEnd.
iterator sead::OffsetList< T >::begin(T *ptr) const
References sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset.
robustIterator sead::OffsetList< T >::robustBegin() const
References sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mOffset, sead::ListImpl::mStartEnd, sead::ListNode::next.
Referenced by sead::OffsetList< T >::RobustRange::begin.
robustIterator sead::OffsetList< T >::robustEnd() const
References sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mOffset, sead::ListImpl::mStartEnd.
Referenced by sead::OffsetList< T >::RobustRange::end.
robustIterator sead::OffsetList< T >::robustBegin(T *ptr) const
References sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset.
RobustRange sead::OffsetList< T >::robustRange() const
static int sead::OffsetList< T >::compareT(const T *lhs, const T *rhs)
References sead::OffsetList< T >::mergeSort.
Referenced by sead::OffsetList< T >::find, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::sort, sead::OffsetList< T >::uniq.
ListNode * sead::OffsetList< T >::objToListNode(T *obj) const
References sead::PtrUtil::addOffset, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset.
Referenced by sead::OffsetList< T >::erase, sead::OffsetList< T >::indexOf, sead::OffsetList< T >::insertAfter, sead::OffsetList< T >::insertBefore, sead::OffsetList< T >::isNodeLinked, sead::OffsetList< T >::moveAfter, sead::OffsetList< T >::moveBefore, sead::OffsetList< T >::next, sead::OffsetList< T >::prev, sead::OffsetList< T >::pushBack, sead::OffsetList< T >::pushFront, sead::OffsetList< T >::swap.
const ListNode * sead::OffsetList< T >::objToListNode(const T *obj) const
References sead::PtrUtil::addOffset, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset.
T * sead::OffsetList< T >::listNodeToObj(ListNode *node) const
References sead::PtrUtil::addOffset, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset.
Referenced by sead::OffsetList< T >::begin, sead::OffsetList< T >::end, sead::OffsetList< T >::find, sead::OffsetList< T >::listNodeToObjWithNullCheck, sead::OffsetList< T >::listNodeToObjWithNullCheck, sead::OffsetList< T >::next, sead::OffsetList< T >::prev, sead::OffsetList< T >::robustBegin, sead::OffsetList< T >::robustEnd.
const T * sead::OffsetList< T >::listNodeToObj(const ListNode *node) const
References sead::PtrUtil::addOffset, sead::OffsetList< T >::mergeSort, sead::OffsetList< T >::mOffset.
T * sead::OffsetList< T >::listNodeToObjWithNullCheck(ListNode *node) const
References sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mergeSort.
Referenced by sead::OffsetList< T >::back, sead::OffsetList< T >::front, sead::OffsetList< T >::nth, sead::OffsetList< T >::popBack, sead::OffsetList< T >::popFront.
const T * sead::OffsetList< T >::listNodeToObjWithNullCheck(const ListNode *node) const
References sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::mergeSort.