sead::ListNode
friend class ListImpl
ListNode* sead::ListNode::mPrev
Referenced by sead::ListImpl::back, sead::ListImpl::clear, erase_, insertBack_, insertFront_, isLinked, sead::ListImpl::ListImpl, sead::ListImpl::mergeSort, sead::ListImpl::popBack, prev, sead::ListImpl::swap.
ListNode* sead::ListNode::mNext
Referenced by sead::ListImpl::clear, erase_, sead::ListImpl::front, sead::ListImpl::indexOf, insertBack_, insertFront_, isLinked, sead::ListImpl::ListImpl, sead::ListImpl::mergeSort, next, sead::ListImpl::nth, sead::ListImpl::popFront.
ListNode * sead::ListNode::next() const
References mNext.
Referenced by sead::OffsetList< T >::begin, sead::TList< T >::begin, insertBack_, sead::OffsetList< T >::next, sead::OffsetList< T >::robustIterator::operator++, sead::OffsetList< T >::robustBegin, sead::TList< T >::robustBegin.
ListNode * sead::ListNode::prev() const
References mPrev.
Referenced by insertFront_, sead::OffsetList< T >::prev.
bool sead::ListNode::isLinked() const
References mNext, mPrev.
Referenced by erase_, insertBack_, insertFront_, sead::OffsetList< T >::isNodeLinked.
sead::ListNode::ListNode()
void sead::ListNode::init_()
Referenced by sead::ListImpl::clear.
void sead::ListNode::insertBack_(ListNode *node)
References isLinked, mNext, mPrev, next, SEAD_ASSERT_MSG.
Referenced by sead::ListImpl::pushFront.
void sead::ListNode::insertFront_(ListNode *node)
References isLinked, mNext, mPrev, prev, SEAD_ASSERT_MSG.
Referenced by sead::ListImpl::pushBack.
void sead::ListNode::erase_()
References isLinked, mNext, mPrev, NULL, SEAD_ASSERT_MSG.
Referenced by sead::ListImpl::popBack, sead::ListImpl::popFront, sead::ListImpl::swap.