sead::Vector4CalcCtr
typedef Policies<T>::Vec4Base sead::Vector4CalcCtr< T >::Base
void sead::Vector4CalcCtr< T >::set(Base &o, const Base &v)
References sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
Referenced by sead::Vector4< T >::operator=, sead::Vector4< T >::set, sead::Vector4< T >::set, sead::Vector4< T >::Vector4.
void sead::Vector4CalcCtr< T >::set(Base &v, T x, T y, T z, T w)
References sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.