sead::PtrUtil
static void * sead::PtrUtil::roundUpPow2(const void *ptr, u32 n)
static void * sead::PtrUtil::roundUpN(const void *ptr, u32 n)
static void * sead::PtrUtil::roundDownPow2(const void *ptr, u32 n)
static void * sead::PtrUtil::roundDownN(const void *ptr, u32 n)
static void * sead::PtrUtil::addOffset(const void *ptr, intptr_t offset)
Referenced by sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::listNodeToObj, sead::OffsetList< T >::objToListNode, sead::OffsetList< T >::objToListNode, sead::OffsetList< T >::iterator::operator++, sead::OffsetList< T >::robustIterator::operator++.
static intptr_t sead::PtrUtil::diff(const void *ptr1, const void *ptr2)
static bool sead::PtrUtil::isInclude(const void *ptr, const void *begin, const void *end)
static bool sead::PtrUtil::isAligned(const void *ptr, s32 alignment)
References SEAD_ASSERT.
static bool sead::PtrUtil::isAlignedPow2(const void *ptr, u32 n)
static bool sead::PtrUtil::isAlignedN(const void *ptr, s32 n)