sead::Matrix44CalcCommon
typedef Policies<T>::Mtx44Base sead::Matrix44CalcCommon< T >::Base
typedef Policies<T>::Mtx33Base sead::Matrix44CalcCommon< T >::Mtx33
typedef Policies<T>::Mtx34Base sead::Matrix44CalcCommon< T >::Mtx34
typedef Policies<T>::QuatBase sead::Matrix44CalcCommon< T >::Quat
typedef Policies<T>::Vec3Base sead::Matrix44CalcCommon< T >::Vec3
typedef Policies<T>::Vec4Base sead::Matrix44CalcCommon< T >::Vec4
void sead::Matrix44CalcCommon< T >::makeIdentity(Base &o)
References sead::BaseMtx44< T >::m.
Referenced by sead::Matrix44< T >::makeIdentity.
void sead::Matrix44CalcCommon< T >::makeZero(Base &o)
References sead::BaseMtx44< T >::m.
Referenced by sead::Matrix44< T >::makeZero.
void sead::Matrix44CalcCommon< T >::copy(Base &o, const Base &n)
References sead::BaseMtx44< T >::m.
Referenced by sead::Matrix44< T >::Matrix44, sead::Matrix44< T >::Matrix44, sead::Matrix44< T >::operator=.
void sead::Matrix44CalcCommon< T >::copy(Base &o, const Mtx33 &n, const Vec3 &t, const Vec4 &v)
References sead::BaseMtx33< T >::m, sead::BaseMtx44< T >::m, sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
void sead::Matrix44CalcCommon< T >::copy(Base &o, const Mtx34 &n, const Vec4 &v)
References sead::BaseMtx34< T >::m, sead::BaseMtx44< T >::m, sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
void sead::Matrix44CalcCommon< T >::inverse(Base &o, const Base &n)
References sead::BaseMtx44< T >::m.
Referenced by sead::Matrix44< T >::setInverse.
void sead::Matrix44CalcCommon< T >::inverseTranspose(Base &o, const Base &n)
References sead::BaseMtx44< T >::m.
void sead::Matrix44CalcCommon< T >::multiply(Base &o, const Base &a, const Base &b)
References sead::BaseMtx44< T >::m.
Referenced by sead::Matrix44< T >::setMul, sead::Matrix44< T >::setMul, sead::Matrix44< T >::setMul.
void sead::Matrix44CalcCommon< T >::multiply(Base &o, const Mtx34 &a, const Base &b)
References sead::BaseMtx34< T >::m, sead::BaseMtx44< T >::m.
void sead::Matrix44CalcCommon< T >::multiply(Base &o, const Base &a, const Mtx34 &b)
References sead::BaseMtx34< T >::m, sead::BaseMtx44< T >::m.
void sead::Matrix44CalcCommon< T >::transpose(Base &o)
References sead::BaseMtx44< T >::m.
Referenced by sead::Matrix44< T >::transpose.
void sead::Matrix44CalcCommon< T >::transposeTo(Base &o, const Base &n)
References sead::BaseMtx44< T >::m, SEAD_ASSERT.
Referenced by sead::Matrix44< T >::setTranspose.
void sead::Matrix44CalcCommon< T >::makeQ(Base &o, const Quat &q)
References sead::BaseMtx44< T >::m, sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Matrix44< T >::fromQuat.
void sead::Matrix44CalcCommon< T >::makeR(Base &o, const Vec3 &r)
References sead::MathCalcCommon< T >::cos, sead::BaseMtx44< T >::m, sead::MathCalcCommon< T >::sin.
Referenced by sead::Matrix44< T >::makeR.
void sead::Matrix44CalcCommon< T >::makeRIdx(Base &o, u32 xr, u32 yr, u32 zr)
References sead::BaseMtx44< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix44< T >::makeRIdx.
void sead::Matrix44CalcCommon< T >::makeRzxyIdx(Base &o, u32 xr, u32 yr, u32 zr)
References sead::BaseMtx44< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix44< T >::makeRzxyIdx.
void sead::Matrix44CalcCommon< T >::toQuat(Quat &q, const Base &n)
References sead::BaseMtx44< T >::m, sead::MathCalcCommon< T >::sqrt, sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Matrix44< T >::toQuat.
void sead::Matrix44CalcCommon< T >::getCol(Vec4 &v, const Base &n, s32 axis)
References sead::BaseMtx44< T >::m, sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
Referenced by sead::Matrix44< T >::getCol.
void sead::Matrix44CalcCommon< T >::getRow(Vec4 &v, const Base &n, s32 row)
References sead::BaseMtx44< T >::m, sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
Referenced by sead::Matrix44< T >::getRow.
void sead::Matrix44CalcCommon< T >::scaleAllElements(Base &n, T s)
References sead::BaseMtx44< T >::m.
Referenced by sead::Matrix44< T >::scaleAllElements.
void sead::Matrix44CalcCommon< T >::scaleBases(Base &n, T sx, T sy, T sz, T sw)
References sead::BaseMtx44< T >::m.
Referenced by sead::Matrix44< T >::scaleBases.
void sead::Matrix44CalcCommon< T >::setCol(Base &n, s32 axis, const Vec4 &v)
References sead::BaseMtx44< T >::m, sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
Referenced by sead::Matrix44< T >::setCol.
void sead::Matrix44CalcCommon< T >::setRow(Base &n, const Vec4 &v, s32 row)
References sead::BaseMtx44< T >::m, sead::BaseVec4< T >::w, sead::BaseVec4< T >::x, sead::BaseVec4< T >::y, sead::BaseVec4< T >::z.
Referenced by sead::Matrix44< T >::setRow.