sead::BitFlag
T sead::BitFlag< T >::mBits
Referenced by sead::BitFlag< T >::countContinuousOffBitFromRight, sead::BitFlag< T >::countOnBit, sead::BitFlag< T >::countRightOnBit, sead::BitFlag< T >::findOnBitFromRight, sead::BitFlag< T >::getDirect, sead::BitFlag< T >::getPtr, sead::BitFlag< T >::getPtr, sead::BitFlag< T >::isOn, sead::BitFlag< T >::isOnAll, sead::BitFlag< T >::isZero, sead::BitFlag< T >::makeAllOne, sead::BitFlag< T >::makeAllZero, sead::BitFlag< T >::operator T, sead::BitFlag< T >::reset, sead::BitFlag< T >::set, sead::BitFlag< T >::setDirect, sead::BitFlag< T >::toggle.
sead::BitFlag< T >::BitFlag()
sead::BitFlag< T >::BitFlag(T bits)
sead::BitFlag< T >::operator T() const
References sead::BitFlag< T >::mBits.
void sead::BitFlag< T >::makeAllZero()
References sead::BitFlag< T >::mBits.
void sead::BitFlag< T >::makeAllOne()
References sead::BitFlag< T >::mBits.
void sead::BitFlag< T >::setDirect(T bits)
References sead::BitFlag< T >::mBits.
T sead::BitFlag< T >::getDirect() const
References sead::BitFlag< T >::mBits.
Referenced by sead::ControllerBase::getHoldMask, sead::ControllerBase::getReleaseMask, sead::ControllerBase::getRepeatMask, sead::ControllerBase::getTrigMask.
T * sead::BitFlag< T >::getPtr()
References sead::BitFlag< T >::mBits.
Referenced by sead::ControllerBase::getHoldMaskPtr, sead::ControllerBase::getReleaseMaskPtr, sead::ControllerBase::getRepeatMaskPtr, sead::ControllerBase::getTrigMaskPtr.
const T * sead::BitFlag< T >::getPtr() const
References sead::BitFlag< T >::mBits.
size_t sead::BitFlag< T >::getByteSize() const
void sead::BitFlag< T >::set(T val)
References sead::BitFlag< T >::mBits.
Referenced by sead::BitFlag< T >::change, sead::BitFlag< T >::setBit.
void sead::BitFlag< T >::reset(T val)
References sead::BitFlag< T >::mBits.
Referenced by sead::BitFlag< T >::change, sead::BitFlag< T >::resetBit, sead::BitFlag< T >::testAndClear.
void sead::BitFlag< T >::toggle(T val)
References sead::BitFlag< T >::mBits.
Referenced by sead::BitFlag< T >::toggleBit.
void sead::BitFlag< T >::change(T val, bool on)
References sead::BitFlag< T >::reset, sead::BitFlag< T >::set.
Referenced by sead::BitFlag< T >::changeBit.
bool sead::BitFlag< T >::isZero() const
References sead::BitFlag< T >::mBits.
bool sead::BitFlag< T >::isOn(T val) const
Checks if (at least) one of the bits are set.
References sead::BitFlag< T >::mBits.
Referenced by sead::BitFlag< T >::isOff, sead::BitFlag< T >::isOnBit, sead::ControllerBase::isPointerOffNow, sead::ControllerBase::isPointerOn, sead::ControllerBase::isPointerOnNow, sead::ControllerBase::isPointerUnkFlag3, sead::BitFlag< T >::testAndClear.
bool sead::BitFlag< T >::isOnAll(T val) const
Checks if all of the bits are set.
References sead::BitFlag< T >::mBits.
bool sead::BitFlag< T >::isOff(T val) const
References sead::BitFlag< T >::isOn.
Referenced by sead::BitFlag< T >::isOffBit.
bool sead::BitFlag< T >::testAndClear(T val)
References sead::BitFlag< T >::isOn, sead::BitFlag< T >::reset.
Referenced by sead::BitFlag< T >::testAndClearBit.
T sead::BitFlag< T >::getMask(T v) const
void sead::BitFlag< T >::setBit(int bit)
References sead::BitFlag< T >::makeMask, sead::BitFlag< T >::set.
void sead::BitFlag< T >::resetBit(int bit)
References sead::BitFlag< T >::makeMask, sead::BitFlag< T >::reset.
void sead::BitFlag< T >::changeBit(int bit, bool on)
References sead::BitFlag< T >::change, sead::BitFlag< T >::makeMask.
void sead::BitFlag< T >::toggleBit(int bit)
References sead::BitFlag< T >::makeMask, sead::BitFlag< T >::toggle.
bool sead::BitFlag< T >::isOnBit(int bit) const
References sead::BitFlag< T >::isOn, sead::BitFlag< T >::makeMask.
bool sead::BitFlag< T >::isOffBit(int bit) const
References sead::BitFlag< T >::isOff, sead::BitFlag< T >::makeMask.
bool sead::BitFlag< T >::testAndClearBit(int bit)
References sead::BitFlag< T >::makeMask, sead::BitFlag< T >::testAndClear.
int sead::BitFlag< T >::countOnBit() const
Popcount.
References sead::BitFlagUtil::countOnBit, sead::BitFlag< T >::mBits.
int sead::BitFlag< T >::countContinuousOffBitFromRight() const
Count trailing zeroes.
References sead::BitFlagUtil::countContinuousOffBitFromRight, sead::BitFlag< T >::mBits.
int sead::BitFlag< T >::countRightOnBit(int bit) const
References sead::BitFlagUtil::countRightOnBit, sead::BitFlag< T >::mBits.
int sead::BitFlag< T >::findOnBitFromRight(int num) const
References sead::BitFlagUtil::findOnBitFromRight, sead::BitFlag< T >::mBits.
static T sead::BitFlag< T >::makeMask(int bit)
Referenced by sead::BitFlag< T >::changeBit, sead::BitFlag< T >::isOffBit, sead::BitFlag< T >::isOnBit, sead::BitFlag< T >::resetBit, sead::BitFlag< T >::setBit, sead::BitFlag< T >::testAndClearBit, sead::BitFlag< T >::toggleBit.