sead::PtrArrayImpl
typedef int(* sead::PtrArrayImpl::CompareCallbackImpl) (const void *a, const void *b))(const void *a, const void *b)
s32 sead::PtrArrayImpl::mPtrNumMax
Referenced by at, capacity, erase, isFull, setBuffer.
s32 sead::PtrArrayImpl::mPtrNum
Referenced by allocBufferInline, at, back, sead::PtrArray< T >::back, binarySearch, clear, sead::PtrArray< T >::constEnd, createVacancy, sead::PtrArray< T >::dataEnd, sead::PtrArray< T >::end, equal, find, indexOf, isEmpty, isFull, popBack, pushBack, search, setBuffer, size.
void** sead::PtrArrayImpl::mPtrs
Referenced by allocBufferInline, at, back, binarySearch, createVacancy, sead::PtrArray< T >::data, equal, erase, find, front, indexOf, isBufferReady, popBack, popFront, pushBack, replace, search, setBuffer, swap, unsafeAt.
sead::PtrArrayImpl::PtrArrayImpl()
sead::PtrArrayImpl::PtrArrayImpl(s32 ptrNumMax, void *buf)
References setBuffer.
void sead::PtrArrayImpl::setBuffer(s32 ptrNumMax, void *buf)
References mPtrNum, mPtrNumMax, mPtrs, NULL, SEAD_ASSERT_MSG.
Referenced by PtrArrayImpl.
void sead::PtrArrayImpl::allocBuffer(s32 ptrNumMax, Heap *heap, s32 alignment=sizeof(void *))
bool sead::PtrArrayImpl::tryAllocBuffer(s32 ptrNumMax, Heap *heap, s32 alignment=sizeof(void *))
void sead::PtrArrayImpl::allocBufferInline(s32 ptrNumMax)
References mPtrNum, mPtrs.
void sead::PtrArrayImpl::freeBuffer()
bool sead::PtrArrayImpl::isBufferReady() const
References mPtrs.
bool sead::PtrArrayImpl::isEmpty() const
References mPtrNum.
Referenced by popBack, popFront.
bool sead::PtrArrayImpl::isFull() const
References mPtrNum, mPtrNumMax.
s32 sead::PtrArrayImpl::size() const
References mPtrNum.
s32 sead::PtrArrayImpl::capacity() const
References mPtrNumMax.
Referenced by sead::HeapMgr::getRootHeapNum.
void sead::PtrArrayImpl::erase(s32 position)
References erase.
Referenced by erase, popFront.
void sead::PtrArrayImpl::erase(s32 position, s32 count)
References sead::MemUtil::copyOverlap, mPtrNumMax, mPtrs, SEAD_ASSERT_MSG.
void sead::PtrArrayImpl::clear()
References mPtrNum.
void sead::PtrArrayImpl::resize(s32 size)
void sead::PtrArrayImpl::unsafeResize(s32 size)
void sead::PtrArrayImpl::swap(s32 pos1, s32 pos2)
References mPtrs.
void sead::PtrArrayImpl::reverse()
void sead::PtrArrayImpl::shuffle()
References shuffle.
Referenced by shuffle.
void sead::PtrArrayImpl::shuffle(Random *random)
void * sead::PtrArrayImpl::at(s32 idx) const
References mPtrNum, mPtrNumMax, mPtrs, SEAD_ASSERT_MSG.
Referenced by sead::PtrArray< T >::at.
void * sead::PtrArrayImpl::unsafeAt(s32 idx) const
References mPtrs.
Referenced by sead::PtrArray< T >::unsafeAt.
void * sead::PtrArrayImpl::front() const
References mPtrs.
void * sead::PtrArrayImpl::back() const
References mPtrNum, mPtrs.
void sead::PtrArrayImpl::pushBack(void *ptr)
References mPtrNum, mPtrs.
Referenced by sead::PtrArray< T >::pushBack.
void sead::PtrArrayImpl::pushFront(void *ptr)
References insert.
Referenced by sead::PtrArray< T >::pushFront.
void * sead::PtrArrayImpl::popBack()
References isEmpty, mPtrNum, mPtrs.
Referenced by sead::PtrArray< T >::popBack.
void * sead::PtrArrayImpl::popFront()
References erase, isEmpty, mPtrs.
Referenced by sead::PtrArray< T >::popFront.
void sead::PtrArrayImpl::replace(s32 idx, void *ptr)
References mPtrs.
Referenced by sead::PtrArray< T >::replace.
void * sead::PtrArrayImpl::find(const void *ptr, CompareCallbackImpl cmp) const
References mPtrNum, mPtrs.
Referenced by sead::PtrArray< T >::find.
s32 sead::PtrArrayImpl::search(const void *ptr, CompareCallbackImpl cmp) const
References mPtrNum, mPtrs.
Referenced by sead::PtrArray< T >::search.
bool sead::PtrArrayImpl::equal(const PtrArrayImpl &other, CompareCallbackImpl cmp) const
References mPtrNum, mPtrs.
Referenced by sead::PtrArray< T >::equal.
s32 sead::PtrArrayImpl::indexOf(const void *ptr) const
References mPtrNum, mPtrs.
Referenced by sead::PtrArray< T >::indexOf.
void sead::PtrArrayImpl::createVacancy(s32 pos, s32 count)
References sead::MemUtil::copyOverlap, mPtrNum, mPtrs.
void sead::PtrArrayImpl::insert(s32 idx, void *ptr)
Referenced by sead::PtrArray< T >::insert, pushFront.
void sead::PtrArrayImpl::insertArray(s32 idx, void *array, s32 array_length, s32 elem_size)
Referenced by sead::PtrArray< T >::insert.
bool sead::PtrArrayImpl::checkInsert(s32 idx, s32 num)
void sead::PtrArrayImpl::heapSort(CompareCallbackImpl cmp)
s32 sead::PtrArrayImpl::compare(const PtrArrayImpl &other, CompareCallbackImpl cmp) const
Referenced by sead::PtrArray< T >::compare.
void sead::PtrArrayImpl::uniq(CompareCallbackImpl cmp)
Referenced by sead::PtrArray< T >::uniq, sead::PtrArray< T >::uniq.
s32 sead::PtrArrayImpl::binarySearch(const void *ptr, CompareCallbackImpl cmp) const
References mPtrNum, mPtrs.
Referenced by sead::PtrArray< T >::binarySearch, sead::PtrArray< T >::binarySearch.