sead::Matrix33CalcCommon
typedef Policies<T>::Mtx33Base sead::Matrix33CalcCommon< T >::Base
typedef Policies<T>::Mtx34Base sead::Matrix33CalcCommon< T >::Mtx34
typedef Policies<T>::QuatBase sead::Matrix33CalcCommon< T >::Quat
typedef Policies<T>::Vec3Base sead::Matrix33CalcCommon< T >::Vec3
void sead::Matrix33CalcCommon< T >::makeIdentity(Base &o)
References sead::BaseMtx33< T >::m.
Referenced by sead::Matrix33< T >::makeIdentity.
void sead::Matrix33CalcCommon< T >::makeZero(Base &o)
References sead::BaseMtx33< T >::m.
Referenced by sead::Matrix33< T >::makeZero.
void sead::Matrix33CalcCommon< T >::copy(Base &o, const Base &n)
References sead::BaseMtx33< T >::m.
Referenced by sead::Matrix33< T >::Matrix33, sead::Matrix33< T >::operator=.
void sead::Matrix33CalcCommon< T >::copy(Base &o, const Mtx34 &n)
References sead::BaseMtx33< T >::m, sead::BaseMtx34< T >::m.
void sead::Matrix33CalcCommon< T >::inverse(Base &o, const Base &n)
References sead::BaseMtx33< T >::m.
Referenced by sead::Matrix33< T >::setInverse.
void sead::Matrix33CalcCommon< T >::inverseTranspose(Base &o, const Base &n)
References sead::BaseMtx33< T >::m.
Referenced by sead::Matrix33< T >::setInverseTranspose.
void sead::Matrix33CalcCommon< T >::multiply(Base &o, const Base &a, const Base &b)
References sead::BaseMtx33< T >::m.
Referenced by sead::Matrix33< T >::setMul, sead::Matrix33< T >::setMul, sead::Matrix33< T >::setMul.
void sead::Matrix33CalcCommon< T >::multiply(Base &o, const Mtx34 &a, const Base &b)
References sead::BaseMtx33< T >::m, sead::BaseMtx34< T >::m.
void sead::Matrix33CalcCommon< T >::multiply(Base &o, const Base &a, const Mtx34 &b)
References sead::BaseMtx33< T >::m, sead::BaseMtx34< T >::m.
void sead::Matrix33CalcCommon< T >::transpose(Base &o)
References sead::BaseMtx33< T >::m.
Referenced by sead::Matrix33< T >::transpose.
void sead::Matrix33CalcCommon< T >::transposeTo(Base &o, const Base &n)
References sead::BaseMtx33< T >::m, SEAD_ASSERT.
Referenced by sead::Matrix33< T >::setTranspose.
void sead::Matrix33CalcCommon< T >::makeQ(Base &o, const Quat &q)
References sead::BaseMtx33< T >::m, sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Matrix33< T >::fromQuat.
void sead::Matrix33CalcCommon< T >::makeR(Base &o, const Vec3 &r)
References sead::MathCalcCommon< T >::cos, sead::BaseMtx33< T >::m, sead::MathCalcCommon< T >::sin.
Referenced by sead::Matrix33< T >::makeR.
void sead::Matrix33CalcCommon< T >::makeRIdx(Base &o, u32 xr, u32 yr, u32 zr)
References sead::BaseMtx33< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix33< T >::makeRIdx.
void sead::Matrix33CalcCommon< T >::makeRzxyIdx(Base &o, u32 xr, u32 yr, u32 zr)
References sead::BaseMtx33< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix33< T >::makeRzxyIdx.
void sead::Matrix33CalcCommon< T >::makeS(Base &o, const Vec3 &s)
References sead::BaseMtx33< T >::m.
Referenced by sead::Matrix33< T >::makeS, sead::Matrix33< T >::makeS.
void sead::Matrix33CalcCommon< T >::makeSR(Base &o, const Vec3 &s, const Vec3 &r)
References sead::MathCalcCommon< T >::cos, sead::BaseMtx33< T >::m, sead::MathCalcCommon< T >::sin.
Referenced by sead::Matrix33< T >::makeSR.
void sead::Matrix33CalcCommon< T >::makeSRIdx(Base &o, const Vec3 &s, const Vector3< u32 > &r)
References sead::BaseMtx33< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix33< T >::makeSRIdx.
void sead::Matrix33CalcCommon< T >::makeSRzxyIdx(Base &o, const Vec3 &s, const Vector3< u32 > &r)
References sead::BaseMtx33< T >::m, sead::MathCalcCommon< T >::sinCosIdx.
Referenced by sead::Matrix33< T >::makeSRzxyIdx.
void sead::Matrix33CalcCommon< T >::toQuat(Quat &q, const Base &n)
References sead::BaseMtx33< T >::m, sead::MathCalcCommon< T >::sqrt, sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Matrix33< T >::toQuat.