sead::Vector2CalcCtr
typedef Policies<T>::Vec2Base sead::Vector2CalcCtr< T >::Base
void sead::Vector2CalcCtr< T >::add(Base &o, const Base &a, const Base &b)
References sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
Referenced by sead::Vector2< T >::operator+=.
void sead::Vector2CalcCtr< T >::sub(Base &o, const Base &a, const Base &b)
References sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
Referenced by sead::Vector2< T >::operator-=.
void sead::Vector2CalcCtr< T >::set(Base &o, const Base &v)
References sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
Referenced by sead::Vector2< T >::operator=, sead::Vector2< T >::set, sead::Vector2< T >::set, sead::Vector2< T >::Vector2.
void sead::Vector2CalcCtr< T >::set(Base &v, T x, T y)
References sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.