sead::FileDevice
FileOpenFlag
SeekOrigin
const s32 sead::FileDevice::cBufferMinAlignment
FixedSafeString<32> sead::FileDevice::mDriveName
Referenced by getDriveName, setDriveName.
bool sead::FileDevice::mPermission
Referenced by hasPermission, setHasPermission.
sead::FileDevice::FileDevice()
sead::FileDevice::FileDevice(const SafeString &name)
References setDriveName.
virtual sead::FileDevice::~FileDevice()
const SafeString & sead::FileDevice::getDriveName() const
References mDriveName.
void sead::FileDevice::setDriveName(const SafeString &name)
References sead::SafeStringBase< T >::cstr, mDriveName, SEAD_WARN.
Referenced by FileDevice.
bool sead::FileDevice::hasPermission() const
References mPermission.
void sead::FileDevice::setHasPermission(bool perm)
References mPermission.
bool sead::FileDevice::isAvailable() const
u8 * sead::FileDevice::tryLoad(LoadArg &arg)
bool sead::FileDevice::save(SaveArg &arg)
References SEAD_ASSERT_MSG, trySave.
bool sead::FileDevice::trySave(SaveArg &arg)
Referenced by save.
FileDevice * sead::FileDevice::open(FileHandle *handle, const SafeString &path, FileOpenFlag flag, u32 divSize=0)
References SEAD_ASSERT_MSG, tryOpen.
FileDevice * sead::FileDevice::tryOpen(FileHandle *handle, const SafeString &path, FileOpenFlag flag, u32 divSize=0)
Referenced by open.
bool sead::FileDevice::close(FileHandle *handle)
References SEAD_ASSERT_MSG, tryClose.
bool sead::FileDevice::tryClose(FileHandle *handle)
Referenced by close, sead::FileHandle::~FileHandle.
bool sead::FileDevice::flush(FileHandle *handle)
References SEAD_ASSERT_MSG, tryFlush.
bool sead::FileDevice::tryFlush(FileHandle *handle)
Referenced by flush.
bool sead::FileDevice::remove(const SafeString &str)
References SEAD_ASSERT_MSG, tryRemove.
bool sead::FileDevice::tryRemove(const SafeString &str)
Referenced by remove.
u32 sead::FileDevice::read(FileHandle *handle, u8 *data, u32 size)
References SEAD_ASSERT_MSG, tryRead.
bool sead::FileDevice::tryRead(u32 *bytesRead, FileHandle *handle, u8 *outBuffer, u32 bytesToRead)
Referenced by read.
u32 sead::FileDevice::write(FileHandle *handle, const u8 *data, u32 size)
References SEAD_ASSERT_MSG, tryWrite.
bool sead::FileDevice::tryWrite(u32 *bytesWritten, FileHandle *handle, const u8 *inBuffer, u32 bytesToWrite)
Referenced by write.
bool sead::FileDevice::seek(FileHandle *handle, s32 offset, SeekOrigin origin)
References SEAD_ASSERT_MSG, trySeek.
bool sead::FileDevice::trySeek(FileHandle *handle, s32 offset, SeekOrigin origin)
Referenced by seek.
u32 sead::FileDevice::getCurrentSeekPos(FileHandle *handle)
References SEAD_ASSERT_MSG, tryGetCurrentSeekPos.
bool sead::FileDevice::tryGetCurrentSeekPos(u32 *seekPos, FileHandle *handle)
Referenced by getCurrentSeekPos.
u32 sead::FileDevice::getFileSize(const SafeString &path)
References SEAD_ASSERT_MSG, tryGetFileSize.
bool sead::FileDevice::tryGetFileSize(u32 *fileSize, const SafeString &path)
Referenced by getFileSize, getFileSize.
u32 sead::FileDevice::getFileSize(FileHandle *handle)
References SEAD_ASSERT_MSG, tryGetFileSize.
bool sead::FileDevice::tryGetFileSize(u32 *size, FileHandle *handle)
bool sead::FileDevice::isExistFile(const SafeString &path)
References SEAD_ASSERT_MSG, tryIsExistFile.
bool sead::FileDevice::tryIsExistFile(bool *exists, const SafeString &path)
Referenced by isExistFile.
bool sead::FileDevice::isExistDirectory(const SafeString &path)
References SEAD_ASSERT_MSG, tryIsExistDirectory.
bool sead::FileDevice::tryIsExistDirectory(bool *exists, const SafeString &path)
Referenced by isExistDirectory.
FileDevice * sead::FileDevice::openDirectory(DirectoryHandle *handle, const SafeString &path)
References SEAD_ASSERT_MSG, tryOpenDirectory.
FileDevice * sead::FileDevice::tryOpenDirectory(DirectoryHandle *handle, const SafeString &path)
Referenced by openDirectory.
bool sead::FileDevice::closeDirectory(DirectoryHandle *handle)
References SEAD_ASSERT_MSG, tryCloseDirectory.
bool sead::FileDevice::tryCloseDirectory(DirectoryHandle *handle)
Referenced by closeDirectory, sead::DirectoryHandle::~DirectoryHandle.
u32 sead::FileDevice::readDirectory(DirectoryHandle *handle, DirectoryEntry *entries, u32 num_entries)
References SEAD_ASSERT_MSG, tryReadDirectory.
bool sead::FileDevice::tryReadDirectory(u32 *entriesRead, DirectoryHandle *handle, DirectoryEntry *entries, u32 entriesToRead)
Referenced by readDirectory.
bool sead::FileDevice::makeDirectory(const SafeString &path, u32 x)
References SEAD_ASSERT_MSG, tryMakeDirectory.
bool sead::FileDevice::tryMakeDirectory(const SafeString &path, u32)
Referenced by makeDirectory.
bool sead::FileDevice::makeDirectoryWithParent(const SafeString &path, u32 x)
References SEAD_ASSERT_MSG, tryMakeDirectoryWithParent.
bool sead::FileDevice::tryMakeDirectoryWithParent(const SafeString &path, u32)
Referenced by makeDirectoryWithParent.
s32 sead::FileDevice::getLastRawError() const
virtual void sead::FileDevice::traceFilePath(const SafeString &path) const
virtual void sead::FileDevice::traceDirectoryPath(const SafeString &path) const
virtual void sead::FileDevice::resolveFilePath(BufferedSafeString *out, const SafeString &path) const
virtual void sead::FileDevice::resolveDirectoryPath(BufferedSafeString *out, const SafeString &path) const
virtual bool sead::FileDevice::isMatchDevice_(const HandleBase *handle) const
virtual bool sead::FileDevice::doIsAvailable_() const =0
virtual u8 * sead::FileDevice::doLoad_(LoadArg &arg)
virtual bool sead::FileDevice::doSave_(SaveArg &arg)
virtual FileDevice * sead::FileDevice::doOpen_(FileHandle *handle, const SafeString &path, FileOpenFlag flag)=0
virtual bool sead::FileDevice::doClose_(FileHandle *handle)=0
virtual bool sead::FileDevice::doFlush_(FileHandle *handle)=0
virtual bool sead::FileDevice::doRemove_(const SafeString &str)=0
virtual bool sead::FileDevice::doRead_(u32 *bytesRead, FileHandle *handle, u8 *outBuffer, u32 bytesToRead)=0
virtual bool sead::FileDevice::doWrite_(u32 *bytesWritten, FileHandle *handle, const u8 *inBuffer, u32 bytesToWrite)=0
virtual bool sead::FileDevice::doSeek_(FileHandle *handle, s32 offset, SeekOrigin origin)=0
virtual bool sead::FileDevice::doGetCurrentSeekPos_(u32 *seekPos, FileHandle *handle)=0
virtual bool sead::FileDevice::doGetFileSize_(u32 *fileSize, const SafeString &path)=0
virtual bool sead::FileDevice::doGetFileSize_(u32 *fileSize, FileHandle *handle)=0
virtual bool sead::FileDevice::doIsExistFile_(bool *exists, const SafeString &path)=0
virtual bool sead::FileDevice::doIsExistDirectory_(bool *exists, const SafeString &path)=0
virtual FileDevice * sead::FileDevice::doOpenDirectory_(DirectoryHandle *handle, const SafeString &path)=0
virtual bool sead::FileDevice::doCloseDirectory_(DirectoryHandle *handle)=0
virtual bool sead::FileDevice::doReadDirectory_(u32 *entriesRead, DirectoryHandle *handle, DirectoryEntry *entries, u32 entriesToRead)=0
virtual bool sead::FileDevice::doMakeDirectory_(const SafeString &path, u32)=0
virtual s32 sead::FileDevice::doGetLastRawError_() const =0
virtual void sead::FileDevice::doTracePath_(const SafeString &path) const
virtual void sead::FileDevice::doResolvePath_(BufferedSafeString *out, const SafeString &path) const
void sead::FileDevice::setFileHandleDivSize_(FileHandle *handle, u32 divSize) const
void sead::FileDevice::setHandleBaseFileDevice_(HandleBase *handle, FileDevice *device) const
void sead::FileDevice::setHandleBaseOriginalFileDevice_(HandleBase *handle, FileDevice *device) const
HandleBuffer & sead::FileDevice::getHandleBaseHandleBuffer_(HandleBase *handle) const