sead::Matrix22CalcCommon
typedef Policies<T>::Mtx22Base sead::Matrix22CalcCommon< T >::Base
void sead::Matrix22CalcCommon< T >::makeIdentity(Base &o)
References sead::BaseMtx22< T >::m.
Referenced by sead::Matrix22< T >::makeIdentity.
void sead::Matrix22CalcCommon< T >::makeZero(Base &o)
References sead::BaseMtx22< T >::m.
Referenced by sead::Matrix22< T >::makeZero.
void sead::Matrix22CalcCommon< T >::copy(Base &o, const Base &n)
References sead::BaseMtx22< T >::m.
Referenced by sead::Matrix22< T >::operator=.
void sead::Matrix22CalcCommon< T >::inverse(Base &o, const Base &n)
References sead::BaseMtx22< T >::m.
Referenced by sead::Matrix22< T >::setInverse.
void sead::Matrix22CalcCommon< T >::inverseTranspose(Base &o, const Base &n)
References sead::BaseMtx22< T >::m.
Referenced by sead::Matrix22< T >::setInverseTranspose.
void sead::Matrix22CalcCommon< T >::multiply(Base &o, const Base &a, const Base &b)
References sead::BaseMtx22< T >::m.
Referenced by sead::Matrix22< T >::setMul.
void sead::Matrix22CalcCommon< T >::transpose(Base &o)
References sead::BaseMtx22< T >::m.
Referenced by sead::Matrix22< T >::transpose.
void sead::Matrix22CalcCommon< T >::transposeTo(Base &o, const Base &n)
References sead::BaseMtx22< T >::m, SEAD_ASSERT.
Referenced by sead::Matrix22< T >::setTranspose.