sead::QuatCalcCommon
typedef Policies<T>::QuatBase sead::QuatCalcCommon< T >::Base
typedef Policies<T>::Vec3Base sead::QuatCalcCommon< T >::Vec3
T sead::QuatCalcCommon< T >::length(const Base &v)
Referenced by sead::Quat< T >::length.
T sead::QuatCalcCommon< T >::normalize(Base &v)
References sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Quat< T >::normalize.
T sead::QuatCalcCommon< T >::dot(const Base &u, const Base &v)
References sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Quat< T >::dot.
void sead::QuatCalcCommon< T >::setMul(Base &out, const Base &u, const Base &v)
References sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Quat< T >::operator*=.
static void sead::QuatCalcCommon< T >::slerpTo(Base &out, const Base &q1, const Base &q2, f32 t)
void sead::QuatCalcCommon< T >::makeUnit(Base &q)
Referenced by sead::Quat< T >::makeUnit.
bool sead::QuatCalcCommon< T >::makeVectorRotation(Base &q, const Vec3 &from, const Vec3 &to)
References sead::Vector3CalcCtr< T >::cross, sead::Vector3CalcCtr< T >::dot, sead::MathCalcCommon< T >::sqrt, sead::BaseQuat< T >::x.
Referenced by sead::Quat< T >::makeVectorRotation.
void sead::QuatCalcCommon< T >::set(Base &q, T w, T x, T y, T z)
References sead::BaseQuat< T >::w, sead::BaseQuat< T >::x, sead::BaseQuat< T >::y, sead::BaseQuat< T >::z.
Referenced by sead::Quat< T >::Quat, sead::Quat< T >::set.
void sead::QuatCalcCommon< T >::setRPY(Base &q, T roll, T pitch, T yaw)
Referenced by sead::Quat< T >::setRPY.
static void sead::QuatCalcCommon< T >::calcRPY(Vec3 &rpy, const Base &q)
Referenced by sead::Quat< T >::calcRPY.