sead::TList
typedef int(* sead::TList< T >::CompareCallback) (const T *, const T *))(const T *, const T *)
sead::TList< T >::TList()
void sead::TList< T >::pushBack(TListNode< T > *item)
References sead::TList< T >::mergeSort, sead::ListImpl::pushBack.
void sead::TList< T >::pushFront(TListNode< T > *item)
References sead::TList< T >::mergeSort, sead::ListImpl::pushFront.
TListNode< T > * sead::TList< T >::popBack()
References sead::ListImpl::popBack.
TListNode< T > * sead::TList< T >::popFront()
References sead::ListImpl::popFront.
void sead::TList< T >::insertBefore(TListNode< T > *node, TListNode< T > *node_to_insert)
References sead::ListImpl::insertBefore, sead::TList< T >::mergeSort.
void sead::TList< T >::insertAfter(TListNode< T > *node, TListNode< T > *node_to_insert)
References sead::ListImpl::insertAfter, sead::TList< T >::mergeSort.
void sead::TList< T >::erase(TListNode< T > *item)
References sead::ListImpl::erase, sead::TList< T >::mergeSort.
Referenced by sead::TListNode< T >::erase.
TListNode< T > * sead::TList< T >::front() const
References sead::ListImpl::front.
TListNode< T > * sead::TList< T >::back() const
References sead::ListImpl::back.
TListNode< T > * sead::TList< T >::nth(int n) const
References sead::TList< T >::mergeSort, sead::ListImpl::nth.
s32 sead::TList< T >::indexOf(const TListNode< T > *node) const
References sead::ListImpl::indexOf, sead::TList< T >::mergeSort.
void sead::TList< T >::swap(TListNode< T > *n1, TListNode< T > *n2)
References sead::TList< T >::mergeSort, sead::ListImpl::swap.
void sead::TList< T >::moveAfter(TListNode< T > *basis, TListNode< T > *n)
References sead::TList< T >::mergeSort, sead::ListImpl::moveAfter.
void sead::TList< T >::moveBefore(TListNode< T > *basis, TListNode< T > *n)
References sead::TList< T >::mergeSort, sead::ListImpl::moveBefore.
void sead::TList< T >::sort(s32 offset, CompareCallback cmp)
References sead::TList< T >::mergeSort, sead::ListImpl::mergeSort.
void sead::TList< T >::mergeSort(s32 offset, CompareCallback cmp)
References sead::TList< T >::mergeSort, sead::ListImpl::mergeSort.
Referenced by sead::TList< T >::compareT, sead::TList< T >::erase, sead::TList< T >::find, sead::TList< T >::indexOf, sead::TList< T >::insertAfter, sead::TList< T >::insertBefore, sead::TList< T >::mergeSort, sead::TList< T >::moveAfter, sead::TList< T >::moveBefore, sead::TList< T >::next, sead::TList< T >::nth, sead::TList< T >::prev, sead::TList< T >::pushBack, sead::TList< T >::pushFront, sead::TList< T >::sort, sead::TList< T >::swap, sead::TList< T >::uniq.
TListNode< T > * sead::TList< T >::find(const void *ptr, s32 offset, CompareCallback cmp) const
References sead::ListImpl::find, sead::TList< T >::mergeSort.
void sead::TList< T >::uniq(s32 offset, CompareCallback cmp)
References sead::TList< T >::mergeSort, sead::ListImpl::uniq.
void sead::TList< T >::clear()
References sead::ListImpl::clear.
TListNode< T > * sead::TList< T >::prev(const TListNode< T > *node) const
References sead::TList< T >::mergeSort, sead::ListImpl::mStartEnd.
TListNode< T > * sead::TList< T >::next(const TListNode< T > *node) const
References sead::TList< T >::mergeSort, sead::ListImpl::mStartEnd.
iterator sead::TList< T >::begin() const
References sead::ListImpl::mStartEnd, sead::ListNode::next.
iterator sead::TList< T >::end() const
References sead::ListImpl::mStartEnd.
robustIterator sead::TList< T >::robustBegin() const
References sead::ListImpl::mStartEnd, sead::ListNode::next.
Referenced by sead::TList< T >::RobustRange::begin.
robustIterator sead::TList< T >::robustEnd() const
References sead::ListImpl::mStartEnd.
Referenced by sead::TList< T >::RobustRange::end.
RobustRange sead::TList< T >::robustRange() const
static int sead::TList< T >::compareT(const T *a, const T *b)
References sead::TList< T >::mergeSort.