sead::PtrArray
typedef s32(* sead::PtrArray< T >::CompareCallback) (const T *, const T *))(const T *, const T *)
sead::PtrArray< T >::PtrArray()
sead::PtrArray< T >::PtrArray(s32 ptrNumMax, T **buf)
T * sead::PtrArray< T >::at(s32 pos) const
References sead::PtrArrayImpl::at.
Referenced by sead::PtrArray< T >::back, sead::PtrArray< T >::front, sead::PtrArray< T >::operator[].
T * sead::PtrArray< T >::unsafeAt(s32 pos) const
References sead::PtrArrayImpl::unsafeAt.
Referenced by sead::PtrArray< T >::operator().
T * sead::PtrArray< T >::operator()(s32 pos) const
References sead::PtrArray< T >::unsafeAt.
T * sead::PtrArray< T >::operator[](s32 pos) const
References sead::PtrArray< T >::at.
T * sead::PtrArray< T >::front() const
References sead::PtrArray< T >::at.
T * sead::PtrArray< T >::back() const
References sead::PtrArray< T >::at, sead::PtrArrayImpl::mPtrNum.
void sead::PtrArray< T >::pushBack(T *ptr)
References sead::PtrArrayImpl::pushBack.
void sead::PtrArray< T >::pushFront(T *ptr)
References sead::PtrArrayImpl::pushFront.
T * sead::PtrArray< T >::popBack()
References sead::PtrArrayImpl::popBack.
T * sead::PtrArray< T >::popFront()
References sead::PtrArrayImpl::popFront.
void sead::PtrArray< T >::insert(s32 pos, T *ptr)
References sead::PtrArrayImpl::insert.
void sead::PtrArray< T >::insert(s32 pos, T *array, s32 count)
References sead::PtrArrayImpl::insertArray.
void sead::PtrArray< T >::replace(s32 pos, T *ptr)
References sead::PtrArrayImpl::replace.
s32 sead::PtrArray< T >::indexOf(const T *ptr) const
References sead::PtrArrayImpl::indexOf.
bool sead::PtrArray< T >::equal(const PtrArray &other, CompareCallback cmp) const
References sead::PtrArrayImpl::equal.
Referenced by sead::PtrArray< T >::operator==.
s32 sead::PtrArray< T >::compare(const PtrArray &other, CompareCallback cmp) const
References sead::PtrArrayImpl::compare.
T * sead::PtrArray< T >::find(const T *ptr, CompareCallback cmp) const
References sead::PtrArrayImpl::find.
s32 sead::PtrArray< T >::search(const T *ptr, CompareCallback cmp) const
References sead::PtrArrayImpl::search.
s32 sead::PtrArray< T >::binarySearch(const T *ptr) const
References sead::PtrArrayImpl::binarySearch, sead::PtrArray< T >::compareT.
s32 sead::PtrArray< T >::binarySearch(const T *ptr, CompareCallback cmp) const
References sead::PtrArrayImpl::binarySearch.
bool sead::PtrArray< T >::operator==(const PtrArray &other) const
References sead::PtrArray< T >::compareT, sead::PtrArray< T >::equal.
bool sead::PtrArray< T >::operator!=(const PtrArray &other) const
void sead::PtrArray< T >::uniq()
References sead::PtrArray< T >::compareT, sead::PtrArrayImpl::uniq.
void sead::PtrArray< T >::uniq(CompareCallback cmp)
References sead::PtrArrayImpl::uniq.
iterator sead::PtrArray< T >::begin() const
References sead::PtrArray< T >::data.
iterator sead::PtrArray< T >::end() const
References sead::PtrArray< T >::data, sead::PtrArrayImpl::mPtrNum.
constIterator sead::PtrArray< T >::constBegin() const
References sead::PtrArray< T >::data.
constIterator sead::PtrArray< T >::constEnd() const
References sead::PtrArray< T >::data, sead::PtrArrayImpl::mPtrNum.
T ** sead::PtrArray< T >::data() const
References sead::PtrArrayImpl::mPtrs.
Referenced by sead::PtrArray< T >::begin, sead::PtrArray< T >::constBegin, sead::PtrArray< T >::constEnd, sead::PtrArray< T >::dataBegin, sead::PtrArray< T >::dataEnd, sead::PtrArray< T >::end.
T ** sead::PtrArray< T >::dataBegin() const
References sead::PtrArray< T >::data.
T ** sead::PtrArray< T >::dataEnd() const
References sead::PtrArray< T >::data, sead::PtrArrayImpl::mPtrNum.
static int sead::PtrArray< T >::compareT(const void *a_, const void *b_)
Referenced by sead::PtrArray< T >::binarySearch, sead::PtrArray< T >::operator==, sead::PtrArray< T >::uniq.