sead::BitFlagUtil
static int sead::BitFlagUtil::countOnBit(u32 x)
Popcount.
Referenced by countContinuousOffBitFromRight, sead::BitFlag< T >::countOnBit.
static int sead::BitFlagUtil::countContinuousOffBitFromRight(u32 x)
Count trailing zeroes (ctz).
References countOnBit.
Referenced by sead::BitFlag< T >::countContinuousOffBitFromRight.
static int sead::BitFlagUtil::countRightOnBit(u32 x, int bit)
Referenced by sead::BitFlag< T >::countRightOnBit.
static int sead::BitFlagUtil::findOnBitFromRight(u32 x, int num)
Referenced by sead::BitFlag< T >::findOnBitFromRight.