sead::HeapMgr
typedef FixedPtrArray<Heap, 4> sead::HeapMgr::RootHeaps
typedef FixedPtrArray<Heap, 4> sead::HeapMgr::IndependentHeaps
HeapMgr sead::HeapMgr::sInstance
HeapMgr* sead::HeapMgr::sInstancePtr
Referenced by instance.
friend class ScopedCurrentHeapSetter
Arena sead::HeapMgr::sDefaultArena
HeapMgr::RootHeaps sead::HeapMgr::sRootHeaps
Referenced by getRootHeap, getRootHeapNum.
IndependentHeaps sead::HeapMgr::sIndependentHeaps
CriticalSection sead::HeapMgr::sHeapTreeLockCS
void* sead::HeapMgr::unk
void* sead::HeapMgr::mAllocFailedCallback
u8 sead::HeapMgr::unk1
sead::HeapMgr::HeapMgr()
Heap * sead::HeapMgr::getCurrentHeap()
Heap * sead::HeapMgr::findContainHeap(const void *ptr) const
static bool sead::HeapMgr::isContainedInAnyHeap(const void *ptr)
static HeapMgr * sead::HeapMgr::instance()
References sInstancePtr.
Referenced by sead::ScopedCurrentHeapSetter::ScopedCurrentHeapSetter, sead::ScopedCurrentHeapSetter::~ScopedCurrentHeapSetter.
static s32 sead::HeapMgr::getRootHeapNum()
References sead::PtrArrayImpl::capacity, sRootHeaps.
Referenced by sead::HeapArray::getHeap.
static Heap * sead::HeapMgr::getRootHeap(int index)
References sRootHeaps.
sead::Heap * sead::HeapMgr::setCurrentHeap_(sead::Heap *heap)
Set the current heap to the specified heap and returns the previous "current heap".
Referenced by sead::ScopedCurrentHeapSetter::~ScopedCurrentHeapSetter.