sead::TreeNode
TreeNode* sead::TreeNode::mParent
Referenced by sead::TTreeNode< T >::parent.
TreeNode* sead::TreeNode::mChild
Referenced by sead::TTreeNode< T >::child.
TreeNode* sead::TreeNode::mNext
Referenced by sead::TTreeNode< T >::next.
TreeNode* sead::TreeNode::mPrev
Referenced by sead::TTreeNode< T >::prev.
sead::TreeNode::TreeNode()
void sead::TreeNode::clearLinks()
s32 sead::TreeNode::countChildren() const
void sead::TreeNode::detachAll()
void sead::TreeNode::detachSubTree()
TreeNode * sead::TreeNode::findRoot()
Referenced by sead::TTreeNode< T >::findRoot, sead::TTreeNode< T >::findRoot.
const TreeNode * sead::TreeNode::findRoot() const
void sead::TreeNode::insertAfterSelf(TreeNode *node)
Referenced by sead::TTreeNode< T >::insertAfterSelf.
void sead::TreeNode::insertBeforeSelf(TreeNode *node)
Referenced by sead::TTreeNode< T >::insertBeforeSelf.
void sead::TreeNode::pushBackChild(TreeNode *node)
Referenced by sead::TTreeNode< T >::pushBackChild.
void sead::TreeNode::pushBackSibling(TreeNode *node)
Referenced by sead::TTreeNode< T >::pushBackSibling.
void sead::TreeNode::pushFrontChild(TreeNode *node)
Referenced by sead::TTreeNode< T >::pushFrontChild.
void sead::TreeNode::clearChildLinksRecursively_()