sead::Vector3CalcCtr
typedef Policies<T>::Vec3Base sead::Vector3CalcCtr< T >::Base
typedef Policies<T>::Mtx33Base sead::Vector3CalcCtr< T >::Mtx33
typedef Policies<T>::Mtx34Base sead::Vector3CalcCtr< T >::Mtx34
void sead::Vector3CalcCtr< T >::add(Base &o, const Base &a, const Base &b)
Referenced by sead::Vector3< T >::add, sead::Vector3< T >::operator+=.
void sead::Vector3CalcCtr< T >::sub(Base &o, const Base &a, const Base &b)
Referenced by sead::Vector3< T >::operator-=.
void sead::Vector3CalcCtr< T >::mul(Base &o, const Mtx33 &m, const Base &a)
References sead::BaseMtx33< T >::m.
Referenced by sead::Vector3< T >::setMul, sead::Vector3< T >::setMul.
void sead::Vector3CalcCtr< T >::mul(Base &o, const Mtx34 &m, const Base &a)
Apply a transformation m (rotation + translation) to the vector a.
References sead::BaseMtx34< T >::m.
void sead::Vector3CalcCtr< T >::cross(Base &o, const Base &a, const Base &b)
References sead::Vector3CalcCtr< T >::set.
Referenced by sead::QuatCalcCommon< T >::makeVectorRotation, sead::Vector3< T >::setCross.
T sead::Vector3CalcCtr< T >::dot(const Base &a, const Base &b)
Referenced by sead::Vector3< T >::dot, sead::QuatCalcCommon< T >::makeVectorRotation.
T sead::Vector3CalcCtr< T >::squaredLength(const Base &v)
Referenced by sead::Vector3< T >::squaredLength.
T sead::Vector3CalcCtr< T >::length(const Base &v)
References sead::MathCalcCommon< T >::sqrt.
Referenced by sead::Vector3< T >::length.
bool sead::Vector3CalcCtr< T >::equals(const Base &lhs, const Base &rhs, T epsilon)
Referenced by sead::Vector3< T >::equals.
void sead::Vector3CalcCtr< T >::multScalar(Base &o, const Base &v, T t)
Referenced by sead::Vector3< T >::multScalar, sead::Vector3< T >::operator*=.
void sead::Vector3CalcCtr< T >::multScalarAdd(Base &o, T t, const Base &a, const Base &b)
Referenced by sead::Vector3< T >::setScaleAdd.
T sead::Vector3CalcCtr< T >::normalize(Base &v)
Referenced by sead::Vector3< T >::normalize.
void sead::Vector3CalcCtr< T >::set(Base &o, const Base &v)
Referenced by sead::Vector3CalcCtr< T >::cross, sead::Vector3< T >::operator=, sead::Vector3< T >::set, sead::Vector3< T >::set, sead::Vector3< T >::Vector3.
void sead::Vector3CalcCtr< T >::set(Base &v, T x, T y, T z)
void sead::Vector3CalcCtr< f32 >::add(Base &o, const Base &a, const Base &b)
void sead::Vector3CalcCtr< f32 >::sub(Base &o, const Base &a, const Base &b)
void sead::Vector3CalcCtr< f32 >::multScalar(Base &o, const Base &v, f32 t)