sead::ListImpl
typedef int(* sead::ListImpl::CompareCallbackImpl) (const void *, const void *))(const void *, const void *)
ListNode sead::ListImpl::mStartEnd
Referenced by back, sead::OffsetList< T >::begin, sead::TList< T >::begin, clear, sead::OffsetList< T >::end, sead::TList< T >::end, front, indexOf, ListImpl, mergeSort, sead::OffsetList< T >::next, sead::TList< T >::next, nth, popBack, popFront, sead::OffsetList< T >::prev, sead::TList< T >::prev, pushBack, pushFront, sead::OffsetList< T >::robustBegin, sead::TList< T >::robustBegin, sead::OffsetList< T >::robustEnd, sead::TList< T >::robustEnd.
s32 sead::ListImpl::mCount
Referenced by back, clear, erase, front, insertAfter, insertBefore, isEmpty, nth, popBack, popFront, pushBack, pushFront, size.
sead::ListImpl::ListImpl()
References sead::ListNode::mNext, sead::ListNode::mPrev, mStartEnd.
bool sead::ListImpl::isEmpty() const
References mCount.
s32 sead::ListImpl::size() const
References mCount.
Referenced by mergeSort.
void sead::ListImpl::reverse()
void sead::ListImpl::shuffle()
void sead::ListImpl::shuffle(Random *random)
bool sead::ListImpl::checkLinks() const
void sead::ListImpl::sort(s32 offset, const ComparePredicate &cmp)
References mergeSort.
void sead::ListImpl::mergeSort(s32 offset, const ComparePredicate &cmp)
References mergeSort, sead::ListNode::mNext, sead::ListNode::mPrev, mStartEnd, size.
Referenced by clear, erase, indexOf, insertAfter, insertBefore, sead::OffsetList< T >::mergeSort, sead::TList< T >::mergeSort, mergeSort, nth, pushBack, pushFront, sead::OffsetList< T >::sort, sead::TList< T >::sort, sort, swap.
void sead::ListImpl::pushBack(ListNode *item)
References sead::ListNode::insertFront_, mCount, mergeSort, mStartEnd.
Referenced by sead::OffsetList< T >::pushBack, sead::TList< T >::pushBack.
void sead::ListImpl::pushFront(ListNode *item)
References sead::ListNode::insertBack_, mCount, mergeSort, mStartEnd.
Referenced by sead::OffsetList< T >::pushFront, sead::TList< T >::pushFront.
ListNode * sead::ListImpl::popBack()
References back, sead::ListNode::erase_, mCount, sead::ListNode::mPrev, mStartEnd.
Referenced by sead::OffsetList< T >::popBack, sead::TList< T >::popBack.
ListNode * sead::ListImpl::popFront()
References sead::ListNode::erase_, front, mCount, sead::ListNode::mNext, mStartEnd.
Referenced by sead::OffsetList< T >::popFront, sead::TList< T >::popFront.
void sead::ListImpl::insertBefore(ListNode *node, ListNode *node_to_insert)
References mCount, mergeSort.
Referenced by sead::OffsetList< T >::insertBefore, sead::TList< T >::insertBefore.
void sead::ListImpl::insertAfter(ListNode *node, ListNode *node_to_insert)
References mCount, mergeSort.
Referenced by sead::OffsetList< T >::insertAfter, sead::TList< T >::insertAfter.
void sead::ListImpl::erase(ListNode *item)
References mCount, mergeSort.
Referenced by sead::OffsetList< T >::erase, sead::TList< T >::erase.
ListNode * sead::ListImpl::front() const
References mCount, sead::ListNode::mNext, mStartEnd.
Referenced by sead::OffsetList< T >::front, sead::TList< T >::front, popFront.
ListNode * sead::ListImpl::back() const
References mCount, sead::ListNode::mPrev, mStartEnd.
Referenced by sead::OffsetList< T >::back, sead::TList< T >::back, popBack.
ListNode * sead::ListImpl::nth(int n) const
References mCount, mergeSort, sead::ListNode::mNext, mStartEnd, SEAD_ASSERT_MSG.
Referenced by sead::TList< T >::nth, sead::OffsetList< T >::nth.
s32 sead::ListImpl::indexOf(const ListNode *) const
References mergeSort, sead::ListNode::mNext, mStartEnd.
Referenced by sead::OffsetList< T >::indexOf, sead::TList< T >::indexOf.
void sead::ListImpl::swap(ListNode *n1, ListNode *n2)
References sead::ListNode::erase_, mergeSort, sead::ListNode::mPrev, SEAD_ASSERT.
Referenced by sead::OffsetList< T >::swap, sead::TList< T >::swap.
void sead::ListImpl::moveAfter(ListNode *basis, ListNode *n)
Referenced by sead::OffsetList< T >::moveAfter, sead::TList< T >::moveAfter.
void sead::ListImpl::moveBefore(ListNode *basis, ListNode *n)
Referenced by sead::OffsetList< T >::moveBefore, sead::TList< T >::moveBefore.
ListNode * sead::ListImpl::find(const void *ptr, s32 offset, CompareCallbackImpl cmp) const
Referenced by sead::OffsetList< T >::find, sead::TList< T >::find.
void sead::ListImpl::uniq(s32 offset, CompareCallbackImpl cmp)
Referenced by sead::OffsetList< T >::uniq, sead::TList< T >::uniq.
void sead::ListImpl::clear()
References sead::ListNode::init_, mCount, mergeSort, sead::ListNode::mNext, sead::ListNode::mPrev, mStartEnd.
Referenced by sead::OffsetList< T >::clear, sead::TList< T >::clear.
static void sead::ListImpl::mergeSortImpl_(ListNode *front, ListNode *back, s32 num, s32 offset, const ComparePredicate &predicate)