sead::AtomicBase
sead::AtomicBase< T >::AtomicBase(T value)
sead::AtomicBase< T >::AtomicBase(AtomicDirectInitTag, T value)
Directly initialises the underlying atomic with the specified value.
Note that initialisation is not atomic.
sead::AtomicBase< T >::AtomicBase(const AtomicBase &rhs)
sead::AtomicBase< T >::operator T() const
References sead::AtomicBase< T >::load.
AtomicBase & sead::AtomicBase< T >::operator=(const AtomicBase &rhs)
References sead::AtomicBase< T >::load, sead::AtomicBase< T >::store.
AtomicBase & sead::AtomicBase< T >::operator=(T value)
References sead::AtomicBase< T >::store.
T sead::AtomicBase< T >::load() const
Load the current value, as if with memory_order_relaxed.
Referenced by sead::AtomicBase< T >::operator T, sead::AtomicBase< T >::operator=.
void sead::AtomicBase< T >::store(T value)
Store a new value, as if with memory_order_relaxed.
Referenced by sead::AtomicBase< T >::operator=, sead::AtomicBase< T >::operator=.
void sead::AtomicBase< T >::storeNonAtomic(T value)
Non-atomically store a new value.
T sead::AtomicBase< T >::exchange(T value)
Exchange/swap the current value, as if with memory_order_relaxed.
the previous value
bool sead::AtomicBase< T >::compareExchange(T expected, T desired, T *original=nullptr)
Load the current value and if it is equal to expected, store desired as if with memory_order_relaxed.
Otherwise, this sets original to the current value. expected The value expected to be found in the atomic object, and to be replaced. desired The new value to store in the atomic object if expected was found. original The value that was found in the atomic object if the comparison fails. May be null. Note that this is only updated when false is returned. true if and only if the value was modified