sead::Atomic
T sead::Atomic< T >::fetchAdd(T x)
Referenced by sead::Atomic< T >::increment, sead::Atomic< T >::operator++, sead::Atomic< T >::operator++, sead::Atomic< T >::operator+=.
T sead::Atomic< T >::fetchSub(T x)
Referenced by sead::Atomic< T >::decrement, sead::Atomic< T >::operator--, sead::Atomic< T >::operator--, sead::Atomic< T >::operator-=.
T sead::Atomic< T >::fetchAnd(T x)
Referenced by sead::Atomic< T >::operator&=.
T sead::Atomic< T >::fetchOr(T x)
Referenced by sead::Atomic< T >::operator|=.
T sead::Atomic< T >::fetchXor(T x)
Referenced by sead::Atomic< T >::operator^=.
T sead::Atomic< T >::increment()
References sead::Atomic< T >::fetchAdd.
T sead::Atomic< T >::decrement()
References sead::Atomic< T >::fetchSub.
bool sead::Atomic< T >::isBitOn(unsigned int bit) const
bool sead::Atomic< T >::setBitOn(unsigned int bit)
whether the bit was cleared and is now set.
bool sead::Atomic< T >::setBitOff(unsigned int bit)
whether the bit was set and is now cleared.
T sead::Atomic< T >::operator+=(T x)
References sead::Atomic< T >::fetchAdd.
T sead::Atomic< T >::operator-=(T x)
References sead::Atomic< T >::fetchSub.
T sead::Atomic< T >::operator&=(T x)
References sead::Atomic< T >::fetchAnd.
T sead::Atomic< T >::operator|=(T x)
References sead::Atomic< T >::fetchOr.
T sead::Atomic< T >::operator^=(T x)
References sead::Atomic< T >::fetchXor.
T sead::Atomic< T >::operator++()
References sead::Atomic< T >::fetchAdd.
T sead::Atomic< T >::operator++(int)
References sead::Atomic< T >::fetchAdd.
T sead::Atomic< T >::operator--()
References sead::Atomic< T >::fetchSub.
T sead::Atomic< T >::operator--(int)
References sead::Atomic< T >::fetchSub.