sead::Vector2
const Vector2 sead::Vector2< T >::zero
const Vector2 sead::Vector2< T >::ex
const Vector2 sead::Vector2< T >::ey
const Vector2 sead::Vector2< T >::ones
sead::Vector2< T >::Vector2()
This constructor leaves member variables uninitialized.
sead::Vector2< T >::Vector2(const Vector2 &other)
sead::Vector2< T >::Vector2(T x, T y)
References sead::Vector2CalcCtr< T >::set.
Vector2< T > & sead::Vector2< T >::operator=(const Vector2 &other)
References sead::Vector2CalcCtr< T >::set.
Vector2< T > & sead::Vector2< T >::operator+=(const Vector2 &other)
References sead::Vector2CalcCtr< T >::add.
Vector2< T > & sead::Vector2< T >::operator-=(const Vector2 &other)
References sead::Vector2CalcCtr< T >::sub.
Vector2< T > & sead::Vector2< T >::operator*=(T t)
Vector2< T > & sead::Vector2< T >::operator/=(T t)
bool sead::Vector2< T >::operator==(const Vector2 &rhs) const
References sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
Referenced by sead::Vector2< T >::operator!=.
bool sead::Vector2< T >::operator!=(const Vector2 &rhs) const
References sead::Vector2< T >::operator==.
void sead::Vector2< T >::set(const Vector2 &other)
References sead::Vector2CalcCtr< T >::set.
Referenced by sead::BoundBox2< T >::getCenter, sead::BoundBox2< T >::setFromCenterAndXY.
void sead::Vector2< T >::set(T x_, T y_)
References sead::Vector2CalcCtr< T >::set.
const Vector2< f32 > sead::Vector2< f32 >::zero
const Vector2< f32 > sead::Vector2< f32 >::ex
const Vector2< f32 > sead::Vector2< f32 >::ey
const Vector2< f32 > sead::Vector2< f32 >::ones
const Vector2< f32 > sead::Vector2< f32 >::zero(0.0f, 0.0f)
const Vector2< f32 > sead::Vector2< f32 >::ex(1.0f, 0.0f)
const Vector2< f32 > sead::Vector2< f32 >::ey(0.0f, 1.0f)
const Vector2< f32 > sead::Vector2< f32 >::ones(1.0f, 1.0f)
Vector2 operator+(const Vector2 &a, const Vector2 &b)
Vector2 operator-(const Vector2 &a, const Vector2 &b)
Vector2 operator*(const Vector2 &a, T t)
Vector2 operator*(T t, const Vector2 &a)
Vector2 operator/(const Vector2 &a, T t)