sead::BoundBox2
typedef sead::Vector2<T> sead::BoundBox2< T >::Vector2
Vector2 sead::BoundBox2< T >::mMin
Referenced by sead::BoundBox2< T >::getBL, sead::BoundBox2< T >::getHalfSizeX, sead::BoundBox2< T >::getHalfSizeY, sead::BoundBox2< T >::getMin, sead::BoundBox2< T >::getSizeX, sead::BoundBox2< T >::getSizeY, sead::BoundBox2< T >::getTL, sead::BoundBox2< T >::getTR.
Vector2 sead::BoundBox2< T >::mMax
Referenced by sead::BoundBox2< T >::getBL, sead::BoundBox2< T >::getBR, sead::BoundBox2< T >::getHalfSizeX, sead::BoundBox2< T >::getHalfSizeY, sead::BoundBox2< T >::getMax, sead::BoundBox2< T >::getSizeX, sead::BoundBox2< T >::getSizeY, sead::BoundBox2< T >::getTR.
const BoundBox2<T> sead::BoundBox2< T >::cUndefined
sead::BoundBox2< T >::BoundBox2()
References sead::BoundBox2< T >::setUndef.
sead::BoundBox2< T >::BoundBox2(T x0, T y0, T x1, T y1)
References sead::BoundBox2< T >::set.
sead::BoundBox2< T >::BoundBox2(const Vector2 &min, const Vector2 &max)
T sead::BoundBox2< T >::getSizeX() const
References sead::BoundBox2< T >::mMax, sead::BoundBox2< T >::mMin, sead::BaseVec2< T >::x.
T sead::BoundBox2< T >::getSizeY() const
References sead::BoundBox2< T >::mMax, sead::BoundBox2< T >::mMin, sead::BaseVec2< T >::y.
T sead::BoundBox2< T >::getHalfSizeX() const
References sead::BoundBox2< T >::mMax, sead::BoundBox2< T >::mMin, sead::BaseVec2< T >::x.
T sead::BoundBox2< T >::getHalfSizeY() const
References sead::BoundBox2< T >::mMax, sead::BoundBox2< T >::mMin, sead::BaseVec2< T >::y.
const Vector2 & sead::BoundBox2< T >::getMin() const
References sead::BoundBox2< T >::mMin.
const Vector2 & sead::BoundBox2< T >::getMax() const
References sead::BoundBox2< T >::mMax.
Vector2 sead::BoundBox2< T >::getTL() const
References sead::BoundBox2< T >::mMin.
Vector2 sead::BoundBox2< T >::getTR() const
References sead::BoundBox2< T >::mMax, sead::BoundBox2< T >::mMin, sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
Vector2 sead::BoundBox2< T >::getBL() const
References sead::BoundBox2< T >::mMax, sead::BoundBox2< T >::mMin, sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
Vector2 sead::BoundBox2< T >::getBR() const
References sead::BoundBox2< T >::mMax.
Vector2< T > sead::BoundBox2< T >::getCenter() const
void sead::BoundBox2< T >::getCenter(Vector2 *p) const
References sead::Vector2< T >::set.
bool sead::BoundBox2< T >::isUndef() const
bool sead::BoundBox2< T >::isInside(const Vector2 &p) const
References sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
void sead::BoundBox2< T >::setUndef()
References sead::MathCalcCommon< T >::maxNumber, sead::MathCalcCommon< T >::minNumber.
Referenced by sead::BoundBox2< T >::BoundBox2.
void sead::BoundBox2< T >::set(T x0, T y0, T x1, T y1)
Referenced by sead::BoundBox2< T >::BoundBox2.
void sead::BoundBox2< T >::set(const Vector2 &min, const Vector2 &max)
void sead::BoundBox2< T >::setMin(const Vector2 &min)
void sead::BoundBox2< T >::setMax(const Vector2 &max)
void sead::BoundBox2< T >::setFromCenterAndXY(T centerX, T centerY, T sizeX, T sizeY)
References sead::Vector2< T >::set.
Referenced by sead::BoundBox2< T >::setFromCenterAndXY.
void sead::BoundBox2< T >::setFromCornerAndXY(T cornerX, T cornerY, T sizeX, T sizeY)
void sead::BoundBox2< T >::setFromCenterAndXY(const Vector2 &center, T sizeX, T sizeY)
References sead::BoundBox2< T >::setFromCenterAndXY, sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
void sead::BoundBox2< T >::setFromCornerAndXY(const Vector2 &corner, T sizeX, T sizeY)
References sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
void sead::BoundBox2< T >::offset(T dx, T dy)
void sead::BoundBox2< T >::offset(const Vector2 &dv)
References sead::BaseVec2< T >::x, sead::BaseVec2< T >::y.
void sead::BoundBox2< T >::scaleX(T sx)
void sead::BoundBox2< T >::scaleY(T sy)